const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../fixtures/v50-visual-state.json'),'utf8'));
async function boot(page,width){const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('dialog',d=>d.accept());await page.setViewportSize({width,height:1000});await page.clock.setFixedTime(new Date('2026-10-06T12:00:00Z'));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.addInitScript(s=>{if(!localStorage.getItem('finize-budget-planner-v1'))localStorage.setItem('finize-budget-planner-v1',JSON.stringify(s));},fixture);await page.goto('/');await page.waitForFunction(()=>window.__finizeBootstrap?.rendered);await page.evaluate(()=>commitChange(()=>{state.meta.selectedMonth='2026-10';state.monthRecords={};state.transactions=[];state.recurringFixedExpenses=[{id:'fix-mortgage',naam:'Hypotheek',categorie:'Wonen',bedrag:100,financialFor:'gezamenlijk',rekening:'gezamenlijk',begindatum:'2026-01-01',actief:true,frequentieAantal:1,frequentieEenheid:'maanden',amountHistory:[{effectiveFrom:'2026-01-01',amount:100}]}];state.importSummaries=[];state.activeImportId='';state.manualTransactionReplacements=[];state.internalTransferPairs=[];state.advanceLedger=[];state.advanceRepayments=[];state.savingsCoverageAllocations=[];state.accountProfiles=[{id:'fix-joint',accountOwner:'gezamenlijk',identifier:'NL01JOINT',name:'Gezamenlijk'}];state.budgetDefaultsHistory=Object.fromEntries(['gezamenlijk','dion','dara'].map(owner=>[owner,[{effectiveFrom:'0000-01',rows:[{id:owner+'-clothing',post:'Kleding',bedrag:300}]}]]));state.spaardoelen=Object.fromEntries(['gezamenlijk','dion','dara'].map(owner=>[owner,[{id:'fix-goal-'+owner,naam:'Buffer '+owner,doelbedrag:4000,algespaard:2000,vasteInleg:25,favoriet:true,doeldatum:'2027-10-01'}]]));state.savingsGoalLedger=['gezamenlijk','dion','dara'].map(owner=>({id:'fix-opening-'+owner,goalId:'fix-goal-'+owner,source:'legacy-opening',effectiveAmount:2000,active:true}));}));await page.evaluate(()=>renderActiveTab());return errors;}
async function nav(page,owner){await page.evaluate(owner=>document.querySelector(`#tabs [data-tab="${owner}"]`).click(),owner);}
async function capture(page){return page.evaluate(()=>({state:JSON.stringify(state),forecast:FinizeTransactions.forecast('2026-10'),effects:FinizeTransactions.effects()}));}
for(const width of [390,768,1280,1440])test(`joint month KPI and goal table fit ${width}`,async({page})=>{
 const errors=await boot(page,width),before=await capture(page);
 for(const owner of ['gezamenlijk','dion','dara']){
  await nav(page,owner);
  const table=page.locator(`#tab-${owner} .u5-joint-goals-preview .goal-table:visible`);
  await expect(table).toBeVisible();await expect(table.locator('thead th')).toHaveCount(10);
  await expect(table.locator('tfoot')).toContainText('Totaal');
  expect(await table.locator('..').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
  expect(await table.evaluate(el=>el.getBoundingClientRect().right<=el.parentElement.getBoundingClientRect().right+1)).toBe(true);
  if(owner==='gezamenlijk'&&width<768){
   const card=page.locator('#tab-gezamenlijk .joint-first-row .joint-saving-card');
   await expect(card).toContainText('Over deze maand');
   const expected=await page.evaluate(()=>{const n=FinizeTransactions.forecast('2026-10').owners.gezamenlijk.available;return `${n<0?'-':''}€ ${Math.abs(n).toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}`;});
   await expect(card.locator('.mobile-kpi-value')).toHaveText(expected);
   await expect(card).not.toHaveAttribute('data-saving-edit');
   expect(await card.evaluate(el=>el.tagName)).toBe('DIV');
  }
  await expect(page.locator(`#tab-${owner} .u5-joint-goals-preview .savings-month-button:visible`)).toBeVisible();
  await evidence(page,`fit-goals-${owner}-${width}`);
 }
 expect(await capture(page)).toEqual(before);expect(errors).toEqual([]);
});
async function evidence(page,name){if(process.env.FINIZE_FIX_EVIDENCE){fs.mkdirSync(process.env.FINIZE_FIX_EVIDENCE,{recursive:true});await page.screenshot({path:path.join(process.env.FINIZE_FIX_EVIDENCE,name+'.png'),fullPage:true});}}
async function batch(page,{count=3,amount=-100,date='2026-09-17',id='fix-editor',matchCount=0}={}){return page.evaluate(async args=>{const u=FinizeUpdate4Runtime,b=u.createImportDraft({id:args.id,text:'Datum;Omschrijving;Rekening;Bedrag\n'+Array.from({length:args.count},(_,i)=>`${args.date};${i<args.matchCount?'Matched merchant':'Fix row '+i};NL01JOINT;${args.amount}`).join('\n'),profiles:state.accountProfiles,today:'2026-10-06'});for(const r of b.rows)Object.assign(r.processing,{category:'Kleding',transactionType:'uitgave',budgetOwner:'gezamenlijk',advanceMode:'none'});await u.persistImportDraft(window,b,{syncCloud:false});window.__fixDraft=await u.beginImportEditor(window,b);u.testRenderDraftModal(window,__fixDraft);document.querySelectorAll('.u4-section').forEach(d=>d.open=true);window.__fixCommits=0;const commit=window.commitChange;window.commitChange=(...args)=>{window.__fixCommits++;return commit(...args);};return b.rows.map(r=>r.id);},{count,amount,date,id,matchCount});}
for(const width of [390,1440]){
 test(`F1/F2 personal KPI, account tables, edit accessibility and no financial writes ${width}`,async({page})=>{const errors=await boot(page,width),before=await capture(page);for(const owner of ['gezamenlijk','dion','dara']){await nav(page,owner);const table=page.locator(`#tab-${owner} .u5-joint-goals-preview .goal-table`);await expect(table).toBeVisible();await expect(table.locator('thead th')).toHaveCount(10);await expect(table.locator('tfoot')).toContainText('Totaal');expect(await table.locator('..').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);if(owner!=='gezamenlijk'){const card=page.locator(`#tab-${owner} ${width<768?'[data-personal-kpi-mobile="saving"]':'.overview-kpi-row [data-kpi-id="saving"]'}`);const expected=await page.evaluate(owner=>((n)=>`${n<0?'-':''}€ ${Math.abs(n).toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})}`)(FinizeTransactions.forecast('2026-10').owners[owner].available),owner);if(await card.count())await expect(card).toContainText(expected);else await expect(page.locator(`#tab-${owner} .overview-kpi-row`)).toContainText(expected);await expect(page.locator(`#tab-${owner}`)).toContainText('Na vaste lasten, gebruikt budget en spaargeld');}await evidence(page,`fix-account-${owner}-${width}`);const edit=page.locator(`#tab-${owner} .u5-joint-goals-preview [${owner==='gezamenlijk'?'data-saving-edit':`data-personal-saving-edit="${owner}"`}]`);await expect(edit).toBeVisible();await edit.click();await expect(page.locator('#incomeEditModal')).toHaveClass(/open/);await page.locator('#incomeEditModal').getByRole('button',{name:'Annuleren',exact:true}).click();}await nav(page,'dashboard');await expect(page.locator('#tab-dashboard .dashboard-goal-preview-item:visible').first()).toBeVisible();expect(await capture(page)).toEqual(before);expect(errors).toEqual([]);});
 test(`F4/F5 type transitions, refund dropdown, automatic fixed month ${width}`,async({page})=>{const errors=await boot(page,width),ids=await batch(page);const card=page.locator(`[data-u4-row="${ids[0]}"]`),before=await page.evaluate(()=>JSON.stringify(__fixDraft.rows[0].bankOriginal));for(const family of ['sparen','uitgave','terugbetaling','sparen','terugbetaling','uitgave']){await card.locator('[data-u4-family]').selectOption(family);if(family==='sparen'){await expect(card.locator('[data-u4-field="savingsGoalId"]')).toBeVisible();await card.locator('[data-u4-field="savingsGoalId"]').selectOption('fix-goal-gezamenlijk');}else if(family==='terugbetaling'){await card.locator('[data-u4-field="refundMonth"]').fill('2026-09');await expect(card.locator('select[data-u4-field="refundCategory"]')).toBeVisible();await card.locator('[data-u4-field="refundCategory"]').selectOption('Kleding');}else await expect(card.locator('select[data-u4-field="category"]')).toBeVisible();}expect(await page.evaluate(()=>({goal:__fixDraft.rows[0].processing.savingsGoalId,refund:__fixDraft.rows[0].processing.refundMonth,commits:__fixCommits}))).toEqual({goal:'',refund:'',commits:0});await card.locator('[data-u4-field="category"]').selectOption('Vaste lasten');await card.locator('[data-u4-field="fixedExpenseId"]').selectOption('fix-mortgage');await expect(card.locator('[data-u4-field="fixedOccurrenceMonth"]')).toHaveValue('2026-09');await expect(card.locator('[data-u4-field="processingDate"]')).toHaveValue('2026-09-17');expect(await card.locator('[data-u4-field="fixedOccurrenceId"]').inputValue()).not.toBe('');await card.locator('[data-u4-field="fixedOccurrenceMonth"]').fill('2026-10');expect(await card.locator('[data-u4-field="fixedOccurrenceId"]').inputValue()).not.toBe('');expect(await page.evaluate(()=>JSON.stringify(__fixDraft.rows[0].bankOriginal))).toBe(before);expect(await page.evaluate(()=>__fixCommits)).toBe(0);await evidence(page,`fix-fixed-month-${width}`);expect(errors).toEqual([]);});
 test(`F6 local draft survives reload; group approval and next row stay usable ${width}`,async({page})=>{const errors=await boot(page,width),ids=await batch(page,{count:4,date:'2026-10-03',id:'fix-reload-'+width});await page.locator(`[data-u4-row="${ids[0]}"] [data-u4-family]`).selectOption('sparen');await page.locator(`[data-u4-row="${ids[0]}"] [data-u4-field="savingsGoalId"]`).selectOption('fix-goal-gezamenlijk');await expect.poll(()=>page.evaluate(async()=>Boolean((await FinizeUpdate4Runtime.ImportStore.getJournal('editor-draft-'+__fixDraft.id))?.draft.rows[0].processing.savingsGoalId))).toBe(true);expect(await page.evaluate(()=>__fixCommits)).toBe(0);expect(await page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(0);await page.reload();await page.waitForFunction(()=>window.__finizeBootstrap?.rendered);await page.evaluate(id=>FinizeUpdate4.openImportDetails(id),'fix-reload-'+width);await expect(page.locator(`[data-u4-row="${ids[0]}"] [data-u4-field="savingsGoalId"]`)).toHaveValue('fix-goal-gezamenlijk');for(const id of ids.slice(0,3))await page.locator(`[data-u4-select-approval="${id}"]`).check();await page.locator('[data-u4-approve-selection]').click();await expect.poll(()=>page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source'&&t.importBatchId.startsWith('fix-reload')).length)).toBe(3);await expect(page.locator('#u4ImportModalRoot')).toHaveClass(/open/);await expect(page.locator(`[data-u4-row="${ids[3]}"] [data-u4-approve]`)).toBeVisible();await page.locator(`[data-u4-row="${ids[3]}"] [data-u4-approve]`).click();if(await page.locator('[data-u4-match-only]').isVisible())await page.locator('[data-u4-match-only]').click();await expect.poll(()=>page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source'&&t.importBatchId.startsWith('fix-reload')).length)).toBe(4);expect(await page.evaluate(()=>state.savingsGoalLedger.filter(l=>l.source!=='legacy-opening'&&l.active!==false).length)).toBe(1);expect(errors).toEqual([]);});
 test(`F6 approved edit retains actual across close and applies only explicit reapproval ${width}`,async({page})=>{const errors=await boot(page,width),ids=await batch(page,{count:1,date:'2026-10-03',id:'fix-approved-'+width});await page.locator(`[data-u4-row="${ids[0]}"] [data-u4-approve]`).click();await expect.poll(()=>page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-10'}))).toBe(100);await page.locator('.u4-section-approved > summary').click();await page.locator(`[data-u4-row="${ids[0]}"] [data-u4-field="processedAmount"]`).fill('150');await page.locator(`[data-u4-row="${ids[0]}"] [data-u4-field="processedAmount"]`).press('Tab');expect(await page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-10'}))).toBe(100);await page.locator('#u4ImportModalRoot > .u4-import-modal > header [data-u4-close]').click();await expect(page.locator('#u4ImportModalRoot')).not.toHaveClass(/open/);expect(await page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-10'}))).toBe(100);await page.evaluate(id=>FinizeUpdate4.openImportDetails(id),'fix-approved-'+width);await page.locator(`[data-u4-row="${ids[0]}"] [data-u4-approve]`).click();await expect.poll(()=>page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-10'}))).toBe(150);expect(errors).toEqual([]);});
}
test('F1/F2 viewport parity uses identical goals and month result',async({page})=>{await boot(page,1440);for(const owner of ['gezamenlijk','dion','dara']){await page.setViewportSize({width:1440,height:1000});await nav(page,owner);const before=await capture(page),rows=await page.locator(`#tab-${owner} .goal-table`).innerText();await page.setViewportSize({width:390,height:1000});await expect(page.locator(`#tab-${owner} .goal-table`)).toBeVisible();expect(await page.locator(`#tab-${owner} .goal-table`).innerText()).toBe(rows);expect(await capture(page)).toEqual(before);}});

for(const width of [390,1440])test(`F6 recognition matches are proposals; one group commit and next source ${width}`,async({page})=>{
 const errors=await boot(page,width),ids=await batch(page,{count:21,date:'2026-10-03',id:'fix-recognition-'+width,matchCount:20});
 await page.locator(`[data-u4-row="${ids[0]}"] [data-u4-field="category"]`).selectOption('Overig');
 expect(await page.evaluate(()=>__fixCommits)).toBe(0);
 await page.locator(`[data-u4-row="${ids[0]}"] [data-u4-approve]`).click();
 await expect(page.locator('[data-u4-match-id]')).toHaveCount(19);
 await page.locator('[data-u4-match-apply]').click();
 await expect.poll(()=>page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source'&&t.importBatchId.startsWith('fix-recognition')).length)).toBe(1);
 expect(await page.evaluate(()=>__fixDraft.rows.slice(1,20).every(r=>r.processingStatus==='nakijken'&&r.processing.category==='Overig'))).toBe(true);
 await page.locator('.u4-section-review > summary').click();
 for(const id of ids.slice(1,20))await page.locator(`[data-u4-select-approval="${id}"]`).check();
 await page.locator('[data-u4-approve-selection]').click();
 await expect.poll(()=>page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source'&&t.importBatchId.startsWith('fix-recognition')).length)).toBe(20);
 await expect(page.locator('#u4ImportModalRoot')).toHaveClass(/open/);
 await page.locator(`[data-u4-row="${ids[20]}"] [data-u4-approve]`).click();
 await expect.poll(()=>page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source'&&t.importBatchId.startsWith('fix-recognition')).length)).toBe(21);
 expect(await page.evaluate(()=>__fixCommits)).toBe(3);expect(errors).toEqual([]);
});

test('F6 slow own hydration cannot replace a newer completed approval or block the next source',async({page})=>{
 const errors=await boot(page,1440),ids=await batch(page,{count:2,date:'2026-10-03',id:'fix-slow-hydration'});
 await page.evaluate(async()=>{
  const u=FinizeUpdate4Runtime,record=await u.ImportStore.getImport(__fixDraft.id),envelope=u.buildCloudImportEnvelope(record),cloud=CloudAdapter;
  const gate=new Promise(resolve=>window.__releaseHydration=resolve);
  cloud.db={};cloud.docRef='core';cloud.importRef=id=>'imports/'+id;cloud.importChunkRef=(id,chunk)=>'imports/'+id+'/chunks/'+chunk;
  cloud.isConnected=()=>true;cloud.queueSave=()=>{};cloud.flushQueue=async()=>false;
  cloud.modules={firestore:{doc:(_,path)=>path,getDoc:async ref=>{if(ref==='imports/'+record.id){window.__hydrationStarted=true;await gate;return {exists:()=>true,data:()=>envelope.header};}const chunk=envelope.chunks.find(c=>ref.endsWith('/'+envelope.header.generation+'-'+String(c.index).padStart(4,'0'))),sourceIndex=Number(ref.split('-source-')[1]),data=Number.isInteger(sourceIndex)&&envelope.sourceChunks[sourceIndex]!==undefined?{generation:envelope.header.generation,text:envelope.sourceChunks[sourceIndex]}:chunk;return {exists:()=>Boolean(data),data:()=>data};}}};
  window.__hydration=FinizeUpdate4.openImportDetails(record.id);
 });
 await page.waitForFunction(()=>window.__hydrationStarted);
 await page.evaluate(async id=>{await FinizeUpdate4Runtime.commitImportEditor(window,__fixDraft,{approveIds:[id]});__releaseHydration();await __hydration;},ids[0]);
 await page.locator(`[data-u4-row="${ids[1]}"] [data-u4-approve]`).click();
 await expect.poll(()=>page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source'&&t.importBatchId==='fix-slow-hydration'&&t.processingStatus==='goedgekeurd').length)).toBe(2);
 expect(await page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-10'}))).toBe(200);expect(errors).toEqual([]);
});
