const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../fixtures/v50-visual-state.json'),'utf8'));
test.setTimeout(60000);
async function boot(page,width=1440){await page.setViewportSize({width,height:900});await page.route('https://www.gstatic.com/firebasejs/**',r=>r.abort());await page.route('https://firestore.googleapis.com/**',r=>r.abort());await page.addInitScript(input=>{if(!localStorage.getItem('finize-budget-planner-v1'))localStorage.setItem('finize-budget-planner-v1',JSON.stringify(input));},fixture);await page.goto('/');await page.waitForFunction(()=>window.__finizeBootstrap?.rendered);await page.evaluate(()=>commitChange(()=>{state.meta.selectedMonth='2026-10';state.transactions=[];state.importSummaries=[];state.activeImportId='';state.manualTransactionReplacements=[];state.internalTransferPairs=[];state.savingsCoverageAllocations=[];state.advanceLedger=[];state.advanceRepayments=[];state.accountProfiles=[{id:'joint-p5',name:'Gezamenlijk',accountOwner:'gezamenlijk',identifier:'NL01JOINT'}];state.recurringFixedExpenses=[];state.budgetDefaultsHistory={gezamenlijk:[{effectiveFrom:'0000-01',rows:[{id:'p5-clothing',post:'Kleding',bedrag:500}]}],dion:[],dara:[]};state.incomeDefaultsHistory={dion:[{effectiveFrom:'0000-01',salary:3000}],dara:[{effectiveFrom:'0000-01',salary:2000}]};state.planning.spaarpotDezeMaand=250;state.spaardoelen={gezamenlijk:[{id:'p5-goal',naam:'Vakantie',algespaard:2000,doelbedrag:3000}],dion:[],dara:[]};state.savingsGoalLedger=[{id:'p5-opening',goalId:'p5-goal',effectiveAmount:2000,source:'legacy-opening',active:true}];},{render:true}));}
async function batch(page,id,lines){return page.evaluate(async({id,lines})=>{const u=FinizeUpdate4Runtime,draft=u.createImportDraft({id,text:'Datum;Omschrijving;Rekening;Bedrag\n'+lines.map(line=>(line.date||'2026-10-03')+';'+line.label+';NL01JOINT;'+line.amount).join('\n'),profiles:state.accountProfiles,existingImports:await u.ImportStore.listImports(),entryOwner:'gezamenlijk'});draft.rows.forEach((row,index)=>Object.assign(row.processing,{category:'Kleding',budgetOwner:'gezamenlijk',advanceMode:'none',transactionType:lines[index].type||'uitgave',...lines[index].processing}));await u.persistImportDraft(window,draft,{syncCloud:false});window.__p5Batch=draft;u.testRenderDraftModal(window,draft);document.querySelectorAll('.u4-section').forEach(node=>node.open=true);return {id:draft.id,rows:draft.rows.map(row=>row.id)};},{id,lines});}
async function approve(page,id){await page.locator('[data-u4-row="'+id+'"] [data-u4-approve]').click();const only=page.locator('[data-u4-match-only]');if(await only.isVisible())await only.click();await expect.poll(()=>page.evaluate(id=>state.transactions.some(tx=>tx.importTransactionId===id&&tx.processingStatus==='goedgekeurd'),id)).toBe(true);}
async function forecast(page){return page.evaluate(()=>FinizeTransactions.forecast('2026-10'));}
for(const width of [390,1440]){
 test(`P5 partial approval, withdraw/restore/delete, reload and allowance ${width}px`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await boot(page,width);const before=await forecast(page),created=await batch(page,'p5-life-'+width,[{label:'First P5',amount:-300},{label:'Still review P5',amount:-200}]);await approve(page,created.rows[0]);expect((await forecast(page)).allowanceBasis).toEqual(before.allowanceBasis);expect(await page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(1);await page.locator('[data-u4-withdraw]').click();await expect.poll(()=>page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-10'}))).toBe(0);expect((await forecast(page)).allowanceBasis).toEqual(before.allowanceBasis);await page.reload();await page.waitForFunction(()=>window.__finizeBootstrap?.rendered);await page.evaluate(id=>FinizeUpdate4.openImportDetails(id),created.id);await page.locator('[data-u4-restore]').click();await expect.poll(()=>page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-10'}))).toBe(300);expect((await forecast(page)).allowanceBasis).toEqual(before.allowanceBasis);expect(await page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(1);expect(await page.locator('[data-u4-row="'+created.rows[1]+'"] [data-u4-approve]').count()).toBe(1);await page.setViewportSize({width:width===390?1440:390,height:900});await page.locator('[data-u4-delete-batch]').click();await expect.poll(()=>page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(0);expect(await page.evaluate(id=>state.importDeletionProofs.find(row=>row.id===id),created.id)).not.toHaveProperty('rows');expect((await forecast(page)).allowanceBasis).toEqual(before.allowanceBasis);expect(errors).toEqual([]);});
 test(`P5 savings+coverage and refund batch lifecycle ${width}px`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await boot(page,width);const before=await forecast(page);const b=await batch(page,'p5-coverage-'+width,[{label:'Withdrawal P5',amount:500,type:'van-spaarrekening',processing:{savingsGoalId:'p5-goal'}},{label:'Expense P5',amount:-300}]);for(const id of b.rows)await approve(page,id);await page.evaluate(({w,x})=>commitChange(()=>{state.savingsCoverageAllocations.push({id:'p5-allocation',withdrawalTransactionId:'tx-'+w,expenseTransactionId:'tx-'+x,amountCents:20000});},{render:false}),{w:b.rows[0],x:b.rows[1]});expect(await page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-10'}))).toBe(100);expect((await forecast(page)).allowanceBasis).toEqual(before.allowanceBasis);await page.locator('[data-u4-withdraw]').click();await expect.poll(()=>page.evaluate(()=>FinizeUpdate4.calculateGoalSavedAmount('p5-goal'))).toBe(2000);await page.locator('[data-u4-restore]').click();await expect.poll(()=>page.evaluate(()=>FinizeUpdate4.calculateGoalSavedAmount('p5-goal'))).toBe(1500);expect(await page.evaluate(()=>state.savingsGoalLedger.length)).toBe(2);expect(await page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-10'}))).toBe(100);await page.evaluate(()=>document.getElementById('u4ImportModalRoot').classList.remove('open'));const rf=await batch(page,'p5-refund-'+width,[{label:'Refund P5',amount:50,type:'terugbetaling',processing:{refundCategory:'Kleding',refundMonth:'2026-10'}}]);await approve(page,rf.rows[0]);expect(await page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-10'}))).toBe(50);await page.locator('[data-u4-withdraw]').click();await expect.poll(()=>page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-10'}))).toBe(100);await page.locator('[data-u4-restore]').click();await expect.poll(()=>page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-10'}))).toBe(50);expect((await forecast(page)).allowanceBasis).toEqual(before.allowanceBasis);expect(errors).toEqual([]);});
 test(`P5 multiple open batches, source errors and exact identity ${width}px`,async({page})=>{await boot(page,width);const a=await batch(page,'p5-first-'+width,[{label:'Past P5',date:'2026-09-03',amount:-10},{label:'Future P5',date:'2099-01-01',amount:-20}]);await expect(page.locator('.u4-modal-body')).toContainText('ligt in de toekomst');expect(await page.locator('[data-u4-row="'+a.rows[1]+'"]').count()).toBe(0);const b=await batch(page,'p5-second-'+width,[{label:'Other batch P5',amount:-30}]);await approve(page,b.rows[0]);await page.evaluate(id=>FinizeUpdate4.openImportDetails(id),a.id);await page.locator('.u4-section-unknown').evaluate(node=>node.open=true);await approve(page,a.rows[0]);expect(await page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-09'}))).toBe(10);expect(await page.evaluate(()=>FinizeTransactions.total('realExpense',{month:'2026-10'}))).toBe(30);expect(await page.evaluate(()=>state.importSummaries.length)).toBe(2);const duplicate=await batch(page,'p5-identical-'+width,[{label:'Other batch P5',amount:-30}]);await expect(page.locator('.u4-modal-body')).toContainText('overgeslagen');expect(await page.locator('[data-u4-approve]').count()).toBe(0);expect(await page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(2);});
}
test('P5 real compact CloudAdapter publishes header and financial materialization atomically, B reload',async({page,browser})=>{await boot(page);await page.evaluate(async()=>{const copy=v=>JSON.parse(JSON.stringify(v)),docs=new Map(),writes=[];window.__p5Cloud={docs,writes};const cloud=CloudAdapter;cloud.db={};cloud.docRef='core';cloud.importRef=id=>'imports/'+id;cloud.importChunkRef=(id,chunk)=>'imports/'+id+'/chunks/'+chunk;cloud.modules={firestore:{doc:(_,path)=>path,serverTimestamp:()=>0,getDoc:async ref=>({exists:()=>docs.has(ref),data:()=>copy(docs.get(ref))}),setDoc:async(ref,data)=>docs.set(ref,copy(data)),updateDoc:async(ref,data)=>docs.set(ref,{...docs.get(ref),...data}),runTransaction:async(_db,fn)=>{const changes=[];const result=await fn({get:async ref=>({exists:()=>docs.has(ref),data:()=>copy(docs.get(ref))}),set:(ref,data)=>changes.push([ref,copy(data)])});changes.forEach(([ref,data])=>docs.set(ref,data));writes.push(changes.map(([ref])=>ref));return result;}}};const initial={state:copy(state),syncVersion:1,commitId:'initial'};docs.set('core',initial);await cloud.acceptRemote(initial,migrateBudgetState(initial.state),null);});const b=await batch(page,'p5-cloud',[{label:'Cloud P5',amount:-300}]);await approve(page,b.rows[0]);await page.evaluate(()=>FinizeUpdate4Runtime.flushImportSync(window));await expect.poll(()=>page.evaluate(async()=>(await CloudAdapter.cloudStore().hydrate(__p5Cloud.docs.get('core'))).state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(1);const shared=await page.evaluate(async()=>({data:await CloudAdapter.cloudStore().hydrate(__p5Cloud.docs.get('core')),header:__p5Cloud.docs.get('imports/p5-cloud'),writes:__p5Cloud.writes,forecast:FinizeTransactions.forecast('2026-10')}));expect(shared.writes.some(refs=>refs.includes('core')&&refs.includes('imports/p5-cloud'))).toBe(true);expect(shared.header.operationId).toBe(shared.data.state.importSummaries.find(row=>row.id==='p5-cloud').operationId);const context=await browser.newContext({serviceWorkers:'block'}),second=await context.newPage();await second.route('https://www.gstatic.com/firebasejs/**',r=>r.abort());await second.route('https://firestore.googleapis.com/**',r=>r.abort());await second.addInitScript(data=>localStorage.setItem('finize-budget-planner-v1',JSON.stringify(data.state)),shared.data);await second.goto('/');await second.waitForFunction(()=>window.__finizeBootstrap?.rendered);expect(await second.evaluate(()=>FinizeTransactions.forecast('2026-10'))).toEqual(shared.forecast);await context.close();});


test('P5 two isolated devices approve different sources and roundtrip durable processing',async({page,browser})=>{
 const documents=new Map(),copy=v=>JSON.parse(JSON.stringify(v));
 async function attach(target){
  await target.exposeFunction('p5Read',ref=>documents.has(ref)?copy(documents.get(ref)):null);
  await target.exposeFunction('p5Write',(ref,value)=>documents.set(ref,copy(value))&&true);
  await target.exposeFunction('p5Commit',(changes,versions)=>{for(const [ref,version]of versions){if((documents.get(ref)?.syncVersion??documents.get(ref)?.version??null)!==version)throw new Error('Test transaction contention');}for(const [ref,value]of changes)documents.set(ref,copy(value));return true;});
  await target.evaluate(async()=>{const cloud=CloudAdapter;cloud.db={};cloud.docRef='core';cloud.importRef=id=>'imports/'+id;cloud.importChunkRef=(id,chunk)=>'imports/'+id+'/chunks/'+chunk;cloud.modules={firestore:{doc:(_,path)=>path,serverTimestamp:()=>0,getDoc:async ref=>{const value=await p5Read(ref);return {exists:()=>value!==null,data:()=>value};},setDoc:(ref,value)=>p5Write(ref,value),updateDoc:async(ref,value)=>p5Write(ref,{...await p5Read(ref),...value}),runTransaction:async(_db,fn)=>{const changes=[],versions=[];const result=await fn({get:async ref=>{const value=await p5Read(ref);versions.push([ref,value?.syncVersion??value?.version??null]);return {exists:()=>value!==null,data:()=>value};},set:(ref,value)=>changes.push([ref,value])});await p5Commit(changes,versions);return result;}}};const initial=await cloud.cloudStore().hydrate(await p5Read('core'));await cloud.acceptRemote(initial,migrateBudgetState(initial.state),null);});
 }
 await boot(page);documents.set('core',await page.evaluate(()=>({state:JSON.parse(JSON.stringify(state)),syncVersion:1,commitId:'initial'})));await attach(page);
 const b=await batch(page,'p5-roundtrip',[{label:'Device A purchase',amount:-100},{label:'Device B purchase',amount:-200}]);await approve(page,b.rows[0]);
 await expect.poll(()=>page.evaluate(async()=>(await CloudAdapter.cloudStore().hydrate(await p5Read('core'))).state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(1);
 const context=await browser.newContext({serviceWorkers:'block'}),second=await context.newPage();await boot(second,390);await attach(second);await second.evaluate(id=>FinizeUpdate4.openImportDetails(id),b.id);await second.locator('.u4-section-unknown').evaluate(node=>node.open=true);await approve(second,b.rows[1]);
 await expect.poll(()=>page.evaluate(async()=>(await CloudAdapter.cloudStore().hydrate(await p5Read('core'))).state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(2);
 await page.evaluate(async()=>{const latest=await CloudAdapter.cloudStore().hydrate(await p5Read('core'));await CloudAdapter.acceptRemote(latest,migrateBudgetState(latest.state),null);});
 expect(await forecast(page)).toEqual(await forecast(second));
 const details=await page.evaluate(id=>FinizeUpdate4Runtime.fetchImportFromCloud(window,id),b.id);expect(details.rows.every(row=>row.certainty==='goedgekeurd')).toBe(true);expect(details.baseVersion).toBe(details.version);expect(details.rows.map(row=>row.bankOriginal.amount)).toEqual([-100,-200]);
 await second.reload();await second.waitForFunction(()=>window.__finizeBootstrap?.rendered);expect(await second.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(2);await context.close();
});
test('P5 actual IndexedDB store isolates households without mixing identical batch IDs',async({page})=>{await boot(page);const result=await page.evaluate(async()=>{const store=FinizeUpdate4Runtime.ImportStore;store.setScope('isolated-p5-A');await store.putImport({id:'same-id',version:1,operationId:'A',rows:[]});store.setScope('isolated-p5-B');const other=await store.getImport('same-id');await store.putImport({id:'same-id',version:1,operationId:'B',rows:[]});store.setScope('isolated-p5-A');const own=await store.getImport('same-id');await store.putImport({id:'same-id',version:2,operationId:'newer-A',rows:[]});let blocked=false;try{await store.rollbackImport(own,null,null);}catch(error){blocked=error.code==='import-conflict';}const retained=await store.getImport('same-id');await store.rollbackImport(retained,own,null);return {other:other||null,own:own.operationId,blocked,retained:retained.operationId,rolledBack:(await store.getImport('same-id')).operationId};});expect(result).toEqual({other:null,own:'A',blocked:true,retained:'newer-A',rolledBack:'A'});});
