const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../fixtures/v50-visual-state.json'),'utf8'));
test.setTimeout(90_000);test.use({actionTimeout:5000});
async function boot(page,width){
 await page.setViewportSize({width,height:900});await page.route('https://www.gstatic.com/firebasejs/**',r=>r.abort());await page.route('https://firestore.googleapis.com/**',r=>r.abort());
 await page.addInitScript(s=>{if(!localStorage.getItem('finize-budget-planner-v1'))localStorage.setItem('finize-budget-planner-v1',JSON.stringify(s));},fixture);
 await page.goto('/');await page.waitForFunction(()=>window.__finizeBootstrap?.rendered);
 await page.evaluate(()=>commitChange(()=>{state.meta.selectedMonth='2026-10';state.transactions=[];state.recurringFixedExpenses=[];state.importSummaries=[];state.activeImportId='';state.accountProfiles=['dion','dara','gezamenlijk'].map(owner=>({id:owner,accountOwner:owner,name:owner}));state.spaardoelen={dion:[],dara:[],gezamenlijk:[{id:'p4-goal',naam:'Vakantie P4',algespaard:1000,doelbedrag:4000,doeldatum:'2028-12-31',subdoelen:[]}]};state.savingsGoalLedger=[{id:'p4-opening',goalId:'p4-goal',month:'2026-10',source:'manual-correction',effectiveAmount:1000,active:true,status:'uitgevoerd'}];state.savingsCoverageAllocations=[];state.manualTransactionReplacements=[];state.internalTransferPairs=[];state.monthRecords={};},{render:false}));
}
function errors(page){const result=[];page.on('pageerror',e=>result.push(e.message));page.on('console',m=>{if(m.type()==='error')result.push(m.text());});return result;}
async function manual(page,type,amount,label,owner='gezamenlijk',fields={}){
 await page.evaluate(owner=>document.querySelector('#tabs [data-tab="'+owner+'"]').click(),owner);await page.locator('#tab-'+owner+(owner==='gezamenlijk'?' [data-open-joint-transaction]':' [data-open-personal-transaction]')).first().click();await page.locator('#transactionModal').getByRole('button',{name:/Handmatig invoeren/}).click();const prefix=owner==='gezamenlijk'?'jointTx':'personalTx',suffix=owner==='gezamenlijk'?'JointTransaction':'PersonalTransaction';
 await page.locator('#'+prefix+'Type').selectOption(type);await page.locator('#'+prefix+'Amount').fill(String(amount));await page.locator('#'+prefix+'Date').fill(fields.date||'2026-10-03');await page.locator('#'+prefix+'Description').fill(label);
 if(['sparen','naar-spaarrekening','van-spaarrekening'].includes(type))await page.locator('#'+prefix+'Goal').selectOption('p4-goal');
 if(type==='terugbetaling'){await page.locator('#'+prefix+'RefundCategory').fill(fields.refundCategory);await page.locator('#'+prefix+'RefundMonth').fill(fields.refundMonth);}
 else if(type==='uitgave')await page.locator('#'+prefix+'Category').selectOption({label:fields.category||'Overig'});
 await page.locator('#btnSave'+suffix).click();await expect(page.locator('#transactionModal')).not.toHaveClass(/open/);return page.evaluate(label=>state.transactions.find(tx=>tx.description===label).id,label);
}
async function allocate(page,withdrawal,expense,amount){await page.evaluate(id=>FinizeTransactions.openCoverage(id),expense);await page.locator('[data-p4-withdrawal]').selectOption(withdrawal);await page.locator('[data-p4-expense]').selectOption(expense);await page.locator('[data-p4-amount]').fill(String(amount));await page.locator('[data-p4-save]').click();await expect(page.locator('[data-p4-error]')).toBeEmpty();await page.locator('[data-p4-close]').click();}
async function csv(page,id,lines){await page.evaluate(async({id,lines})=>{const u=FinizeUpdate4Runtime;window.__p4Draft={id,fileName:id+'.csv',status:'concept',entryOwner:'gezamenlijk',accountOwner:'gezamenlijk',accountProfileId:'gezamenlijk',rows:lines.map((line,index)=>({id:id+'-'+index,accountOwner:'gezamenlijk',source:'csv',certainty:line.unknown?'onbekend':'nakijken',recognitionState:line.unknown?'unknown':'known',duplicate:false,bankOriginal:{valid:true,bankDate:line.date||'2026-10-03',amount:line.amount,description:line.label,rawDescription:line.label,rawCells:['unchanged',line.amount],fingerprint:id+'-'+index,lineNumber:index+2},processing:{processingDate:line.date||'2026-10-03',processedAmount:Math.abs(line.amount),description:line.label,transactionType:line.type||'uitgave',category:line.category||'Overig',budgetOwner:'gezamenlijk',advanceMode:'none',fixedAmountMode:'none',include:true,splits:[],...line.processing}})),summary:{}};u.updateDraftSummary(__p4Draft);commitChange(()=>{state.activeImportId=id;state.importSummaries.push(u.compactSummary(__p4Draft));},{render:false});await u.ImportStore.putImport(__p4Draft);u.testRenderDraftModal(window,__p4Draft);document.querySelectorAll('.u4-section').forEach(node=>node.open=true);},{id,lines});}
async function sections(page){await page.evaluate(()=>document.querySelectorAll('.u4-section').forEach(node=>node.open=true));}
async function approve(page,id){await sections(page);await page.locator(`[data-u4-row="${id}"] [data-u4-approve]`).click();await expect.poll(()=>page.evaluate(id=>state.transactions.some(tx=>tx.importTransactionId===id&&tx.processingStatus==='goedgekeurd'),id)).toBe(true);}
async function process(page){await page.locator('[data-u4-process]').click();await expect.poll(()=>page.evaluate(()=>__p4Draft.rows.every(row=>['goedgekeurd','niet-meetellen'].includes(row.certainty)))).toBe(true);await page.locator('[data-u4-close]').click();}
const value=(page,id)=>page.evaluate(id=>FinizeTransactions.project(state.transactions.find(t=>t.id===id)),id);
for(const width of [390,1440]){
 test(`P4 manual many-to-many, coverage edit/remove, correction and reload ${width}px`,async({page})=>{
  const failures=errors(page);await boot(page,width);const baseline=await page.evaluate(()=>FinizeTransactions.forecast('2026-10').household.available);
  for(const tab of ['dashboard','gezamenlijk','dion','dara','spaardoelen']){await page.evaluate(tab=>{document.querySelector('#tabs [data-tab="'+tab+'"]').click();},tab);await expect(page.locator('#tab-'+tab)).not.toBeEmpty();}
  const deposit=await manual(page,'naar-spaarrekening',250,'Deposit P4');expect((await value(page,deposit)).effects).toMatchObject({accountCashflow:-250,goalDelta:250,realExpense:0,budgetImpact:0});expect(await page.evaluate(()=>FinizeTransactions.forecast('2026-10').household.available)).toBe(baseline-250);
  const w=await manual(page,'van-spaarrekening',500,'Withdrawal P4'),e=await manual(page,'uitgave',300,'Hotel P4'),e2=await manual(page,'uitgave',100,'Restaurant P4');
  await allocate(page,w,e,200);await allocate(page,w,e2,100);const w2=await manual(page,'van-spaarrekening',100,'Withdrawal second P4');await allocate(page,w2,e,100);
  expect((await value(page,e)).effects).toMatchObject({realExpense:300,savingsFunded:300,budgetImpact:0});expect((await value(page,w)).effects.unusedSavings).toBe(200);
  await page.evaluate(id=>FinizeTransactions.openCoverage(id),e);const id=await page.evaluate(w=>state.savingsCoverageAllocations.find(a=>a.withdrawalTransactionId===w&&a.amountCents===20000).id,w);await page.locator(`[data-p4-edit="${id}"]`).click();await page.locator('[data-p4-amount]').fill('150');await page.locator('[data-p4-save]').click();expect((await value(page,e)).effects.budgetImpact).toBe(50);await page.locator(`[data-p4-remove="${id}"]`).click();expect((await value(page,e)).effects.budgetImpact).toBe(200);expect((await value(page,w)).effects.unusedSavings).toBe(400);await page.locator('[data-p4-close]').click();
  const beforeCorrection=await page.evaluate(()=>({count:state.transactions.filter(t=>t.recordRole!=='bank-source').length,available:FinizeTransactions.forecast('2026-10').household.available}));await page.evaluate(()=>document.querySelector('#tabs [data-tab="spaardoelen"]').click());await page.locator('[data-open-goal-editor="gezamenlijk:p4-goal"]').first().click();await page.locator('#goalEditSaved').fill('750');await page.locator('#goalEditSave').click();expect(await page.evaluate(()=>state.spaardoelen.gezamenlijk[0].algespaard)).toBe(750);expect(await page.evaluate(()=>({count:state.transactions.filter(t=>t.recordRole!=='bank-source').length,available:FinizeTransactions.forecast('2026-10').household.available}))).toEqual(beforeCorrection);
  const saved=await page.evaluate(()=>({tx:state.transactions,ledger:state.savingsGoalLedger,alloc:state.savingsCoverageAllocations,planning:state.planning,closures:state.monthRecords,revision:state.meta.revision}));await page.setViewportSize({width:width===390?1440:390,height:900});await page.evaluate(()=>{state.meta.selectedMonth='2026-09';renderActiveTab();});expect(await page.evaluate(()=>FinizeTransactions.total('savingsDeposit',{month:'2026-09'}))).toBe(0);await page.reload();await page.waitForFunction(()=>window.__finizeBootstrap?.rendered);expect(await page.evaluate(()=>({tx:state.transactions,ledger:state.savingsGoalLedger,alloc:state.savingsCoverageAllocations,planning:state.planning,closures:state.monthRecords,revision:state.meta.revision}))).toEqual(saved);expect(failures).toEqual([]);
 });
 test(`P4 CSV savings source reopen/exclusion/reapproval with retained coverage ${width}px`,async({page})=>{
  const failures=errors(page);await boot(page,width);await csv(page,'p4-csv',[{amount:500,label:'CSV savings P4',type:'van-spaarrekening',category:'Sparen',processing:{savingsGoalId:'p4-goal'}},{amount:-300,label:'CSV expense P4',unknown:true}]);
  expect(await page.evaluate(()=>FinizeTransactions.total('incomeImpact'))).toBe(0);expect(await page.evaluate(()=>state.transactions.filter(t=>t.recordRole!=='bank-source').length)).toBe(0);for(const id of ['p4-csv-0','p4-csv-1'])await approve(page,id);await process(page);
  const w='tx-p4-csv-0',e='tx-p4-csv-1';await allocate(page,w,e,200);const originals=await page.evaluate(()=>state.transactions.map(t=>t.bankOriginal));
  await page.evaluate(()=>FinizeUpdate4Runtime.testRenderDraftModal(window,__p4Draft));await sections(page);await page.locator('[data-u4-row="p4-csv-0"] [data-u4-reopen]').click();await expect.poll(()=>value(page,e).then(p=>p.effects.budgetImpact)).toBe(100);expect(await page.evaluate(()=>state.spaardoelen.gezamenlijk[0].algespaard)).toBe(500);await approve(page,'p4-csv-0');expect((await value(page,e)).effects.budgetImpact).toBe(100);expect(await page.evaluate(()=>state.savingsGoalLedger.length)).toBe(2);
  await sections(page);await page.locator('[data-u4-row="p4-csv-1"] [data-u4-reopen]').click();await expect.poll(()=>value(page,w).then(p=>p.effects.unusedSavings)).toBe(300);await approve(page,'p4-csv-1');expect((await value(page,w)).effects.unusedSavings).toBe(300);
  await sections(page);await page.locator('[data-u4-row="p4-csv-0"] [data-u4-family]').selectOption('niet-meetellen');await sections(page);await page.locator('[data-u4-row="p4-csv-0"] [data-u4-approve]').click();await expect.poll(()=>page.evaluate(()=>FinizeTransactions.total('goalDelta'))).toBe(0);expect((await value(page,e)).effects.budgetImpact).toBe(300);expect(await page.evaluate(()=>state.savingsGoalLedger.length)).toBe(2);expect(await page.evaluate(()=>state.transactions.map(t=>t.bankOriginal))).toEqual(originals);expect(failures).toEqual([]);
 });
 test(`P4 split coverage and historical split refund with undo ${width}px`,async({page})=>{
  const failures=errors(page);await boot(page,width);await csv(page,'p4-split',[{amount:-300,label:'Split expense P4',processing:{splits:[{id:'k',amount:100,category:'Kleding',budgetOwner:'gezamenlijk',transactionType:'uitgave'},{id:'o',amount:200,category:'Overig',budgetOwner:'gezamenlijk',transactionType:'uitgave'}]}},{amount:500,label:'Split withdrawal P4',type:'van-spaarrekening',category:'Sparen',processing:{savingsGoalId:'p4-goal'}}]);for(const id of ['p4-split-0','p4-split-1'])await approve(page,id);await process(page);await allocate(page,'tx-p4-split-1','p4-split-0-split-k',60);expect((await value(page,'p4-split-0-split-o')).effects.budgetImpact).toBe(200);
  await csv(page,'p4-refund',[{amount:50,label:'Split refund P4',date:'2026-11-03',type:'terugbetaling',category:'Terugbetaling',processing:{refundCategory:'Kleding',refundMonth:'2026-10',splits:[{id:'rk',amount:30,category:'Terugbetaling',budgetOwner:'gezamenlijk',transactionType:'terugbetaling',refundCategory:'Kleding',refundMonth:'2026-10'},{id:'ro',amount:20,category:'Terugbetaling',budgetOwner:'gezamenlijk',transactionType:'terugbetaling',refundCategory:'Overig',refundMonth:'2026-10'}]}}]);await page.locator('[data-u4-row="p4-refund-0"] details').first().evaluate(node=>node.open=true);for(const index of [0,1]){const split=page.locator('[data-u4-row="p4-refund-0"] [data-u4-split="'+index+'"]');await split.locator('[data-u4-split-field="refundMonth"]').fill('2026-10');await split.locator('[data-u4-split-field="refundCategory"]').selectOption(index===0?'Kleding':'Overig');await split.locator('[data-u4-split-field="refundCategory"]').blur();}await approve(page,'p4-refund-0');await process(page);
  expect(await page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-10'}))).toBe(190);expect(await page.evaluate(()=>({cash:FinizeTransactions.total('accountCashflow',{month:'2026-11'}),income:FinizeTransactions.income('2026-11').amount,real:FinizeTransactions.total('realExpense',{month:'2026-10'})}))).toEqual({cash:50,income:0,real:300});
  await page.evaluate(()=>FinizeUpdate4Runtime.testRenderDraftModal(window,__p4Draft));await sections(page);await page.locator('[data-u4-row="p4-refund-0"] [data-u4-reopen]').click();await expect.poll(()=>page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-10'}))).toBe(190);await approve(page,'p4-refund-0');expect(await page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-10'}))).toBe(190);expect(failures).toEqual([]);
 });
 test(`P4 manual refund historical month and validation before writes ${width}px`,async({page})=>{
  const failures=errors(page);await boot(page,width);const e=await manual(page,'uitgave',100,'Historical clothing P4','gezamenlijk',{category:'Overig',date:'2026-09-03'}),original=await value(page,e);
  const refund=await manual(page,'terugbetaling',30,'Refund previous P4','gezamenlijk',{refundCategory:'Overig',refundMonth:'2026-09'});expect(await page.evaluate(()=>FinizeTransactions.total('budgetImpact',{month:'2026-09'}))).toBe(70);expect(await value(page,e)).toEqual(original);expect((await value(page,refund)).effects).toMatchObject({accountCashflow:30,refundCorrection:30,incomeImpact:0});
  const before=await page.evaluate(()=>JSON.stringify(state));await page.locator('#tab-gezamenlijk [data-open-joint-transaction]').first().click();await page.locator('#transactionModal').getByRole('button',{name:/Handmatig invoeren/}).click();await page.locator('#jointTxType').selectOption('van-spaarrekening');await page.locator('#jointTxAmount').fill('5000');await page.locator('#jointTxGoal').selectOption('p4-goal');await page.locator('#btnSaveJointTransaction').click();await expect(page.locator('[data-p4-error]')).toContainText('negatief');expect(await page.evaluate(()=>JSON.stringify(state))).toBe(before);await page.locator('#btnCloseJointTransaction').click();
  const p=await manual(page,'sparen',10,'Dion saving P4','dion');expect((await value(page,p))).toMatchObject({accountContext:'dion',financialFor:'dion'});const d=await manual(page,'sparen',15,'Dara saving P4','dara');expect((await value(page,d))).toMatchObject({accountContext:'dara',financialFor:'dara'});expect(failures).toEqual([]);
 });
}

test('P4 cloudmock A/B preserves optional allocations and ledger with no migration echo',async({page,browser})=>{
 const failures=errors(page);await boot(page,1440);const w=await manual(page,'van-spaarrekening',300,'Cloud withdrawal P4'),e=await manual(page,'uitgave',200,'Cloud expense P4');await allocate(page,w,e,150);
 const shared=await page.evaluate(async()=>{const copy=v=>JSON.parse(JSON.stringify(v)),cloud=CloudAdapter;let data={syncVersion:3,commitId:'base',state:copy(state)},writes=0;cloud.db={};cloud.docRef={};cloud.baseState=copy(state);cloud.lastSyncVersion=3;cloud.hasRemoteSnapshot=true;cloud.modules={firestore:{serverTimestamp:()=>0,runTransaction:async(_,fn)=>fn({get:async()=>({exists:()=>true,data:()=>data}),set:(_,payload)=>{writes++;data=copy(payload);}})}};await cloud.acceptRemote(data,migrateBudgetState(data.state),null);while(cloud.writeInFlight||cloud.pendingState)await new Promise(r=>setTimeout(r,10));return {data,writes,forecast:FinizeTransactions.forecast('2026-10'),protected:{ledger:state.savingsGoalLedger,allocations:state.savingsCoverageAllocations,transactions:state.transactions}};});
 const context=await browser.newContext({serviceWorkers:'block'}),second=await context.newPage();await second.route('https://www.gstatic.com/firebasejs/**',r=>r.abort());await second.route('https://firestore.googleapis.com/**',r=>r.abort());await second.addInitScript(input=>localStorage.setItem('finize-budget-planner-v1',JSON.stringify(input)),shared.data.state);await second.goto('/');await second.waitForFunction(()=>window.__finizeBootstrap?.rendered);
 const deviceB=await second.evaluate(async data=>{const cloud=CloudAdapter;let writes=0;cloud.db={};cloud.docRef={};cloud.modules={firestore:{runTransaction:async()=>{writes++;throw new Error('Unexpected migration write');}}};await cloud.acceptRemote(data,migrateBudgetState(data.state),null);await cloud.acceptRemote(data,migrateBudgetState(data.state),null);return {writes,forecast:FinizeTransactions.forecast('2026-10'),protected:{ledger:state.savingsGoalLedger,allocations:state.savingsCoverageAllocations,transactions:state.transactions}};},shared.data);expect(deviceB.writes).toBe(0);expect(deviceB.forecast).toEqual(shared.forecast);expect(deviceB.protected).toEqual(shared.protected);expect(failures).toEqual([]);await context.close();
});

for(const width of [390,1440])test(`P4 mixed fixed/variable refund is an explicit category correction ${width}px`,async({page})=>{
 const failures=errors(page);await boot(page,width);
 await page.evaluate(()=>commitChange(()=>{state.transactions.push({id:'mixed-fixed',source:'manual',accountContext:'gezamenlijk',financialFor:'gezamenlijk',budgetOwner:'gezamenlijk',owner:'gezamenlijk',date:'2026-10-03',amount:100,transactionType:'vaste-last',category:'Boodschappen',processingStatus:'goedgekeurd',fixedExpenseId:'mixed-gym',fixedOccurrenceId:'mixed-gym:2026-10-01',fixedOccurrenceMonth:'2026-10'});},{render:false}));
 await manual(page,'uitgave',40,'Mixed ordinary P4','gezamenlijk',{category:'Boodschappen'});const id=await manual(page,'terugbetaling',30,'Mixed refund P4','gezamenlijk',{refundCategory:'Boodschappen',refundMonth:'2026-10'});
 expect((await value(page,id)).effects).toMatchObject({refundCorrection:30,categoryOnlyRefundCorrection:30,budgetImpact:0,incomeImpact:0,accountCashflow:30});
 expect(await page.evaluate(()=>FinizeTransactions.total('budgetImpact',{owner:'gezamenlijk',month:'2026-10'}))).toBe(40);const row=await page.evaluate(()=>FinizeUpdate3.budgetSummary('gezamenlijk','2026-10').find(row=>row.category==='Boodschappen'));expect(row).toMatchObject({actual:110,categoryOnlyRefundCorrection:30});
 await page.locator('#tab-gezamenlijk [data-open-budget-transactions]').filter({hasText:/Bood/i}).first().click();await expect(page.locator('.budget-transactions-list')).toContainText('aparte categoriecorrectie');expect(failures).toEqual([]);
});
