const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../fixtures/v50-visual-state.json'),'utf8'));
for(const width of [390,1440])test(`P4 correction planned allowance stable before/after actuals ${width}px`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.setViewportSize({width,height:900});await page.route('https://www.gstatic.com/firebasejs/**',r=>r.abort());await page.route('https://firestore.googleapis.com/**',r=>r.abort());
 await page.addInitScript(s=>{if(!localStorage.getItem('finize-budget-planner-v1'))localStorage.setItem('finize-budget-planner-v1',JSON.stringify(s));},fixture);await page.goto('/');await page.waitForFunction(()=>window.__finizeBootstrap?.rendered);
 await page.evaluate(()=>commitChange(()=>{state.meta.selectedMonth='2026-10';state.transactions=[];state.recurringFixedExpenses=[];state.recurringIncomeSources=[];state.planning.spaarpotDezeMaand=250;state.monthlySavingOverrides={};state.monthlyIncomeOverrides={};state.budgetDefaultsHistory={gezamenlijk:[{id:'correction-budget',effectiveFrom:'0000-01',rows:[{id:'food',post:'Boodschappen',bedrag:500}]}],dion:[],dara:[]};state.monthlyBudgets={};state.incomeDefaultsHistory={dion:[{id:'dion-salary',effectiveFrom:'0000-01',salary:3000,refund:0}],dara:[{id:'dara-salary',effectiveFrom:'0000-01',salary:2000,refund:0}]};state.monthRecords={};state.manualTransactionReplacements=[];state.internalTransferPairs=[];state.spaardoelen={gezamenlijk:[{id:'goal-correction',naam:'Buffer',algespaard:1000,doelbedrag:2000}],dion:[],dara:[]};state.savingsGoalLedger=[{id:'opening-correction',goalId:'goal-correction',source:'legacy-opening',effectiveAmount:1000,active:true}];},{render:false}));
 await page.evaluate(()=>document.querySelector('#tabs [data-tab="dashboard"]').click());const before=await page.evaluate(()=>FinizeTransactions.forecast('2026-10'));
 expect(before.allowanceBasis.owners.gezamenlijk).toMatchObject({budgetReserve:500,savingsReserve:250,totalReserve:750});expect(before.owners.dion.allowance).toBe(2550);expect(before.owners.dara.allowance).toBe(1700);await expect(page.locator('.allowance-return-card, .u5-allowance-split').filter({visible:true}).first()).toContainText('2.550');
 await page.evaluate(()=>document.querySelector('#tabs [data-tab="gezamenlijk"]').click());await page.locator('#tab-gezamenlijk [data-open-joint-transaction]').first().click();await page.locator('#transactionModal').getByRole('button',{name:/Handmatig invoeren/}).click();await page.locator('#jointTxAmount').fill('300');await page.locator('#jointTxDate').fill('2026-10-05');await page.locator('#jointTxDescription').fill('Partial planned groceries');await page.locator('#jointTxCategory').selectOption({label:'Boodschappen'});await page.locator('#btnSaveJointTransaction').click();
 await expect(page.locator('#transactionModal')).not.toHaveClass(/open/);await page.evaluate(()=>document.querySelector('#tabs [data-tab="dashboard"]').click());const after=await page.evaluate(()=>FinizeTransactions.forecast('2026-10'));
 expect(after.allowanceBasis).toEqual(before.allowanceBasis);expect(after.owners.dion.allowance).toBe(before.owners.dion.allowance);expect(after.owners.dara.allowance).toBe(before.owners.dara.allowance);expect(after.owners.gezamenlijk.available).toBe(450);expect(after.household.realExpense).toBe(300);await expect(page.locator('.allowance-return-card, .u5-allowance-split').filter({visible:true}).first()).toContainText('2.550');
 await page.evaluate(()=>commitChange(()=>{state.recurringFixedExpenses.push({id:'fixed-correction',naam:'Planning100',categorie:'Wonen',bedrag:100,financialFor:'gezamenlijk',rekening:'gezamenlijk',begindatum:'2026-10-01',actief:true,frequentieAantal:1,frequentieEenheid:'maanden',amountHistory:[{effectiveFrom:'2026-10-01',amount:100}],monthOverrides:{}});},{render:false}));const fixedPlan=await page.evaluate(()=>FinizeTransactions.forecast('2026-10'));expect(fixedPlan.allowanceBasis.owners.gezamenlijk.fixedReserve).toBe(100);await page.evaluate(()=>commitChange(()=>{state.transactions.push({id:'actual-fixed-correction',source:'manual',accountContext:'gezamenlijk',financialFor:'gezamenlijk',budgetOwner:'gezamenlijk',owner:'gezamenlijk',date:'2026-10-05',amount:105,transactionType:'vaste-last',category:'Wonen',processingStatus:'goedgekeurd',fixedExpenseId:'fixed-correction',fixedOccurrenceId:'fixed-correction:2026-10-01',fixedOccurrenceMonth:'2026-10'});},{render:false}));await page.evaluate(()=>document.querySelector('#tabs [data-tab="dashboard"]').click());const realizedFixed=await page.evaluate(()=>FinizeTransactions.forecast('2026-10'));expect(realizedFixed.allowanceBasis).toEqual(fixedPlan.allowanceBasis);expect(realizedFixed.owners.gezamenlijk.fixedBurden).toBe(105);expect(realizedFixed.owners.dion.allowance).toBe(fixedPlan.owners.dion.allowance);if(width===1440)await expect(page.locator('.u5-planned-flow .u5-flow-list > div').filter({hasText:'Vaste gezamenlijke lasten'})).toContainText('100,00');
 const protectedData=await page.evaluate(()=>({transactions:state.transactions,ledger:state.savingsGoalLedger,planning:state.planning,revision:state.meta.revision}));await page.setViewportSize({width:width===390?1440:390,height:900});await page.reload();await page.waitForFunction(()=>window.__finizeBootstrap?.rendered);expect(await page.evaluate(()=>({transactions:state.transactions,ledger:state.savingsGoalLedger,planning:state.planning,revision:state.meta.revision}))).toEqual(protectedData);expect(await page.evaluate(()=>FinizeTransactions.forecast('2026-10').allowanceBasis)).toEqual(fixedPlan.allowanceBasis);expect(errors).toEqual([]);
});
