const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const u=require('../src/import/update4-runtime.cjs'),sync=require('../src/import/import-sync-protocol.mjs'),e=require('../src/core/transaction-engine.mjs');
const {state,row,materialize,memory,copy}=require('./helpers/package5-fixture.cjs');
function cloud(){const documents=new Map(),writes=[];const snapshot=ref=>({exists:()=>documents.has(ref),data:()=>copy(documents.get(ref))});const f={doc:(_db,...parts)=>parts.join('/'),setDoc:async(ref,data)=>{documents.set(ref,copy(data));writes.push(ref);},getDoc:async ref=>snapshot(ref),runTransaction:async(_db,fn)=>{const pending=[];const result=await fn({get:async ref=>snapshot(ref),set:(ref,data)=>pending.push([ref,copy(data)])});for(const [ref,data]of pending){documents.set(ref,data);writes.push(ref);}return result;}};return {documents,writes,f,adapter:{isConnected:()=>true,db:{},modules:{firestore:f}}};}
async function publish(root){const staged=await u.stageImportCloudWrites(root,root.state);await root.CloudAdapter.modules.firestore.runTransaction({},async tx=>{await staged.readAndValidate(tx);staged.publish(tx);tx.set('core',copy(root.state));});await staged.acknowledge();}
async function setup(){const mem=memory(),s=state(),batch=materialize(s,[row('expense')]);batch.baseVersion=0;mem.imports.set(batch.id,copy(batch));await u.queueImportSync(batch);const remote=cloud(),root={state:s,CloudAdapter:remote.adapter};return {mem,s,batch,remote,root};}
test('SY1 device A to B full batch and financial snapshot share commit',async()=>{const x=await setup();try{await publish(x.root);const b=await u.fetchImportFromCloud(x.root,x.batch.id);assert.deepEqual(b.rows,x.batch.rows);assert.equal(b.baseVersion,b.version);assert.equal(x.remote.documents.get('core').transactions[0].importBatchId,b.id);}finally{x.mem.restore();}});
test('SY2 B approval roundtrip back to A preserves source choices',async()=>{const x=await setup();try{await publish(x.root);const b=await u.fetchImportFromCloud(x.root,x.batch.id);b.rows[0].processing.category='Other';b.version=2;b.baseVersion=1;b.operationId='B-choice';x.mem.imports.set(b.id,copy(b));Object.assign(x.s.importSummaries[0],{version:2,operationId:b.operationId});await u.queueImportSync(b);await publish(x.root);const a=await u.fetchImportFromCloud(x.root,b.id);assert.equal(a.rows[0].processing.category,'Other');assert.equal(a.version,2);}finally{x.mem.restore();}});
test('SY3 stale header commit rejects before core/header overwrite',async()=>{const x=await setup();try{await publish(x.root);const before=copy(x.remote.documents.get('core'));const stale=copy(x.batch);stale.version=2;stale.operationId='stale';stale.baseVersion=0;x.mem.imports.set(stale.id,stale);Object.assign(x.s.importSummaries[0],{version:2,operationId:'stale'});await u.queueImportSync(stale);await assert.rejects(publish(x.root),e=>e.code==='import-conflict');assert.deepEqual(x.remote.documents.get('core'),before);}finally{x.mem.restore();}});
test('SY4 listener/commit echo is idempotent',()=>{const r={id:'batch',version:2,operationId:'op',baseVersion:1};assert.equal(sync.assertImportBase(r,r),'echo');assert.equal(sync.acknowledgeMatches(sync.pendingQueueReceipt(r),sync.pendingQueueReceipt(r)),true);});
for(const[id,status]of Object.entries({SY5:'nakijken',SY6:'goedgekeurd',SY7:'withdrawn',SY8:'active'}))test(id+' reload retains review/lifecycle',async()=>{const x=await setup();try{x.batch.lifecycle=['withdrawn','active'].includes(status)?status:'active';if(['nakijken','goedgekeurd'].includes(status)){x.batch.rows[0].certainty=status;x.batch.rows[0].processingStatus=status;if(status==='nakijken')x.batch.rows[0].approvalSource='';}x.mem.imports.set(x.batch.id,copy(x.batch));await publish(x.root);const loaded=await u.fetchImportFromCloud(x.root,x.batch.id);assert.equal(loaded.lifecycle,x.batch.lifecycle);assert.equal(loaded.rows[0].certainty,x.batch.rows[0].certainty);}finally{x.mem.restore();}});
test('SY9 viewport independent financial projection and persisted JSON',()=>{const s=state(),b=materialize(s,[row('expense')]),before=copy(s);global.innerWidth=390;const a=e.financialForecastForMonth(s,'2026-10');global.innerWidth=1440;const z=e.financialForecastForMonth(s,'2026-10');assert.deepEqual(a,z);assert.deepEqual(s,before);delete global.innerWidth;});
test('SY10 interrupted journal restores operation receipt exactly once',async()=>{const mem=memory();try{const s=state(),r=row('source'),b={id:'journal-batch',version:0,accountProfileId:'joint',rows:[r],summary:{}};const root={state:s,commitChange:fn=>{fn();return true;}};const write=u.ImportStore.putImport;u.ImportStore.putImport=async()=>{throw new Error('interrupt');};await assert.rejects(u.approveStoredSource(root,b,r),/interrupt/);assert.equal(s.transactions.filter(tx=>tx.recordRole!=='bank-source').length,0);/* Simulate abrupt process termination before the failure handler: its durable pending receipt survives. */for(const entry of mem.journals.values())if(entry.operation==='import-command')entry.status='pending';u.ImportStore.putImport=write;await u.recoverJournal(root);await u.recoverJournal(root);assert.equal(s.transactions.filter(tx=>tx.recordRole!=='bank-source').length,1);assert.equal(mem.journals.values().next().value.status,'completed');}finally{mem.restore();}});
test('SY11 failed stage retries same intent without double financial rows',async()=>{const x=await setup();try{const write=x.remote.f.setDoc;let once=true;x.remote.f.setDoc=async(...args)=>{if(once){once=false;throw new Error('offline');}return write(...args);};await assert.rejects(publish(x.root),/offline/);assert.equal(x.mem.queue.size,1);await publish(x.root);assert.equal(x.mem.queue.size,0);assert.equal(x.remote.documents.get('core').transactions.filter(tx=>tx.recordRole!=='bank-source').length,1);}finally{x.mem.restore();}});
test('SY12 details failure never publishes core state',async()=>{const x=await setup();try{x.remote.f.setDoc=async()=>{throw new Error('details-failed');};await assert.rejects(publish(x.root));assert.equal(x.remote.documents.has('core'),false);assert.equal(x.mem.queue.size,1);assert.equal(x.s.transactions.filter(tx=>tx.recordRole!=='bank-source').length,1);}finally{x.mem.restore();}});
test('SY13 reproduced older upload cannot erase newer queued approval',async()=>{const x=await setup();try{let entered,release;const blocked=new Promise(r=>entered=r),gate=new Promise(r=>release=r),write=x.remote.f.setDoc;let first=true;x.remote.f.setDoc=async(...args)=>{if(first){first=false;entered();await gate;}return write(...args);};const pending=publish(x.root);await blocked;const newer=copy(x.batch);newer.version=2;newer.operationId='new-approved';newer.rows[0].processing.category='Newest';x.mem.imports.set(newer.id,newer);await u.queueImportSync(newer);release();await pending;assert.equal(x.mem.queue.size,1);assert.equal(x.mem.imports.get(newer.id).rows[0].processing.category,'Newest');assert.equal(x.mem.imports.get(newer.id).baseVersion,1);Object.assign(x.s.importSummaries[0],{version:2,operationId:newer.operationId});await publish(x.root);assert.equal((await u.fetchImportFromCloud(x.root,newer.id)).rows[0].processing.category,'Newest');assert.equal(x.mem.queue.size,0);}finally{x.mem.restore();}});
test('SY14 immutable original CSV, bank rows, processing and metadata preserved',async()=>{const x=await setup();try{x.batch.originalCsv='Exact original UTF8 €\n';x.batch.rows[0].sourceIdentityProof={kind:'file-row',rowOrdinal:1};x.batch.rows[0].processing.refundMonth='2026-08';x.batch.rows[0].processing.note='saved choice';x.mem.imports.set(x.batch.id,copy(x.batch));await publish(x.root);const reloaded=await u.fetchImportFromCloud(x.root,x.batch.id);assert.equal(reloaded.originalCsv,x.batch.originalCsv);assert.deepEqual(reloaded.rows,x.batch.rows);}finally{x.mem.restore();}});
test('Atomic publication is wired into existing compact-state transaction',()=>{const source=fs.readFileSync('src/core/runtime.js','utf8');assert.match(source,/await importStage\?\.readAndValidate\(transaction\)/);assert.match(source,/importStage\?\.publish\(transaction\)/);assert.match(source,/transaction.set\(this.docRef/);});
test('Same-source overlapping edits require choice; independent source edits preserved',()=>{const base=state(),b=materialize(base,[row('a'),row('b')]),local=copy(base),remote=copy(base);local.transactions[0].category='Local';remote.transactions[0].category='Cloud';assert.equal(sync.findImportConflicts(base,local,remote)[0].kind,'source');remote.transactions[0]=copy(base.transactions[0]);remote.transactions[1].category='Independent';assert.equal(sync.findImportConflicts(base,local,remote).length,0);});
test('Generation mismatch/incomplete upload cannot be accepted',()=>{const b={id:'batch',operationId:'generation-a',rows:[{id:'source'}]},envelope=u.buildCloudImportEnvelope(b);assert.throws(()=>u.assembleCloudImport(envelope.header,[{...envelope.chunks[0],generation:'generation-b'}],b.id),e=>e.code==='cloud-incomplete');});
test('Deleted proof rejects stale resurrecting header; retains no financial payload',()=>{const proof={id:'batch',version:3,lifecycle:'deleted',operationId:'delete',deletedAt:'2026-10-06'};assert.throws(()=>sync.assertImportBase(proof,{id:'batch',baseVersion:3,version:4,operationId:'stale'}),e=>e.code==='import-deleted');assert.equal(JSON.stringify(proof).includes('amount'),false);});

test('AUDIT startup preserves offline approved choice before authoritative cloud acceptance',async()=>{const x=await setup();try{const remote=state(),before=copy(x.s);assert.equal(await u.preservePendingImportsBeforeRemote(x.root,remote),true);const conflict=x.mem.journals.get('conflict-'+x.batch.id);assert.equal(conflict.status,'conflict');assert.deepEqual(conflict.localChoice.rows,x.batch.rows);assert.deepEqual(x.s,before);}finally{x.mem.restore();}});
test('AUDIT explicit cloud choice resolves preserved conflicting processing',async()=>{const x=await setup();try{await publish(x.root);const local=copy(x.batch);local.rows[0].processing.category='Conflicting local';await u.preserveImportConflict(x.root,local,x.batch);x.mem.queue.set(x.batch.id,{id:x.batch.id,importId:x.batch.id,version:2,operationId:'conflict'});await u.resolveImportConflict(x.root,x.batch.id,'cloud');assert.equal(x.mem.queue.size,0);assert.equal(x.mem.imports.get(x.batch.id).rows[0].processing.category,'Kleding');assert.equal(x.mem.journals.get('conflict-'+x.batch.id).status,'resolved');}finally{x.mem.restore();}});
test('AUDIT explicit local choice reopens copied processing without auto approval',async()=>{const x=await setup();try{await publish(x.root);const local=copy(x.batch);local.rows[0].processing.category='Local proposal';await u.preserveImportConflict(x.root,local,x.batch);x.root.commitChange=fn=>{fn();return true;};await u.resolveImportConflict(x.root,x.batch.id,'local');assert.equal(x.mem.imports.get(x.batch.id).rows[0].processing.category,'Local proposal');assert.equal(x.mem.imports.get(x.batch.id).rows[0].certainty,'nakijken');assert.equal(e.sumTransactionEffects(x.s,'realExpense'),0);}finally{x.mem.restore();}});
test('AUDIT large UTF8 source chunk boundaries preserve surrogate pairs',()=>{const text='a'.repeat(99999)+'😀€'+'b'.repeat(100001),envelope=u.buildCloudImportEnvelope({id:'utf8',operationId:'utf8-op',originalCsv:text,rows:[]});assert.equal(envelope.sourceChunks.join(''),text);assert.ok(envelope.sourceChunks.every(part=>!/[\uD800-\uDBFF]$/.test(part)));});


test('AUDIT local conflict reprocessing is journaled and details failure preserves cloud effects',async()=>{const x=await setup();try{await publish(x.root);const local=copy(x.batch);local.rows[0].processing.category='Local choice';await u.preserveImportConflict(x.root,local,x.batch);x.root.commitChange=fn=>{fn();return true;};const original=u.ImportStore.putImport;let calls=0;u.ImportStore.putImport=async record=>{if(++calls===2)throw new Error('local-details-failed');return original(record);};const before=copy(x.s);await assert.rejects(u.resolveImportConflict(x.root,x.batch.id,'local'),/local-details-failed/);assert.deepEqual(x.s,before);assert.equal(x.mem.journals.get('conflict-'+x.batch.id).status,'conflict');assert.ok([...x.mem.journals.values()].some(entry=>entry.operation==='import-command'&&entry.status==='rolled-back'));await u.recoverJournal(x.root);assert.deepEqual(x.s,before);}finally{x.mem.restore();}});
test('AUDIT legacy pending details acquire transport revision on an explicit retry, stable subsequent saves',async()=>{const x=await setup();try{const legacy=copy(x.batch);delete legacy.operationId;delete legacy.version;delete legacy.baseVersion;x.mem.imports.set(legacy.id,copy(legacy));x.root.commitChange=fn=>{fn();return true;};await u.persistImportDraft(x.root,legacy,{syncCloud:false});assert.ok(legacy.operationId);assert.equal(legacy.version,1);const before=copy(legacy);await u.persistImportDraft(x.root,legacy,{syncCloud:false});assert.deepEqual(legacy,before);}finally{x.mem.restore();}});

test('AUDIT interrupted draft save recovers original rows and compact receipt without default reset',async()=>{const mem=memory();try{const s=state(),draft={id:'draft-recovery',version:0,status:'concept',rows:[{...row('review'),certainty:'nakijken',processingStatus:'nakijken',approvalSource:''}],summary:{}},root={state:s,commitChange:fn=>{fn();return true;}};const write=u.ImportStore.putImport;u.ImportStore.putImport=async()=>{throw new Error('draft-interrupted');};await assert.rejects(u.persistImportDraft(root,draft,{syncCloud:false}),/draft-interrupted/);assert.equal(s.importSummaries.length,0);u.ImportStore.putImport=write;await u.recoverJournal(root);await u.recoverJournal(root);assert.equal(s.importSummaries.length,1);assert.deepEqual(mem.imports.get(draft.id).rows,draft.rows);assert.equal(s.transactions.filter(tx=>tx.recordRole!=='bank-source').length,0);}finally{mem.restore();}});

test('AUDIT interrupted journal recovery never publishes financial state before durable details',async()=>{const mem=memory();try{const s=state(),r=row('recover-safe'),b={id:'safe-recovery',version:0,accountProfileId:'joint',rows:[r],summary:{}},root={state:s,commitChange:fn=>{fn();return true;}};u.ImportStore.putImport=async()=>{throw new Error('details-still-offline');};await assert.rejects(u.approveStoredSource(root,b,r));/* Abrupt termination, rather than a reported/rolled-back failure. */for(const entry of mem.journals.values())if(entry.operation==='import-command')entry.status='pending';await assert.rejects(u.recoverJournal(root),/details-still-offline/);assert.equal(s.transactions.filter(tx=>tx.recordRole!=='bank-source').length,0);assert.equal(s.savingsGoalLedger.length,1);}finally{mem.restore();}});

test('AUDIT permanent cloud delete retains only technical proof and removes all chunk generations',async()=>{const x=await setup();try{x.batch.originalCsv='Original bank content';x.mem.imports.set(x.batch.id,copy(x.batch));await publish(x.root);const batch=await u.fetchImportFromCloud(x.root,x.batch.id),deleted=u.planImportCommand(x.s,batch,{type:'delete',operationId:'delete-all-chunks',timestamp:'2026-10-06T12:00:00Z'});deleted.batch.baseVersion=batch.baseVersion;x.root.state=deleted.state;x.mem.imports.set(batch.id,copy(deleted.batch));await u.queueImportSync(deleted.batch);Object.assign(x.remote.f,{collection:(ref,name)=>ref+'/'+name,getDocs:async prefix=>({docs:[...x.remote.documents.keys()].filter(ref=>ref.startsWith(prefix+'/')).map(ref=>({ref}))}),deleteDoc:async ref=>x.remote.documents.delete(ref)});await publish(x.root);assert.equal([...x.remote.documents.keys()].some(ref=>ref.includes('/chunks/')),false);const header=[...x.remote.documents.values()].find(value=>value.lifecycle==='deleted');assert.deepEqual(Object.keys(header).sort(),['baseVersion','deletedAt','deletedBy','id','lifecycle','operationId','version']);assert.equal(JSON.stringify([...x.remote.documents.values()]).includes('Original bank content'),false);assert.equal(x.mem.queue.size,0);}finally{x.mem.restore();}});

test('AUDIT core change during outbox write never gets overwritten by stale candidate',async()=>{const x=await setup();try{const root=x.root;root.commitChange=fn=>{fn();return true;};const queued=u.ImportStore.putSync;u.ImportStore.putSync=async record=>{await queued(record);root.state.monthRecords['2026-08'].snapshot.income=999;};const before=copy(root.state.transactions);await assert.rejects(u.commitImportCommand(root,x.batch,{type:'withdraw'}),/state wijzigde tijdens de opslagcommit/);assert.deepEqual(root.state.transactions,before);assert.equal(root.state.monthRecords['2026-08'].snapshot.income,999);assert.equal(x.mem.journals.get('conflict-'+x.batch.id).status,'conflict');}finally{x.mem.restore();}});

test('AUDIT choosing conflicting local processing keeps unchanged approved siblings active',async()=>{const mem=memory();try{const s=state(),b=materialize(s,[row('changed'),row('unchanged')]),remote=cloud(),root={state:s,CloudAdapter:remote.adapter,commitChange:fn=>{fn();return true;}};b.baseVersion=0;mem.imports.set(b.id,copy(b));await u.queueImportSync(b);await publish(root);const local=copy(b);local.rows[0].processing.category='Local changed category';await u.preserveImportConflict(root,local,b);await u.resolveImportConflict(root,b.id,'local');const saved=mem.imports.get(b.id);assert.equal(saved.rows[0].certainty,'nakijken');assert.equal(saved.rows[1].certainty,'goedgekeurd');assert.equal(e.sumTransactionEffects(s,'realExpense'),300);}finally{mem.restore();}});

test('AUDIT future-date import error blocks direct approval and manual replacement commands before mutation',async()=>{const mem=memory();try{const s=state();s.transactions.push({id:'manual',source:'manual',date:'2026-10-03',amount:20,accountContext:'gezamenlijk',financialFor:'gezamenlijk',transactionType:'uitgave',category:'Kleding'});const b=u.createImportDraft({id:'future-command',text:'Datum;Omschrijving;Rekening;Bedrag\n2099-01-01;Future;NL01JOINT;-20',profiles:s.accountProfiles,today:'2026-10-06'}),root={state:s,commitChange:fn=>{fn();return true;}};const before=copy(s);for(const type of ['source-approve','source-replacement'])await assert.rejects(u.commitImportCommand(root,b,{type,rowId:b.rows[0].id,manualId:'manual'}),e=>e.code==='future-transaction-date');assert.deepEqual(s,before);}finally{mem.restore();}});
