const test=require('node:test'),assert=require('node:assert/strict');
const {state,row,materialize,copy}=require('./helpers/package5-fixture.cjs');
const engine=require('../src/core/transaction-engine.mjs'),commands=require('../src/core/transaction-processing.mjs'),planning=require('../src/core/planning-timeline.mjs'),lifecycle=require('../src/import/import-lifecycle.mjs'),model=require('../src/core/transaction-model.mjs'),ledger=require('../src/core/data-normalization.mjs'),runtime=require('../src/import/update4-runtime.cjs');
const month='2026-10',today='2026-10-06';

async function workerNavigation(response){
 const fs=require('node:fs'),vm=require('node:vm'),handlers={},cached=new Map();
 const html=fs.readFileSync('index.html','utf8');cached.set('./index.html',new Response(html));
 const caches={open:async()=>({put:async(key,value)=>cached.set(key,value.clone())}),match:async key=>cached.get(key)?.clone()};
 vm.runInNewContext(fs.readFileSync('service-worker.js','utf8'),{self:{addEventListener:(key,handler)=>handlers[key]=handler,skipWaiting:()=>{},clients:{claim:()=>{}}},caches,fetch:async()=>response.clone()});
 let navigation;handlers.fetch({request:{method:'GET',mode:'navigate'},respondWith:promise=>navigation=promise});await navigation;await new Promise(resolve=>setImmediate(resolve));return {html,cached:await cached.get('./index.html').text()};
}
test('P7 W3 interrupted release navigation retains offline shell for cached asset version',async()=>{const fs=require('node:fs'),html=fs.readFileSync('index.html','utf8'),next=html.replaceAll('111-private-income-import-history','106-isolated-test');const result=await workerNavigation(new Response(next));assert.equal(result.cached,result.html);});
test('P7 W5 failed HTTP navigation never replaces valid offline shell',async()=>{const result=await workerNavigation(new Response('<html>Service unavailable</html>',{status:503}));assert.equal(result.cached,result.html);});
async function workerInstall(html){
 const fs=require('node:fs'),vm=require('node:vm'),handlers={},cached=new Map(),deleted=[];
 const cache={addAll:async keys=>keys.forEach(key=>cached.set(key,new Response(html))),add:async()=>{},match:async key=>cached.get(key)?.clone()};
 const caches={open:async()=>cache,delete:async key=>{deleted.push(key);cached.clear();return true;}};
 vm.runInNewContext(fs.readFileSync('service-worker.js','utf8'),{self:{addEventListener:(key,handler)=>handlers[key]=handler,skipWaiting:()=>{},clients:{claim:()=>{}}},caches});
 let installing;handlers.install({waitUntil:promise=>installing=promise});return {installing,deleted};
}
test('P7 W2/W3 mismatched shell cannot install over the working worker',async()=>{const fs=require('node:fs'),html=fs.readFileSync('index.html','utf8').replaceAll('111-private-income-import-history','101-functional-consolidation'),result=await workerInstall(html);await assert.rejects(result.installing,/assetversie/);assert.deepEqual(result.deleted,['finize-v111-private-income-import-history']);});
test('P7 W1 matching shell installs successfully',async()=>{const result=await workerInstall(require('node:fs').readFileSync('index.html','utf8'));await result.installing;assert.deepEqual(result.deleted,[]);});
function manual(s,id,changes={},account='gezamenlijk'){return commands.upsertManualFinancialTransaction(s,{id,source:'manual',date:month+'-03',amount:100,transactionType:'uitgave',category:'Kleding',financialFor:account,budgetOwner:account,...changes},account,{today});}
function batchCommand(s,b,type){return lifecycle.planImportCommand(s,b,{type,operationId:b.id+'-'+type,timestamp:today+'T12:00:00Z'},{validateRow:runtime.rowProcessingValidation});}
function fixed(s){const item={id:'fixed-p7',naam:'P7 fixed',categorie:'Wonen',bedrag:100,rekening:'gezamenlijk',financialFor:'gezamenlijk',begindatum:'2026-01-01',actief:true,frequentieAantal:1,frequentieEenheid:'maanden',amountHistory:[{id:'fixed-initial',effectiveFrom:'2026-01-01',amount:100}],monthOverrides:{}};s.recurringFixedExpenses=[item];return item;}

test('P7 M12 orphan fixed occurrence blocks manual create before mutation',()=>{const s=state(),before=copy(s);assert.throws(()=>manual(s,'orphan',{fixedOccurrenceId:'missing:2026-10-01',fixedOccurrenceMonth:month}),/vaste|betaal/i);assert.deepEqual(s,before);});
test('P7 C18 orphan fixed occurrence blocks source and split approval validation',()=>{
 for(const split of [false,true]){const r=row('orphan');const line={transactionType:'uitgave',category:'Kleding',budgetOwner:'gezamenlijk',amount:300,fixedOccurrenceId:'missing:2026-10-01',fixedOccurrenceMonth:month};if(split)r.processing.splits=[line];else Object.assign(r.processing,line);const before=copy(r);assert.equal(engine.validateTransactionProcessing(r).ok,false);assert.deepEqual(r,before);}
});
test('P7 M13 integer-cent overflow blocks manual create and edit before mutation',()=>{const s=state(),before=copy(s);assert.throws(()=>manual(s,'unsafe',{amount:90071992547410}),/cent/i);assert.deepEqual(s,before);manual(s,'normal');const saved=copy(s);assert.throws(()=>commands.upsertManualFinancialTransaction(s,{id:'normal',amount:90071992547410},'gezamenlijk',{today}),/cent/i);assert.deepEqual(s,saved);});
test('P7 I20 integer-cent overflow blocks source and split processing',()=>{const r=row('unsafe','uitgave',-90071992547410);assert.equal(engine.validateTransactionProcessing(r).ok,false);const split=row('split');split.processing.splits=[{amount:90071992547410,category:'Kleding',budgetOwner:'gezamenlijk',transactionType:'uitgave'}];assert.equal(engine.validateTransactionProcessing(split).ok,false);});

test('P7 P1-P3/P7/P12 five budget boundaries, once override and restart survive JSON',()=>{
 const s=state();for(const [m,amount]of [['2026-01',500],['2026-03',600],['2026-06',550],['2026-09',null],['2026-11',700]])planning.setBudgetForMonth(s,'gezamenlijk',m,amount===null?[]:[{id:'p7-budget',post:'Kleding',bedrag:amount}]);
 planning.setBudgetForMonth(s,'gezamenlijk','2026-07',[{id:'p7-budget',post:'Kleding',bedrag:575}],{scope:'once'});
 const expected=[500,500,600,600,600,550,575,550,null,null,700,700];for(let i=1;i<=12;i++){const rows=planning.resolveVariableBudgetsForMonth(copy(s),`2026-${String(i).padStart(2,'0')}`,'gezamenlijk');assert.equal(rows[0]?.bedrag??null,expected[i-1]);}
 const before=copy(s);for(let i=0;i<5;i++)engine.financialForecastForMonth(s,'2026-12');assert.deepEqual(s,before);assert.deepEqual(s.transactions,[]);
});
test('P7 P4/P5/P8/P13 fixed property history, end-exclusive stop and explicit restart',()=>{
 const s=state(),item=fixed(s);planning.setRecurringFromMonth(item,'2026-03',{bedrag:600,naam:'March',categorie:'Huis',rekening:'dion',financialFor:'dion',betaaldag:15});planning.setRecurringFromMonth(item,'2026-06',{bedrag:550,naam:'June'});planning.setRecurringFromMonth(item,'2026-07',{bedrag:575},{scope:'once'});planning.endRecurringFromMonth(item,'2026-09');item.validUntil=null;planning.setRecurringFromMonth(item,'2026-11',{bedrag:700,actief:true,validUntil:null});
 for(const [m,amount,owner]of [['2026-02',100,'gezamenlijk'],['2026-03',600,'dion'],['2026-06',550,'dion'],['2026-07',575,'dion'],['2026-08',550,'dion'],['2026-09',null,null],['2026-10',null,null],['2026-11',700,'dion']]){const result=planning.resolveRecurringConfig(item,m);assert.equal(result?.bedrag??null,amount);assert.equal(result?.financialFor??null,owner);if(result&&m>='2026-03')assert.equal(result.betaaldag,15);}
});
test('P7 P6/P9/P14 salary history with once/stop/restart and explicit dashboard zero',()=>{
 const s=state();s.recurringIncomeSources=[{...fixed(s),id:'salary-dion-p7',naam:'Loon Dion',eigenaar:'dion',legacyKind:'salary',verwachtBedrag:3000,amountHistory:[{id:'salary-start',effectiveFrom:'2026-01-01',amount:3000}]}];s.recurringFixedExpenses=[];
 for(const [m,amount]of [['2026-03',3200],['2026-06',3100]])planning.setIncomeSourceForMonth(s,s.recurringIncomeSources[0],m,{eigenaar:'dion',verwachtBedrag:amount});planning.setIncomeSourceForMonth(s,s.recurringIncomeSources[0],'2026-07',{eigenaar:'dion',verwachtBedrag:3150},{scope:'once'});planning.endIncomeSourceFromMonth(s,s.recurringIncomeSources[0],'2026-09');planning.setPlannedIncomeFromMonth(s,'dion','2026-11',3300,0);
 for(const [m,amount]of [['2026-02',3000],['2026-03',3200],['2026-06',3100],['2026-07',3150],['2026-08',3100],['2026-09',0],['2026-10',0],['2026-11',3300]])assert.equal(planning.resolvePlannedIncomeForMonth(copy(s),m,'dion').salary,amount);
 s.monthlyIncomeOverrides={[month]:{dion:0}};assert.equal(engine.financialForecastForMonth(s,month).owners.dion.salary,0);assert.equal(engine.actualIncomeForMonth(s,month).amount,0);
});
test('P7 P10/P11/P15 other income versions and month-only savings do not create actuals',()=>{
 const s=state();s.recurringIncomeSources=[{...fixed(s),id:'other-income',eigenaar:'dion',verwachtBedrag:100,amountHistory:[{id:'first',effectiveFrom:'2026-01-01',amount:100}]}];s.recurringFixedExpenses=[];
 planning.setIncomeSourceForMonth(s,s.recurringIncomeSources[0],'2026-03',{eigenaar:'dara',rekening:'gezamenlijk',verwachtBedrag:200,naam:'Other March'});planning.endIncomeSourceFromMonth(s,s.recurringIncomeSources[0],'2026-09');assert.equal(planning.resolveIncomeSourcesForMonth(s,'2026-02')[0].eigenaar,'dion');assert.equal(planning.resolveIncomeSourcesForMonth(s,'2026-03')[0].eigenaar,'dara');assert.equal(planning.resolveIncomeSourcesForMonth(s,'2026-09').length,0);
 planning.setSavingsPlanForMonth(s,'gezamenlijk','2027-01',400);assert.equal(engine.financialForecastForMonth(s,'2026-12').allowanceBasis.owners.gezamenlijk.savingsReserve,250);assert.equal(engine.financialForecastForMonth(s,'2027-01').allowanceBasis.owners.gezamenlijk.savingsReserve,400);assert.equal(engine.financialForecastForMonth(s,'2027-02').allowanceBasis.owners.gezamenlijk.savingsReserve,250);assert.deepEqual(s.transactions,[]);
});
test('P7 M1-M3/M8/M9 approved edits preserve ID, original account and unknown fields',()=>{
 for(const account of ['dion','dara','gezamenlijk']){const s=state();s.budgetDefaultsHistory[account]=[{effectiveFrom:'0000-01',rows:[{id:'clothing',post:'Kleding',bedrag:100}]}];manual(s,'manual-'+account,{custom:{audit:'retained'}},account);commands.upsertManualFinancialTransaction(s,{id:'manual-'+account,amount:125,date:'2026-09-03',description:'Changed',note:'Memo'},account,{today});assert.equal(s.transactions.length,1);assert.equal(s.transactions[0].accountContext,account);assert.equal(s.transactions[0].financialFor,account);assert.equal(s.transactions[0].transactionDate,'2026-09-03');assert.equal(model.getTransactionProcessingStatus(s.transactions[0]),'goedgekeurd');assert.deepEqual(s.transactions[0].custom,{audit:'retained'});}
});
test('P7 M10/M11/X12 closed original and new month reject edit before mutation',()=>{
 for(const direction of ['into','out']){const s=state();s.monthRecords={};manual(s,'closed',{date:direction==='out'?'2026-09-03':'2026-10-03'});s.monthRecords['2026-09']={status:'afgesloten',snapshot:{immutable:123},closureHistory:[{id:'saved-closure'}]};const before=copy(s);assert.throws(()=>commands.upsertManualFinancialTransaction(s,{id:'closed',date:direction==='out'?'2026-10-03':'2026-09-03'},'gezamenlijk',{today}),/afgesloten/);assert.deepEqual(s,before);}
});
test('P7 M14/M15 calendar, zero, negative and sub-cent values cannot partially mutate',()=>{
 const s=state();for(const changes of [{date:'2026-02-29'},{date:'2026-10-07'},{amount:0},{amount:-1},{amount:.001}]){const before=copy(s);assert.throws(()=>manual(s,'invalid',changes));assert.deepEqual(s,before);}manual(s,'leap',{date:'2024-02-29',amount:.01});assert.equal(engine.sumTransactionEffects(s,'realExpense',{month:'2024-02'}),.01);
});
test('P7 X1/C1/C2 CSV expense coverage withdraw/restore never duplicates ledger or allocation',()=>{
 const s=state(),w=materialize(s,[row('withdrawal','van-spaarrekening',500,{savingsGoalId:'goal'})],'withdrawals'),x=materialize(s,[row('covered','uitgave',-300)],'expenses');commands.setSavingsCoverageAllocation(s,{id:'p7-allocation',withdrawalTransactionId:'tx-withdrawal',expenseTransactionId:'tx-covered',amountCents:20000});const original=copy(s),basis=engine.financialForecastForMonth(s,month).allowanceBasis;
 const inactive=batchCommand(s,x,'withdraw');assert.equal(engine.sumTransactionEffects(inactive.state,'unusedSavings'),500);assert.equal(engine.sumTransactionEffects(inactive.state,'realExpense'),0);assert.deepEqual(engine.financialForecastForMonth(inactive.state,month).allowanceBasis,basis);
 const restored=batchCommand(inactive.state,inactive.batch,'restore');assert.equal(engine.sumTransactionEffects(restored.state,'budgetImpact'),100);assert.equal(engine.sumTransactionEffects(restored.state,'unusedSavings'),300);assert.equal(restored.state.savingsGoalLedger.length,original.savingsGoalLedger.length);assert.equal(restored.state.savingsCoverageAllocations.length,1);assert.equal(batchCommand(restored.state,restored.batch,'restore').noop,true);assert.deepEqual(s,original);assert.equal(w.id,'withdrawals');
});
test('P7 X2/X10 historical category refund withdraw/restore retains original expense and bankdate',()=>{
 const s=state();manual(s,'past-expense',{date:'2026-09-03',amount:100});planning.setBudgetForMonth(s,'gezamenlijk',month,[]);const b=materialize(s,[row('refund','terugbetaling',30,{refundCategory:'Kleding',refundMonth:'2026-09'})],'refunds'),expense=copy(s.transactions.find(t=>t.id==='past-expense'));
 assert.equal(engine.sumTransactionEffects(s,'budgetImpact',{month:'2026-09'}),70);const inactive=batchCommand(s,b,'withdraw');assert.equal(engine.sumTransactionEffects(inactive.state,'budgetImpact',{month:'2026-09'}),100);assert.equal(engine.sumTransactionEffects(inactive.state,'accountCashflow',{month}),0);const active=batchCommand(inactive.state,inactive.batch,'restore');assert.equal(engine.sumTransactionEffects(active.state,'budgetImpact',{month:'2026-09'}),70);assert.equal(engine.sumTransactionEffects(active.state,'accountCashflow',{month}),30);assert.equal(engine.actualIncomeForMonth(active.state,month).amount,0);assert.deepEqual(active.state.transactions.find(t=>t.id==='past-expense'),expense);
});
test('P7 X3 fixed actual with coverage retains deviation after future planning edit',()=>{
 const s=state(),item=fixed(s);materialize(s,[row('fixed-payment','vaste-last',-105,{category:'Wonen',fixedExpenseId:item.id,fixedOccurrenceId:'fixed-p7:2026-10-01',fixedOccurrenceMonth:month})],'fixed-batch');materialize(s,[row('fixed-withdrawal','van-spaarrekening',40,{savingsGoalId:'goal'})],'withdrawal-batch');commands.setSavingsCoverageAllocation(s,{id:'fixed-coverage',withdrawalTransactionId:'tx-fixed-withdrawal',expenseTransactionId:'tx-fixed-payment',amountCents:4000});const transactions=copy(s.transactions);planning.setRecurringFromMonth(item,'2026-11',{bedrag:150,naam:'November fixed'});
 assert.deepEqual(s.transactions,transactions);assert.equal(engine.financialForecastForMonth(s,month).owners.gezamenlijk.fixedBurden,65);assert.equal(engine.financialForecastForMonth(s,month).allowanceBasis.owners.gezamenlijk.fixedReserve,100);assert.deepEqual({...engine.fixedOccurrenceActuals(s,{id:'fixed-p7:2026-10-01',month,amount:100}),rows:[]},{planned:100,actual:105,deviation:5,paid:true,status:'Betaald',rows:[]});
});
test('P7 X4 salary actual beats dashboard zero and future planned income without changing planning',()=>{
 const s=state();s.monthlyIncomeOverrides={[month]:{dion:0}};manual(s,'salary',{transactionType:'salaris',amount:3100,financialFor:'dion',budgetOwner:'dion',category:'Salaris'});const transactions=copy(s.transactions);planning.setPlannedIncomeFromMonth(s,'dion','2027-01',3300,0);const f=engine.financialForecastForMonth(s,month);assert.equal(f.owners.dion.salary,3100);assert.equal(f.owners.dion.salarySource,'transactions');assert.equal(engine.sumTransactionEffects(s,'accountCashflow',{account:'gezamenlijk'}),3100);assert.equal(engine.sumTransactionEffects(s,'accountCashflow',{account:'dion'}),0);assert.equal(planning.resolvePlannedIncomeForMonth(s,month,'dion').salary,3000);assert.equal(engine.financialForecastForMonth(s,'2027-01').owners.dion.salary,3300);assert.deepEqual(s.transactions,transactions);
});
test('P7 X5 confirmed transfer withdrawn endpoint preserves independent physical movement',()=>{
 const s=state(),b=materialize(s,[row('transfer-out','interne-overboeking',-500,{sourceAccountProfileId:'joint',destinationAccountProfileId:'dion'})],'transfer-batch');manual(s,'transfer-in',{transactionType:'interne-overboeking',kind:'inkomen',amount:500,accountDelta:500,category:'Overig'},'dion');s.internalTransferPairs=[{id:'p7-pair',transactionIds:['tx-transfer-out','transfer-in'],status:'voorgesteld'}];engine.confirmInternalTransferPair(s,'p7-pair');const independent=copy(s.transactions.find(t=>t.id==='transfer-in')),inactive=batchCommand(s,b,'withdraw');assert.deepEqual(inactive.state.transactions.find(t=>t.id==='transfer-in'),independent);assert.equal(engine.sumTransactionEffects(inactive.state,'accountCashflow',{account:'dion'}),500);assert.equal(engine.sumTransactionEffects(inactive.state,'externalHouseholdCashflow'),0);const active=batchCommand(inactive.state,inactive.batch,'restore');assert.equal(engine.sumTransactionEffects(active.state,'accountCashflow'),0);assert.equal(engine.sumTransactionEffects(active.state,'externalHouseholdCashflow'),0);
});
test('P7 X6/X7 CSV replacement withdrawal/delete safely reactivates independent manual source',()=>{
 const s=state();manual(s,'manual-baseline',{amount:300,description:'Manual preserved'});const official=row('official');engine.confirmManualReplacement(s,official,'manual-baseline','replacement-batch');assert.equal(official.processingStatus,'nakijken');runtime.markExplicitlyApproved(official);const b=materialize(s,[official],'replacement-batch'),manualRow=copy(s.transactions.find(t=>t.id==='manual-baseline'));
 for(const type of ['withdraw','delete']){const result=batchCommand(s,b,type);assert.equal(engine.sumTransactionEffects(result.state,'realExpense'),300);assert.deepEqual(result.state.transactions.find(t=>t.id==='manual-baseline'),manualRow);assert.equal(engine.selectActiveTransactions(result.state).filter(t=>t.id==='manual-baseline').length,1);if(type==='delete'){assert.equal(result.state.transactions.length,1);assert.equal(result.state.importDeletionProofs[0].lifecycle,'deleted');}}
});
test('P7 X8 refund plus coverage never allows negative category burden or partial edit',()=>{
 const s=state();manual(s,'purchase',{amount:300});manual(s,'withdrawal',{transactionType:'van-spaarrekening',savingsGoalId:'goal',amount:100});commands.setSavingsCoverageAllocation(s,{id:'coverage',withdrawalTransactionId:'withdrawal',expenseTransactionId:'purchase',amountCents:10000});manual(s,'refund',{transactionType:'terugbetaling',refundCategory:'Kleding',refundMonth:month,amount:50});const result=engine.categoryFinancialActuals(s,month,'gezamenlijk')[0];assert.equal(result.realExpense,300);assert.equal(result.savingsFunded,100);assert.equal(result.refundCorrection,50);assert.equal(result.budgetImpact,150);const before=copy(s);assert.throws(()=>commands.upsertManualFinancialTransaction(s,{id:'purchase',amount:120},'gezamenlijk',{today}),/Refunds/);assert.deepEqual(s,before);
});
test('P7 X9 partially unused withdrawal and independent historical refund remain separate',()=>{
 const s=state();manual(s,'past',{date:'2026-09-03'});const basis=engine.financialForecastForMonth(s,month).allowanceBasis;manual(s,'withdrawal',{transactionType:'van-spaarrekening',savingsGoalId:'goal',amount:500});manual(s,'expense',{amount:300});commands.setSavingsCoverageAllocation(s,{id:'coverage',withdrawalTransactionId:'withdrawal',expenseTransactionId:'expense',amountCents:20000});manual(s,'refund',{transactionType:'terugbetaling',amount:30,refundCategory:'Kleding',refundMonth:'2026-09'});assert.equal(engine.sumTransactionEffects(s,'unusedSavings',{month}),300);assert.equal(engine.sumTransactionEffects(s,'budgetImpact',{month:'2026-09'}),70);assert.equal(engine.sumTransactionEffects(s,'incomeImpact',{month}),0);assert.deepEqual(engine.financialForecastForMonth(s,month).allowanceBasis,basis);
});
test('P7 X11 future configuration does not modify current actuals or earlier planning',()=>{
 const s=state(),item=fixed(s);manual(s,'current');const before=copy(s.transactions),current=engine.financialForecastForMonth(s,month);planning.setRecurringFromMonth(item,'2027-01',{bedrag:150});planning.setBudgetForMonth(s,'gezamenlijk','2027-01',[{id:'future',post:'Future',bedrag:700}]);planning.setPlannedIncomeFromMonth(s,'dion','2027-01',3300,0);assert.deepEqual(s.transactions,before);assert.deepEqual(engine.financialForecastForMonth(s,month),current);assert.equal(engine.actualIncomeForMonth(s,'2027-01').amount,0);assert.equal(engine.sumTransactionEffects(s,'realExpense',{month:'2027-01'}),0);
});
test('P7 X13 physical account selector and financial category detail never double-count',()=>{
 const s=state();manual(s,'cross',{financialFor:'gezamenlijk',budgetOwner:'gezamenlijk'},'dion');assert.equal(engine.selectActiveTransactions(s,{month,account:'dion'}).length,1);assert.equal(engine.selectActiveTransactions(s,{month,account:'gezamenlijk'}).length,0);assert.equal(engine.sumTransactionEffects(s,'realExpense'),100);assert.deepEqual(engine.categoryActuals(s,month,'gezamenlijk'),{Kleding:100});assert.deepEqual(engine.categoryActuals(s,month,'dion'),{});
});
test('P7 X14 split fixed link source reopen removes both projections and preserves bank source',()=>{
 const s=state();fixed(s);const r=row('split','uitgave',-150);r.processing.splits=[{id:'fixed',amount:100,category:'Wonen',transactionType:'vaste-last',budgetOwner:'gezamenlijk',fixedExpenseId:'fixed-p7',fixedOccurrenceId:'fixed-p7:2026-10-01',fixedOccurrenceMonth:month},{id:'other',amount:50,category:'Kleding',transactionType:'uitgave',budgetOwner:'gezamenlijk'}];const b=materialize(s,[r],'split-batch'),bank=copy(r.bankOriginal),basis=engine.financialForecastForMonth(s,month).allowanceBasis;assert.equal(engine.sumTransactionEffects(s,'realExpense'),150);assert.equal(engine.sumTransactionEffects(s,'budgetImpact'),50);assert.equal(engine.fixedOccurrenceActuals(s,{id:'fixed-p7:2026-10-01',month,amount:100}).actual,100);commands.reopenTransactionSource(s,b.id,r.id);assert.equal(engine.sumTransactionEffects(s,'accountCashflow'),0);assert.equal(engine.sumTransactionEffects(s,'realExpense'),0);assert.equal(engine.fixedOccurrenceActuals(s,{id:'fixed-p7:2026-10-01',month,amount:100}).paid,false);s.transactions.forEach(t=>assert.deepEqual(t.bankOriginal,bank));assert.deepEqual(engine.financialForecastForMonth(s,month).allowanceBasis,basis);
});
test('P7 X15 delete allocation endpoint removes only relation and owned payload, independent data remains',()=>{
 const s=state();manual(s,'withdrawal',{transactionType:'van-spaarrekening',savingsGoalId:'goal',amount:500});const b=materialize(s,[row('expense')],'expense-batch');commands.setSavingsCoverageAllocation(s,{id:'coverage',withdrawalTransactionId:'withdrawal',expenseTransactionId:'tx-expense',amountCents:20000});commands.correctGoalBalance(s,'goal',1600,{id:'independent-correction'});const independent=copy(s.transactions.find(t=>t.id==='withdrawal')),planningBefore=copy(s.planning),closures=copy(s.monthRecords),correction=copy(s.savingsGoalLedger.find(x=>x.id==='independent-correction'));
 const deleted=batchCommand(s,b,'delete');assert.deepEqual(deleted.state.transactions,[independent]);assert.deepEqual(deleted.state.planning,planningBefore);assert.deepEqual(deleted.state.monthRecords,closures);assert.deepEqual(deleted.state.savingsGoalLedger.find(x=>x.id==='independent-correction'),correction);assert.equal(deleted.state.savingsCoverageAllocations.length,0);assert.equal(engine.sumTransactionEffects(deleted.state,'unusedSavings'),500);assert.deepEqual(Object.keys(deleted.batch).sort(),['deletedAt','deletedBy','id','lifecycle','operationId','version']);
});
test('P7 S1-S4/S8 JSON/read purity keeps IDs, ledger, closures and unknown metadata',()=>{
 const s=state();s.unknown={provenance:['kept']};manual(s,'stored');const before=copy(s);for(let i=0;i<5;i++){engine.selectTransactionProjections(s,{includeInactive:true});engine.financialForecastForMonth(s,month);engine.categoryFinancialActuals(s,month);ledger.calculateGoalSavedAmount(s,'goal');}assert.deepEqual(s,before);assert.deepEqual(JSON.parse(JSON.stringify(s)),before);
});

test('P7 C10-C12 identical file after permanent deletion gets a new review-only batch identity',()=>{
 const s=state(),text='Datum;Omschrijving;Rekening;Bedrag\n2026-10-03;P7 reimport;NL01JOINT;-100';
 const first=runtime.createImportDraft({id:'p7-old-file',text,profiles:s.accountProfiles,entryOwner:'gezamenlijk',today});
 const source=first.rows[0];runtime.markExplicitlyApproved(source);Object.assign(source.processing,{category:'Kleding',budgetOwner:'gezamenlijk',transactionType:'uitgave',include:true});
 const b=materialize(s,[source],first.id);b.originalCsv=text;
 const deleted=batchCommand(s,b,'delete'),before=copy(deleted.state);
 const next=runtime.createImportDraft({id:'p7-new-file',text,profiles:deleted.state.accountProfiles,entryOwner:'gezamenlijk',transactions:deleted.state.transactions,existingImports:[deleted.batch],today});
 assert.equal(next.rows[0].duplicate,false);assert.notEqual(next.rows[0].id,source.id);assert.equal(model.isTransactionFinanciallyActive(next.rows[0]),false);assert.deepEqual(deleted.state,before);assert.equal(engine.sumTransactionEffects(deleted.state,'realExpense',{month}),0);
 runtime.markExplicitlyApproved(next.rows[0]);Object.assign(next.rows[0].processing,{category:'Kleding',budgetOwner:'gezamenlijk',transactionType:'uitgave',include:true});materialize(deleted.state,next.rows,next.id);
 assert.equal(engine.sumTransactionEffects(deleted.state,'realExpense',{month}),100);assert.equal(deleted.state.transactions.length,1);assert.equal(deleted.state.transactions[0].importBatchId,next.id);assert.equal(deleted.state.importDeletionProofs[0].id,first.id);
});
