const {test}=require('node:test'),assert=require('node:assert/strict');
const e=require('../src/core/transaction-engine.mjs'),c=require('../src/core/transaction-processing.mjs'),d=require('../src/core/data-normalization.mjs');
const clone=value=>JSON.parse(JSON.stringify(value));
function state(){return {meta:{schemaVersion:11},planning:{verdeling:{minimumDion:.4}},incomeDefaultsHistory:{dion:[{effectiveFrom:'0000-01',salary:2600,refund:0}],dara:[{effectiveFrom:'0000-01',salary:0,refund:0}]},budgetDefaultsHistory:{dion:[{effectiveFrom:'0000-01',rows:[{id:'clothes',post:'Kleding',bedrag:500}]}],dara:[],gezamenlijk:[]},transactions:[],spaardoelen:{dion:[{id:'vacation',naam:'Vakantie',algespaard:1000}],dara:[],gezamenlijk:[]},savingsGoalLedger:[{id:'opening',goalId:'vacation',effectiveAmount:1000,source:'legacy-opening',active:true}],accountProfiles:[],internalTransferPairs:[],manualTransactionReplacements:[],advanceLedger:[],advanceRepayments:[],recurringFixedExpenses:[],monthRecords:{},importSummaries:[]};}
function tx(id,amount,type='uitgave',extra={}){return {id,source:'manual',accountContext:'dion',financialFor:'dion',budgetOwner:'dion',owner:'dion',date:'2026-08-12',amount,transactionType:type,kind:type==='salaris'?'inkomen':'uitgave',category:'Kleding',processingStatus:'goedgekeurd',...extra};}
function add(s,t){c.upsertManualFinancialTransaction(s,t,t.accountContext||'dion');return s.transactions.find(row=>row.id===t.id);}
function withdrawal(s,id='w',amount=500,extra={}){return add(s,tx(id,amount,'van-spaarrekening',{category:'Sparen',savingsGoalId:'vacation',...extra}));}
function expense(s,id='x',amount=300,extra={}){return add(s,tx(id,amount,'uitgave',extra));}
function alloc(s,id,w,x,amount){const rows=e.selectTransactionProjections(s),a=rows.find(p=>p.id===w),b=rows.find(p=>p.id===x),ar=e.projectionLineReference(a),br=e.projectionLineReference(b);c.setSavingsCoverageAllocation(s,{id,withdrawalTransactionId:w,withdrawalSourceKey:ar.sourceKey,withdrawalSplitId:ar.splitId,expenseTransactionId:x,expenseSourceKey:br.sourceKey,expenseSplitId:br.splitId,amountCents:Math.round(amount*100)});}
const project=(s,id)=>e.selectTransactionProjections(s,{includeInactive:true}).find(p=>p.id===id);
const forecast=s=>e.financialForecastForMonth(s,'2026-08');
function csvify(s,id){const t=s.transactions.find(row=>row.id===id);Object.assign(t,{source:'csv',importBatchId:'batch',importTransactionId:id,approvalSource:'manual',certainty:'goedgekeurd',processingStatus:'goedgekeurd',bankOriginal:{bankDate:t.date,amount:t.transactionType==='van-spaarrekening'?t.amount:-t.amount,description:'immutable'}});return t;}
function reapprove(s,id){const previous=clone(s),t=s.transactions.find(row=>row.id===id);Object.assign(t,{processingStatus:'goedgekeurd',reviewStatus:'bevestigd',certainty:'goedgekeurd',approvalSource:'manual'});c.synchronizeChangedSavings(s,previous);c.assertFinancialMutationSafe(previous,s);}

test('S1 deposit 250 cash/goal/forecast without expense',()=>{const s=state();add(s,tx('deposit',250,'sparen',{savingsGoalId:'vacation',category:'Sparen'}));const p=project(s,'deposit');assert.equal(p.effects.accountCashflow,-250);assert.equal(p.effects.realExpense,0);assert.equal(p.effects.budgetImpact,0);assert.equal(d.calculateGoalSavedAmount(s,'vacation'),1250);assert.equal(forecast(s).household.available,2350);});
test('S2 withdrawal 500 no coverage',()=>{const s=state();withdrawal(s);assert.equal(project(s,'w').effects.incomeImpact,0);assert.equal(project(s,'w').effects.accountCashflow,500);assert.equal(project(s,'w').effects.unusedSavings,500);assert.equal(d.calculateGoalSavedAmount(s,'vacation'),500);assert.equal(forecast(s).household.available,3100);});
test('S3 withdrawal coverage 350 unused 150',()=>{const s=state();withdrawal(s);expense(s,'x',350);alloc(s,'a','w','x',350);assert.equal(project(s,'w').effects.unusedSavings,150);assert.equal(project(s,'x').effects.savingsFunded,350);assert.equal(d.calculateGoalSavedAmount(s,'vacation'),500);});
test('S4 later coverage 100 reduces unused to 50 without transaction',()=>{const s=state();withdrawal(s);expense(s,'x',450);alloc(s,'a','w','x',350);const n=s.transactions.length;alloc(s,'b','w','x',100);assert.equal(project(s,'w').effects.unusedSavings,50);assert.equal(s.transactions.length,n);});
test('S5 balance correction has no transaction/cashflow/forecast',()=>{const s=state(),before=forecast(s);c.correctGoalBalance(s,'vacation',1100,{id:'correction',createdAt:'action',note:'Bank balance verified'});assert.equal(d.calculateGoalSavedAmount(s,'vacation'),1100);assert.equal(s.transactions.length,0);assert.deepEqual(forecast(s),before);assert.equal(s.savingsGoalLedger.at(-1).balanceBefore,1000);assert.equal(s.savingsGoalLedger.at(-1).transactionId,'');});
test('S6 new savings without goal blocked',()=>{const s=state(),before=clone(s);assert.throws(()=>add(s,tx('bad',250,'naar-spaarrekening')),/spaardoel/);assert.deepEqual(s,before);});
test('C1 full coverage real 189 budget 0',()=>{const s=state();withdrawal(s);expense(s,'x',189);alloc(s,'a','w','x',189);assert.equal(project(s,'x').effects.realExpense,189);assert.equal(project(s,'x').effects.budgetImpact,0);});
test('C2 partial coverage 300/200 budget 100',()=>{const s=state();withdrawal(s);expense(s);alloc(s,'a','w','x',200);assert.equal(project(s,'x').effects.realExpense,300);assert.equal(project(s,'x').effects.budgetImpact,100);});
test('C3 one withdrawal multiple expenses',()=>{const s=state();withdrawal(s);expense(s,'hotel',300);expense(s,'food',100);alloc(s,'a','w','hotel',300);alloc(s,'b','w','food',100);assert.equal(project(s,'w').effects.unusedSavings,100);});
test('C4 multiple withdrawals one expense',()=>{const s=state();withdrawal(s,'w1',100);withdrawal(s,'w2',200);expense(s);alloc(s,'a','w1','x',100);alloc(s,'b','w2','x',200);assert.equal(project(s,'x').effects.budgetImpact,0);});
test('C5 over withdrawal atomic rejection',()=>{const s=state();withdrawal(s,'w',100);expense(s);const before=clone(s);assert.throws(()=>alloc(s,'a','w','x',101),/spaaropname/);assert.deepEqual(s,before);});
test('C6 over expense atomic rejection',()=>{const s=state();withdrawal(s);expense(s,'x',100);const before=clone(s);assert.throws(()=>alloc(s,'a','w','x',101),/uitgave/);assert.deepEqual(s,before);});
test('C7 other month blocked',()=>{const s=state();withdrawal(s);expense(s,'x',100,{date:'2026-09-01'});assert.throws(()=>alloc(s,'a','w','x',100),/kalendermaand/);});
test('C8 inactive withdrawal makes allocation inactive',()=>{const s=state();withdrawal(s);expense(s);alloc(s,'a','w','x',200);s.transactions[0].transactionType='niet-meetellen';assert.equal(project(s,'x').effects.budgetImpact,300);assert.equal(e.coverageAllocationStatus(s)[0].active,false);});
test('C9 inactive expense increases unused',()=>{const s=state();withdrawal(s);expense(s);alloc(s,'a','w','x',200);s.transactions[1].transactionType='niet-meetellen';assert.equal(project(s,'w').effects.unusedSavings,500);});
test('C10 exact cents no drift',()=>{const s=state();withdrawal(s,'w',.3);expense(s,'x',.3);alloc(s,'a','w','x',.1);alloc(s,'b','w','x',.2);assert.equal(project(s,'w').effects.unusedSavings,0);assert.equal(project(s,'x').effects.budgetImpact,0);assert.throws(()=>c.setSavingsCoverageAllocation(s,{id:'bad',withdrawalTransactionId:'w',expenseTransactionId:'x',amountCents:1.1}),/centen/);});
function refund(s,amount=30,extra={}){return add(s,tx('refund',amount,'terugbetaling',{date:'2026-09-12',refundCategory:'Kleding',refundMonth:'2026-08',...extra}));}
test('RF1 historical correction with September cash not income',()=>{const s=state();expense(s,'x',100);refund(s);assert.equal(e.categoryFinancialActuals(s,'2026-08','dion')[0].budgetImpact,70);assert.equal(e.sumTransactionEffects(s,'accountCashflow',{month:'2026-09'}),30);assert.equal(e.actualIncomeForMonth(s,'2026-09').amount,0);});
test('RF2 refund does not mutate original expense',()=>{const s=state();expense(s);const before=clone(s.transactions[0]);refund(s);assert.deepEqual(s.transactions[0],before);});
test('RF3 missing category blocks',()=>{const s=state();expense(s);assert.throws(()=>refund(s,30,{refundCategory:''}),/refundcategorie/);});
test('RF4 missing month blocks',()=>{const s=state();expense(s);assert.throws(()=>refund(s,30,{refundMonth:''}),/refundmaand/);});
test('RF5 recognition never approves',()=>{const s=state();s.transactions.push(tx('proposal',30,'terugbetaling',{source:'csv',certainty:'zeker',processingStatus:'nakijken',bankOriginal:{bankDate:'2026-09-12',amount:30},refundCategory:'Kleding',refundMonth:'2026-08'}));assert.equal(project(s,'proposal').active,false);});
test('RF6 inactive refund no correction',()=>{const s=state();expense(s,'x',100);refund(s);s.transactions[1].transactionType='niet-meetellen';assert.equal(e.categoryFinancialActuals(s,'2026-08','dion')[0].budgetImpact,100);});
test('RF7 historical removed category recognizable',()=>{const s=state();expense(s,'x',100);s.budgetDefaultsHistory.dion.push({effectiveFrom:'2026-09',rows:[]});refund(s);assert.equal(e.categoryFinancialActuals(s,'2026-08','dion')[0].budgetImpact,70);assert.equal(e.refundCategoryIsRecognizable(s,'Kleding','2026-08','dion'),true);});
test('RF8 refund plus coverage 300-100-50 budget150 gross300',()=>{const s=state();withdrawal(s);expense(s);alloc(s,'a','w','x',100);refund(s,50);assert.deepEqual(e.categoryFinancialActuals(s,'2026-08','dion')[0],{category:'Kleding',realExpense:300,savingsFunded:100,refundCorrection:50,categoryOnlyRefundCorrection:0,budgetImpact:150});});
test('P1 planned salary not actual income',()=>{const s=state();assert.equal(e.actualIncomeForMonth(s,'2026-08').amount,0);assert.equal(forecast(s).owners.dion.salary,2600);});
test('P2 actual salary replaces planning',()=>{const s=state();add(s,tx('salary',2645,'salaris'));assert.equal(forecast(s).owners.dion.income,2645);assert.equal(e.actualIncomeForMonth(s,'2026-08').amount,2645);});
test('P3 salary plus extra income2745',()=>{const s=state();add(s,tx('salary',2645,'salaris'));add(s,tx('extra',100,'vergoeding'));assert.equal(forecast(s).owners.dion.income,2745);});
test('P4 deposit reduces forecast no expense',()=>{const s=state(),before=forecast(s).household.available;add(s,tx('deposit',250,'naar-spaarrekening',{savingsGoalId:'vacation'}));assert.equal(forecast(s).household.available,before-250);assert.equal(e.sumTransactionEffects(s,'realExpense'),0);});
test('P5 unused 150 available component',()=>{const s=state();withdrawal(s);expense(s,'x',350);alloc(s,'a','w','x',350);assert.equal(forecast(s).owners.dion.unusedSavings,150);assert.equal(forecast(s).household.available,2750);});
test('P6 coverage preserves gross expense',()=>{const s=state();withdrawal(s);expense(s);alloc(s,'a','w','x',100);assert.equal(forecast(s).household.realExpense,300);assert.equal(forecast(s).owners.dion.variableBurden,200);});
test('P7 previous month refund bank month credit once',()=>{const s=state();expense(s,'x',100);refund(s);assert.equal(e.financialForecastForMonth(s,'2026-09').owners.dion.refundCashflow,30);assert.equal(forecast(s).household.available,2500);assert.equal(e.categoryFinancialActuals(s,'2026-08','dion')[0].budgetImpact,70);assert.equal(s.transactions[1].date,'2026-09-12');});
test('U1 exclusion savings source removes own goal effect',()=>{const s=state();withdrawal(s);const before=clone(s);s.transactions[0].transactionType='niet-meetellen';c.synchronizeChangedSavings(s,before);assert.equal(d.calculateGoalSavedAmount(s,'vacation'),1000);assert.equal(project(s,'w').effects.goalDelta,0);});
test('U2 reopen withdrawal goal and coverage inactive',()=>{const s=state();withdrawal(s);expense(s);csvify(s,'w');alloc(s,'a','w','x',200);c.reopenTransactionSource(s,'batch','w');assert.equal(d.calculateGoalSavedAmount(s,'vacation'),1000);assert.equal(project(s,'x').effects.budgetImpact,300);});
test('U3 reapproval exactly once',()=>{const s=state();withdrawal(s);expense(s);csvify(s,'w');alloc(s,'a','w','x',200);c.reopenTransactionSource(s,'batch','w');reapprove(s,'w');const before=clone(s);reapprove(s,'w');assert.deepEqual(s,before);assert.equal(project(s,'x').effects.budgetImpact,100);assert.equal(d.calculateGoalSavedAmount(s,'vacation'),500);});
test('U4 reopen expense increases unused',()=>{const s=state();withdrawal(s);expense(s);csvify(s,'x');alloc(s,'a','w','x',200);c.reopenTransactionSource(s,'batch','x');assert.equal(project(s,'w').effects.unusedSavings,500);});
test('U5 reopen refund removes historical correction',()=>{const s=state();expense(s);refund(s);csvify(s,'refund');s.transactions.at(-1).bankOriginal.amount=30;c.reopenTransactionSource(s,'batch','refund');assert.equal(e.categoryFinancialActuals(s,'2026-08','dion')[0].budgetImpact,300);});
test('U6 ledger count stable after reopen/reapprove',()=>{const s=state();withdrawal(s);csvify(s,'w');const n=s.savingsGoalLedger.length;c.reopenTransactionSource(s,'batch','w');reapprove(s,'w');assert.equal(s.savingsGoalLedger.length,n);});
test('U7 dependency blocks before mutation',()=>{const s=state();add(s,tx('deposit',250,'sparen',{savingsGoalId:'vacation'}));withdrawal(s,'w',1200);csvify(s,'deposit');const before=clone(s);assert.throws(()=>c.reopenTransactionSource(s,'batch','deposit'),/negatief/);assert.deepEqual(s,before);});
function splits(s){const t=tx('source',300,'uitgave',{processing:{transactionType:'uitgave',processedAmount:300,budgetOwner:'dion',category:'Kleding',splits:[{id:'one',amount:100,transactionType:'uitgave',budgetOwner:'dion',category:'Kleding'},{id:'two',amount:200,transactionType:'uitgave',budgetOwner:'dion',category:'Overig'}]}});s.transactions.push(t);return t;}
test('SP1 own split receives coverage',()=>{const s=state();withdrawal(s);splits(s);alloc(s,'a','w','source:split:one',100);assert.equal(project(s,'source:split:one').effects.budgetImpact,0);});
test('SP2 other split unaffected',()=>{const s=state();withdrawal(s);splits(s);alloc(s,'a','w','source:split:one',100);assert.equal(project(s,'source:split:two').effects.budgetImpact,200);});
test('SP3 own refund split corrects category/month',()=>{const s=state();expense(s,'x',100);s.transactions.push(tx('rsource',50,'terugbetaling',{date:'2026-09-01',processing:{transactionType:'terugbetaling',processedAmount:50,splits:[{id:'refundline',transactionType:'terugbetaling',amount:30,category:'Terugbetaling',budgetOwner:'dion',refundCategory:'Kleding',refundMonth:'2026-08'},{id:'other',transactionType:'vergoeding',amount:20,category:'Overig',budgetOwner:'dion'}]}}));assert.equal(e.categoryFinancialActuals(s,'2026-08','dion')[0].budgetImpact,70);assert.equal(e.actualIncomeForMonth(s,'2026-09').amount,20);});
test('SP4 P3 sum validation still exact',()=>{const s=state(),t=splits(s);t.processing.splits[1].amount=199.99;assert.equal(e.validateTransactionProcessing(t).ok,false);});
test('R1 physical context independent of destination',()=>{const s=state();s.budgetDefaultsHistory.gezamenlijk=[{effectiveFrom:'0000-01',rows:[{id:'joint-clothes',post:'Kleding',bedrag:500}]}];add(s,tx('cross',100,'uitgave',{accountContext:'dion',budgetOwner:'gezamenlijk',financialFor:'gezamenlijk'}));assert.equal(project(s,'cross').accountContext,'dion');assert.equal(project(s,'cross').financialFor,'gezamenlijk');});
test('R2 fixed occurrence month intact',()=>{const s=state();s.transactions.push(tx('fixed',105,'vaste-last',{date:'2026-09-01',fixedExpenseId:'hyp',fixedOccurrenceId:'hyp:2026-08-01',fixedOccurrenceMonth:'2026-08'}));assert.equal(e.fixedOccurrenceActuals(s,{id:'hyp:2026-08-01',month:'2026-08',amount:100}).actual,105);assert.equal(project(s,'fixed').calendarMonth,'2026-09');});
test('R3 salary link never moves actual month',()=>{const s=state();add(s,tx('salary',2645,'salaris',{date:'2026-09-01',incomeOccurrenceId:'salary:2026-08-01'}));assert.equal(e.actualIncomeForMonth(s,'2026-08').amount,0);});
test('R4 confirmed internal pair external zero account retained',()=>{const s=state();s.transactions.push(tx('out',500,'interne-overboeking',{approvalSource:'manual',certainty:'goedgekeurd',bankOriginal:{bankDate:'2026-08-12',amount:-500}}),tx('in',500,'interne-overboeking',{approvalSource:'manual',certainty:'goedgekeurd',accountContext:'gezamenlijk',bankOriginal:{bankDate:'2026-08-12',amount:500}}));s.internalTransferPairs.push({id:'pair',transactionIds:['out','in'],status:'voorgesteld'});e.confirmInternalTransferPair(s,'pair');assert.equal(e.sumTransactionEffects(s,'externalHouseholdCashflow'),0);assert.equal(e.sumTransactionEffects(s,'accountCashflow',{account:'dion'}),-500);});
test('R5 explicit replacement still suppresses manual',()=>{const s=state();expense(s,'manual',50);const row={id:'bank',source:'csv',bankOriginal:{bankDate:'2026-08-12',amount:-50,description:'Bank'},processing:{}};e.confirmManualReplacement(s,row,'manual','import');assert.equal(e.sumTransactionEffects(s,'realExpense'),0);assert.equal(row.processingStatus,'nakijken');assert.equal(s.transactions.length,1);});
test('R6 bankOriginal vs processed amount preserved',()=>{const s=state();s.transactions.push(tx('bank',105,'uitgave',{source:'csv',approvalSource:'manual',certainty:'goedgekeurd',bankOriginal:{bankDate:'2026-08-12',amount:-100,rawCells:['keep']}}));const original=clone(s.transactions[0].bankOriginal);assert.equal(project(s,'bank').effects.accountCashflow,-100);assert.equal(project(s,'bank').effects.budgetImpact,105);assert.deepEqual(s.transactions[0].bankOriginal,original);});
test('R7 excluded all effects universally zero',()=>{const s=state();withdrawal(s);s.transactions[0].transactionType='niet-meetellen';assert.ok(Object.values(project(s,'w').effects).every(value=>value===0));});
test('R8 no CSV automatic approval',()=>{const s=state();s.transactions.push(tx('csv',100,'sparen',{source:'csv',processingStatus:'nakijken',certainty:'zeker',savingsGoalId:'vacation'}));assert.equal(project(s,'csv').effects.savingsDeposit,0);});
test('R9 planning histories unchanged',()=>{const s=state(),before=clone({income:s.incomeDefaultsHistory,budget:s.budgetDefaultsHistory,planning:s.planning});withdrawal(s);expense(s);alloc(s,'a','w','x',100);assert.deepEqual({income:s.incomeDefaultsHistory,budget:s.budgetDefaultsHistory,planning:s.planning},before);});
test('R10 read preserves closures and all persistent state',()=>{const s=state();s.monthRecords['2026-07']={status:'afgesloten',closureHistory:[{id:'old',financialSnapshot:{income:999}}]};const before=clone(s);forecast(s);e.categoryFinancialActuals(s,'2026-08');e.coverageAllocationStatus(s);assert.deepEqual(s,before);});

test('Fixed coverage reduces forecast without changing actual',()=>{const s=state();s.recurringFixedExpenses.push({id:'hyp',naam:'Hyp',categorie:'Wonen',bedrag:100,financialFor:'dion',rekening:'dion',begindatum:'2026-01-01',actief:true});withdrawal(s);s.transactions.push(tx('fixed',105,'vaste-last',{fixedExpenseId:'hyp',fixedOccurrenceId:'hyp:2026-08-01',fixedOccurrenceMonth:'2026-08',category:'Wonen'}));alloc(s,'a','w','fixed',100);assert.equal(forecast(s).owners.dion.fixedBurden,5);assert.equal(e.fixedOccurrenceActuals(s,{id:'hyp:2026-08-01',month:'2026-08',amount:100}).actual,105);});
test('Crossmonth fixed coverage rejected',()=>{const s=state();withdrawal(s);s.transactions.push(tx('fixed',100,'vaste-last',{fixedExpenseId:'hyp',fixedOccurrenceId:'hyp:2026-07-01',fixedOccurrenceMonth:'2026-07'}));assert.throws(()=>alloc(s,'a','w','fixed',100),/occurrence-maand/);});
test('Refund overflow and dependent mutation blocked atomically',()=>{const s=state();expense(s,'x',100);const before=clone(s);assert.throws(()=>refund(s,101),/Refunds/);assert.deepEqual(s,before);refund(s,100);csvify(s,'x');const original=clone(s);assert.throws(()=>c.reopenTransactionSource(s,'batch','x'),/Refunds/);assert.deepEqual(s,original);});
test('Same month refund forecast only credited once',()=>{const s=state();expense(s,'x',100);refund(s,30,{date:'2026-08-20'});assert.equal(forecast(s).household.available,2530);assert.equal(e.sumTransactionEffects(s,'budgetImpact',{month:'2026-08'}),70);});
test('Manual salary precedence with explicit zero',()=>{const s=state();s.monthlyIncomeOverrides={'2026-08':{dion:0}};assert.equal(forecast(s).owners.dion.salary,0);add(s,tx('salary',2645,'salaris'));assert.equal(forecast(s).owners.dion.salary,2645);});
test('Subgoal capacity does not cap ledger balance',()=>{const s=state();s.spaardoelen.dion[0].subdoelen=[{id:'child',doelbedrag:100,gespaard:100}];add(s,tx('deposit',250,'sparen',{savingsGoalId:'vacation'}));assert.equal(s.spaardoelen.dion[0].algespaard,1250);assert.equal(s.spaardoelen.dion[0].subdoelen[0].gespaard,100);});
test('Different goals can fund one expense',()=>{const s=state();s.spaardoelen.dion.push({id:'buffer',algespaard:100});s.savingsGoalLedger.push({id:'buffer-open',goalId:'buffer',effectiveAmount:100,source:'legacy-opening'});withdrawal(s,'w1',100);withdrawal(s,'w2',50,{savingsGoalId:'buffer'});expense(s);alloc(s,'a','w1','x',100);alloc(s,'b','w2','x',50);assert.equal(project(s,'x').effects.budgetImpact,150);});
test('Missing split reference retained inactive and overshoot blocked',()=>{const s=state();withdrawal(s);splits(s);alloc(s,'a','w','source:split:one',100);const old=clone(s);s.transactions.find(t=>t.id==='source').processing.splits[0].id='changed';c.assertFinancialMutationSafe(old,s);assert.equal(e.coverageAllocationStatus(s)[0].reason,'coverage-missing-reference');assert.equal(s.savingsCoverageAllocations.length,1);});
test('Legacy missing goal no ledger invention; negative refund no P4 credit',()=>{const s=state();s.transactions.push(tx('legacy-w',500,'van-spaarrekening',{source:'csv',approvalSource:'legacy-confirmed'}),tx('legacy-r',15,'terugbetaling',{source:'csv',approvalSource:'legacy-confirmed',bankOriginal:{bankDate:'2026-08-12',amount:-15}}));const before=clone(s);assert.equal(project(s,'legacy-w').effects.unusedSavings,500);assert.equal(project(s,'legacy-w').effects.goalDelta,0);assert.equal(project(s,'legacy-r').effects.refundCashflow,0);forecast(s);assert.deepEqual(s,before);});
test('P4 JSON roundtrip identical and no clock/random in reads',()=>{const s=state();withdrawal(s);expense(s);alloc(s,'a','w','x',100);assert.deepEqual(forecast(JSON.parse(JSON.stringify(s))),forecast(s));});

test('Explicit savings date change moves ledger month without another entry',()=>{const s=state();add(s,tx('deposit',25,'sparen',{savingsGoalId:'vacation'}));const edited={...s.transactions[0],date:'2026-09-03',transactionDate:'2026-09-03'};c.upsertManualFinancialTransaction(s,edited,'dion');assert.equal(s.savingsGoalLedger.length,2);assert.equal(s.savingsGoalLedger.find(row=>row.transactionId==='deposit').month,'2026-09');assert.equal(d.calculateGoalSavedAmount(s,'vacation'),1025);});
test('Existing editor references survive validated goal correction',()=>{const s=state(),goals=s.spaardoelen.dion,goal=goals[0];c.correctGoalBalance(s,'vacation',1100,{id:'correction-ref'});assert.equal(s.spaardoelen.dion,goals);assert.equal(s.spaardoelen.dion[0],goal);assert.equal(goal.algespaard,1100);});
test('Raw P3 processing split uses the same ledger identity and disables with parent',()=>{const s=state(),empty=clone(s);s.transactions.push(tx('source',100,'uitgave',{splits:[{id:'save',amount:50,transactionType:'sparen',category:'Sparen',budgetOwner:'dion',savingsGoalId:'vacation'},{id:'expense',amount:50,transactionType:'uitgave',category:'Kleding',budgetOwner:'dion'}]}));c.synchronizeChangedSavings(s,empty);assert.equal(d.calculateGoalSavedAmount(s,'vacation'),1050);assert.equal(e.sumTransactionEffects(s,'budgetImpact'),50);const before=clone(s);s.transactions[0].processing={include:false};s.transactions[0].processingStatus='niet-meetellen';c.synchronizeChangedSavings(s,before);assert.equal(d.calculateGoalSavedAmount(s,'vacation'),1000);assert.equal(s.savingsGoalLedger.length,2);});
test('Grandfathered joint salary assignment is forecasted exactly once',()=>{const s=state();s.transactions.push({id:'old-salary',date:'2026-08-25',amount:2645,owner:'gezamenlijk',financialFor:'gezamenlijk',kind:'inkomen',transactionType:'salaris',reviewStatus:'bevestigd',approvalSource:'legacy-confirmed'});assert.equal(e.financialForecastForMonth(s,'2026-08').household.income,2645);assert.equal(e.actualIncomeForMonth(s,'2026-08').amount,2645);});

test('Processing split cannot override immutable physical source or approval',()=>{const s=state(),t=tx('source',150,'uitgave',{splits:[{id:'first',amount:100,transactionType:'uitgave',category:'Kleding',budgetOwner:'dion',accountContext:'dara',bankOriginal:{amount:999,bankDate:'2027-01-01'},date:'2027-01-01'},{id:'second',amount:50,transactionType:'uitgave',category:'Kleding',budgetOwner:'dara'}]});s.transactions.push(t);const rows=e.selectTransactionProjections(s);assert.deepEqual(rows.map(p=>p.accountContext),['dion','dion']);assert.deepEqual(rows.map(p=>p.calendarMonth),['2026-08','2026-08']);assert.equal(e.sumTransactionEffects(s,'accountCashflow'),-150);assert.equal(t.bankOriginal,undefined);});

for(const ordinary of [0,40])test(`mixed-category refund stays separate from variable usage (${ordinary})`,()=>{const s=state();s.transactions.push(tx('fixed',100,'vaste-last',{fixedExpenseId:'gym',fixedOccurrenceId:'gym:2026-08-01',fixedOccurrenceMonth:'2026-08'}));if(ordinary)expense(s,'ordinary',ordinary);refund(s,30);const p=project(s,'refund');assert.equal(p.effects.refundCorrection,30);assert.equal(p.effects.categoryOnlyRefundCorrection,30);assert.equal(p.effects.budgetImpact,0);assert.equal(Object.values(e.categoryActuals(s,'2026-08','dion')).reduce((sum,amount)=>sum+amount,0),ordinary);const combined=e.categoryFinancialActuals(s,'2026-08','dion')[0];assert.equal(combined.budgetImpact,100+ordinary-30);assert.equal(combined.categoryOnlyRefundCorrection,30);assert.equal(e.fixedOccurrenceActuals(s,{id:'gym:2026-08-01',month:'2026-08',amount:100}).actual,100);});

test('Refund split validation follows its own financial destination',()=>{const owners=[],t=tx('r',30,'terugbetaling',{bankOriginal:{bankDate:'2026-09-01',amount:30},processing:{processedAmount:30,transactionType:'terugbetaling',budgetOwner:'dion',splits:[{id:'dara-refund',amount:30,transactionType:'terugbetaling',financialFor:'dara',category:'Terugbetaling',refundCategory:'Kleding',refundMonth:'2026-08'}]}});const result=e.validateTransactionProcessing(t,{refundCategoryExists:(category,month,owner)=>{owners.push(owner);return owner==='dara';}});assert.equal(result.ok,true);assert.deepEqual(owners,['dara']);});
