const {test}=require('node:test'),assert=require('node:assert/strict');
const u=require('../src/import/update4-runtime.cjs'),e=require('../src/core/transaction-engine.mjs');
const copy=v=>JSON.parse(JSON.stringify(v));
function fixture(){
 const state={transactions:[],accountProfiles:[{id:'dion',accountOwner:'dion'}],recurringFixedExpenses:[],importSummaries:[],savingsGoalLedger:[],spaardoelen:{dion:[{id:'goal',algespaard:0}],dara:[],gezamenlijk:[]},advanceLedger:[],advanceRepayments:[],manualTransactionReplacements:[],internalTransferPairs:[],monthRecords:{}};
 const row={id:'row',certainty:'nakijken',recognitionState:'known',bankOriginal:{valid:true,bankDate:'2026-10-01',amount:-100,description:'Original',rawCells:['unchanged']},processing:{processingDate:'2026-12-01',processedAmount:100,description:'Processing',transactionType:'sparen',category:'Sparen',savingsGoalId:'goal',budgetOwner:'dion',include:true,splits:[],advanceMode:'none'}};
 const draft={id:'batch',status:'concept',accountProfileId:'dion',accountOwner:'dion',rows:[row],summary:{}};
 u.markExplicitlyApproved(row);u.updateDraftSummary(draft);state.importSummaries.push(u.compactSummary(draft));
 const plan=u.planImportEffects(draft,state);assert.equal(plan.ok,true);u.applyImportPlan(state,plan);draft.status='verwerkt';draft.effectManifest=u.effectManifest(plan);
 return {state,row,draft,root:{state,commitChange:fn=>{fn();return true;}}};
}
function memoryStore(){const imports=new Map(),journal=new Map(),original={};for(const key of ['putImport','getImport','putJournal','listJournal','putSync','listSync','deleteSync','deleteImport','rollbackImport'])original[key]=u.ImportStore[key];Object.assign(u.ImportStore,{putImport:async record=>imports.set(record.id,copy(record)),getImport:async id=>copy(imports.get(id)),putJournal:async record=>journal.set(record.id,copy(record)),listJournal:async()=>[...journal.values()].map(copy),putSync:async()=>{},listSync:async()=>[],deleteSync:async()=>{},deleteImport:async id=>imports.delete(id),rollbackImport:async(expected,previous)=>{if(previous)imports.set(expected.id,copy(previous));else imports.delete(expected.id);}});return {imports,journal,restore:()=>Object.assign(u.ImportStore,original)};}
test('Source reopen/reapproval behoudt ledgerhistorie en andere bron',async()=>{const mem=memoryStore();try{const {state,row,draft,root}=fixture();state.transactions.push({id:'other',source:'manual',accountContext:'dara',owner:'dara',date:'2026-10-01',amount:20,kind:'uitgave'});const original=copy(row.bankOriginal);await u.ImportStore.putImport(draft);assert.equal(state.spaardoelen.dion[0].algespaard,100);await u.reopenStoredSource(root,draft,row);assert.equal(state.spaardoelen.dion[0].algespaard,0);assert.equal(state.savingsGoalLedger.length,1);row.processing.processedAmount=105;u.markExplicitlyApproved(row);await u.approveStoredSource(root,draft,row);assert.equal(state.spaardoelen.dion[0].algespaard,105);assert.equal(state.savingsGoalLedger.length,1);assert.equal(state.savingsGoalLedger[0].processingHistory[0].actualAmount,100);assert.equal(state.transactions.find(tx=>tx.id==='other').amount,20);assert.deepEqual(row.bankOriginal,original);assert.equal(state.transactions[0].date,'2026-10-01');assert.equal(e.sumTransactionEffects(state,'accountCashflow',{account:'dion'}),-100);}finally{mem.restore();}});
test('Afgekeurde corecommit laat source en ledger exact intact',async()=>{const mem=memoryStore();try{const {state,row,draft,root}=fixture();const before=structuredClone(state);root.commitChange=()=>false;await assert.rejects(u.reopenStoredSource(root,draft,row));assert.deepEqual(state,before);assert.equal(row.certainty,'goedgekeurd');}finally{mem.restore();}});
test('Journal-opslagfout blokkeert financiele heropening',async()=>{const mem=memoryStore();try{const {state,row,draft,root}=fixture(),before=structuredClone(state);u.ImportStore.putJournal=async()=>{throw new Error('journal unavailable');};await assert.rejects(u.reopenStoredSource(root,draft,row));assert.deepEqual(state,before);}finally{mem.restore();}});
test('Abrupt onderbroken details-write na goedkeuring herstelt via pending journal',async()=>{const mem=memoryStore();try{const {state,row,draft,root}=fixture();await u.ImportStore.putImport(draft);await u.reopenStoredSource(root,draft,row);row.processing.processedAmount=120;u.markExplicitlyApproved(row);const write=u.ImportStore.putImport;u.ImportStore.putImport=async()=>{throw new Error('disk unavailable');};await assert.rejects(u.approveStoredSource(root,draft,row),/disk unavailable/);assert.equal(state.spaardoelen.dion[0].algespaard,0);/* Simulated process termination: rollback has not marked the durable receipt. */for(const entry of mem.journal.values())if(entry.operation==='import-command'&&entry.intent.type==='source-approve')entry.status='pending';u.ImportStore.putImport=write;await u.recoverJournal(root);const stored=await u.ImportStore.getImport(draft.id);assert.equal(stored.rows[0].certainty,'goedgekeurd');assert.equal(stored.rows[0].processing.processedAmount,120);assert.equal([...mem.journal.values()].find(entry=>entry.operation==='import-command'&&entry.intent.type==='source-approve').status,'completed');assert.equal(state.savingsGoalLedger.length,1);}finally{mem.restore();}});
test('Fixed parent en split approval vereisen geldige occurrence',()=>{const {state,row}=fixture();row.processing={...row.processing,transactionType:'vaste-last',fixedExpenseId:'missing',fixedOccurrenceId:'missing:2026-10-01'};assert.equal(u.rowProcessingValidation(row,state).ok,false);});

test('Wijziging tijdens journal-write activeert geen verouderd voorstel',async()=>{const mem=memoryStore();try{const {state,row,draft,root}=fixture();await u.ImportStore.putImport(draft);await u.reopenStoredSource(root,draft,row);u.markExplicitlyApproved(row);const write=u.ImportStore.putJournal;u.ImportStore.putJournal=async entry=>{await write(entry);if(entry.operation==='import-command'&&entry.intent.type==='source-approve'&&entry.status==='pending'){row.certainty='nakijken';row.approvalSource='';row.processingStatus='nakijken';}};await assert.rejects(u.approveStoredSource(root,draft,row),/intussen gewijzigd/);assert.equal(state.spaardoelen.dion[0].algespaard,0);assert.equal(e.sumTransactionEffects(state,'savingsEffect'),0);}finally{mem.restore();}});
test('Possible manualMatch zonder bevestigingsrecord wordt niet vervangen',()=>{const {state,row,draft}=fixture();state.transactions=[];state.transactions.push({id:'manual',source:'manual',amount:100,date:'2026-10-01',accountContext:'dion',owner:'dion',kind:'uitgave'});row.processing.manualMatchId='manual';const plan=u.planImportEffects(draft,state);assert.equal(plan.ok,true);assert.equal(plan.replacements.length,0);});
