const {test}=require('node:test'),assert=require('node:assert/strict');
const e=require('../src/core/transaction-engine.mjs'),c=require('../src/core/transaction-processing.mjs'),p=require('../src/core/planning-timeline.mjs');
const clone=x=>JSON.parse(JSON.stringify(x)),month='2026-10';
function state(budget=500,saving=0){return {meta:{schemaVersion:11},planning:{verdeling:{minimumDion:.4},spaarpotDezeMaand:saving},budgetDefaultsHistory:{gezamenlijk:[{effectiveFrom:'0000-01',rows:[{id:'food',post:'Boodschappen',bedrag:budget}]}],dion:[],dara:[]},incomeDefaultsHistory:{dion:[{effectiveFrom:'0000-01',salary:3000}],dara:[{effectiveFrom:'0000-01',salary:2000}]},transactions:[],recurringFixedExpenses:[],spaardoelen:{gezamenlijk:[{id:'buffer-goal',naam:'Buffer',algespaard:2000}],dion:[],dara:[]},savingsGoalLedger:[{id:'opening',goalId:'buffer-goal',effectiveAmount:2000,source:'legacy-opening',active:true}],savingsCoverageAllocations:[],monthlySavingOverrides:{},monthRecords:{},accountProfiles:[],internalTransferPairs:[],manualTransactionReplacements:[]};}
function tx(s,id,amount,type='uitgave',extra={}){const row={id,source:'manual',accountContext:'gezamenlijk',financialFor:'gezamenlijk',budgetOwner:'gezamenlijk',owner:'gezamenlijk',date:month+'-05',amount,category:'Boodschappen',transactionType:type,processingStatus:'goedgekeurd',...extra};c.upsertManualFinancialTransaction(s,row,row.accountContext,{today:'2026-10-31'});return s.transactions.find(t=>t.id===id);}
const f=s=>e.financialForecastForMonth(s,month),allowance=s=>{const v=f(s);return [v.owners.dion.allowance,v.owners.dara.allowance];},reserve=s=>f(s).allowanceBasis.owners.gezamenlijk;
function savings(s,id,amount,type='naar-spaarrekening'){return tx(s,id,amount,type,{category:'Sparen',savingsGoalId:'buffer-goal'});}
function cover(s,w,x,amount){c.setSavingsCoverageAllocation(s,{id:'coverage',withdrawalTransactionId:w,expenseTransactionId:x,amountCents:amount*100});}
test('Z1 budget500 actual0 reserves500',()=>{const s=state();assert.equal(reserve(s).budgetReserve,500);assert.deepEqual(allowance(s),[2700,1800]);assert.equal(f(s).owners.gezamenlijk.available,500);});
test('Z2 budget500 actual300 still reserves500',()=>{const s=state(),before=allowance(s);tx(s,'expense',300);assert.equal(reserve(s).budgetReserve,500);assert.deepEqual(allowance(s),before);assert.equal(f(s).owners.gezamenlijk.available,200);});
test('Z3 budget500 month end400 leaves100 buffer not allowance',()=>{const s=state(),before=allowance(s);tx(s,'expense',400,'uitgave',{date:month+'-31'});assert.deepEqual(allowance(s),before);assert.equal(f(s).owners.gezamenlijk.available,100);});
test('Z4 planned savings250 no transaction reserves250',()=>{const s=state(0,250);assert.equal(reserve(s).savingsReserve,250);assert.deepEqual(allowance(s),[2850,1900]);assert.equal(e.sumTransactionEffects(s,'savingsDeposit'),0);});
test('Z5 planned250 actualdeposit250 not double',()=>{const s=state(0,250),before=allowance(s);savings(s,'deposit',250);assert.deepEqual(allowance(s),before);assert.equal(reserve(s).totalReserve,250);assert.equal(f(s).owners.gezamenlijk.available,0);});
test('Z6 unexecuted savings250 remains reserved',()=>{const s=state(0,250);assert.equal(f(s).owners.gezamenlijk.available,250);assert.equal(reserve(s).savingsReserve,250);assert.deepEqual(allowance(s),[2850,1900]);});
test('Z7 refund actual150 does not release budget300',()=>{const s=state(300),before=allowance(s);tx(s,'expense',200);tx(s,'refund',50,'terugbetaling',{refundCategory:'Boodschappen',refundMonth:month});assert.equal(e.sumTransactionEffects(s,'budgetImpact',{month}),150);assert.equal(reserve(s).budgetReserve,300);assert.deepEqual(allowance(s),before);assert.equal(f(s).owners.gezamenlijk.available,150);});
test('Z8 coverage actual100 does not release budget300',()=>{const s=state(300),before=allowance(s);tx(s,'expense',200);savings(s,'withdrawal',100,'van-spaarrekening');cover(s,'withdrawal','expense',100);assert.equal(e.sumTransactionEffects(s,'budgetImpact',{month}),100);assert.equal(reserve(s).budgetReserve,300);assert.deepEqual(allowance(s),before);});
test('Z9 actual salary precedence with full budget/saving reserve',()=>{const s=state(500,250);tx(s,'salary',3100,'salaris',{accountContext:'dion',financialFor:'dion',budgetOwner:'dion',owner:'dion',category:'Salaris'});const result=f(s);assert.equal(result.owners.dion.salary,3100);assert.equal(result.household.actualIncome,3100);assert.equal(reserve(s).totalReserve,750);assert.equal(result.distributable,4350);assert.equal(s.incomeDefaultsHistory.dion[0].salary,3000);});
test('Z10 explicit zero salary remains valid',()=>{const s=state(500,250);s.monthlyIncomeOverrides={[month]:{dion:0}};assert.equal(f(s).owners.dion.salary,0);assert.equal(f(s).distributable,1250);assert.equal(reserve(s).totalReserve,750);});
test('Z11 historical budget and month savings plan stable',()=>{const s=state(500,50);p.setBudgetForMonth(s,'gezamenlijk',month,[{id:'food',post:'Boodschappen',bedrag:550}]);s.monthlySavingOverrides[month]={gezamenlijk:250};const sep=e.financialForecastForMonth(s,'2026-09'),oct=f(s);assert.equal(sep.allowanceBasis.owners.gezamenlijk.budgetReserve,500);assert.equal(sep.allowanceBasis.owners.gezamenlijk.savingsReserve,50);assert.equal(oct.allowanceBasis.owners.gezamenlijk.budgetReserve,550);assert.equal(oct.allowanceBasis.owners.gezamenlijk.savingsReserve,250);});
test('Z12 financial actuals and persistent state unchanged by planning read',()=>{const s=state(300,250);tx(s,'expense',200);savings(s,'withdrawal',100,'van-spaarrekening');cover(s,'withdrawal','expense',100);tx(s,'refund',50,'terugbetaling',{refundCategory:'Boodschappen',refundMonth:month});const before=clone(s),effects=e.selectTransactionProjections(s),income=e.actualIncomeForMonth(s,month),cats=e.categoryFinancialActuals(s,month);f(s);assert.deepEqual(s,before);assert.deepEqual(e.selectTransactionProjections(s),effects);assert.deepEqual(e.actualIncomeForMonth(s,month),income);assert.deepEqual(e.categoryFinancialActuals(s,month),cats);});
test('Z13 realization of savings even beyond plan never changes allowance',()=>{const s=state(0,250),before=allowance(s);savings(s,'deposit',300);assert.deepEqual(allowance(s),before);assert.equal(reserve(s).savingsReserve,250);assert.equal(f(s).owners.gezamenlijk.available,-50);});
test('Z14 fixed plan100 actual105 only buffer changes',()=>{const s=state(0);s.recurringFixedExpenses=[{id:'rent',naam:'Rent',categorie:'Wonen',bedrag:100,financialFor:'gezamenlijk',rekening:'gezamenlijk',begindatum:'2026-01-01',actief:true}];const before=allowance(s);tx(s,'fixed',105,'vaste-last',{category:'Wonen',fixedExpenseId:'rent',fixedOccurrenceId:'rent:2026-10-01',fixedOccurrenceMonth:month});assert.deepEqual(allowance(s),before);assert.equal(reserve(s).fixedReserve,100);assert.equal(f(s).owners.gezamenlijk.fixedBurden,105);assert.equal(f(s).owners.gezamenlijk.available,-5);assert.equal(e.fixedOccurrenceActuals(s,{id:'rent:2026-10-01',month,amount:100}).deviation,5);});
test('Z15 unused withdrawal remains actual available not allowance redistribution',()=>{const s=state(0),before=allowance(s);savings(s,'withdrawal',500,'van-spaarrekening');tx(s,'expense',350);cover(s,'withdrawal','expense',350);assert.deepEqual(allowance(s),before);assert.equal(f(s).household.unusedSavings,150);assert.equal(f(s).household.available,5150);assert.equal(f(s).owners.gezamenlijk.available,150);});
test('Budget overspend is buffer shortfall, no allowance reduction',()=>{const s=state(500),before=allowance(s);tx(s,'expense',700);assert.deepEqual(allowance(s),before);assert.equal(reserve(s).budgetReserve,500);assert.equal(f(s).owners.gezamenlijk.available,-200);});
test('Only variable planning reserved; fixed category summary not reserved twice',()=>{const s=state(500);s.recurringFixedExpenses=[{id:'fixed',naam:'Fixed',categorie:'Boodschappen',bedrag:100,financialFor:'gezamenlijk',rekening:'gezamenlijk',begindatum:'2026-01-01',actief:true}];assert.equal(reserve(s).totalReserve,600);assert.equal(f(s).distributable,4400);});
test('Personal savings override stays within own allowance; month zero honored',()=>{const s=state(500,250),before=allowance(s);s.monthlySavingOverrides[month]={dion:250,dara:0,gezamenlijk:250};assert.deepEqual(allowance(s),before);assert.equal(f(s).allowanceBasis.owners.dion.savingsReserve,250);assert.equal(f(s).allowanceBasis.owners.dara.savingsReserve,0);});
