const {test}=require('node:test'),assert=require('node:assert/strict');
const u=require('../src/import/update4-runtime.cjs'),c=require('../src/core/transaction-processing.mjs'),e=require('../src/core/transaction-engine.mjs'),d=require('../src/core/data-normalization.mjs');
const copy=v=>JSON.parse(JSON.stringify(v));
function state(){return {meta:{schemaVersion:11},accountProfiles:[{id:'joint',accountOwner:'gezamenlijk'}],transactions:[],recurringFixedExpenses:[],spaardoelen:{gezamenlijk:[{id:'vacation',naam:'Vakantie',algespaard:1000}],dion:[],dara:[]},savingsGoalLedger:[{id:'opening',goalId:'vacation',source:'legacy-opening',effectiveAmount:1000,active:true}],advanceLedger:[],advanceRepayments:[],internalTransferPairs:[],manualTransactionReplacements:[],monthRecords:{},importSummaries:[],incomeDefaultsHistory:{dion:[],dara:[]},budgetDefaultsHistory:{gezamenlijk:[{effectiveFrom:'0000-01',rows:[{post:'Kleding',bedrag:500}]}]}};}
function row(id,type,amount,processing={}){const r={id,bankOriginal:{valid:true,bankDate:'2026-10-03',amount,description:id,rawCells:['bank',amount]},certainty:'nakijken',recognitionState:'known',processing:{transactionType:type,processingDate:'2026-10-03',processedAmount:Math.abs(amount),category:'Kleding',budgetOwner:'gezamenlijk',advanceMode:'none',fixedAmountMode:'none',include:true,splits:[],...processing}};u.markExplicitlyApproved(r);return r;}
function apply(s,rows,id='batch'){const draft={id,status:'concept',accountProfileId:'joint',accountOwner:'gezamenlijk',rows,summary:{}};u.updateDraftSummary(draft);s.importSummaries.push(u.compactSummary(draft));const plan=u.planImportEffects(draft,s);assert.equal(plan.ok,true);u.applyImportPlan(s,plan);draft.effectManifest=u.effectManifest(plan);draft.status='verwerkt';return {draft,plan};}
function memory(){const original={},journal=[];for(const key of ['putImport','getImport','putJournal','putSync','listSync','deleteSync','rollbackImport'])original[key]=u.ImportStore[key];Object.assign(u.ImportStore,{putImport:async()=>{},getImport:async()=>null,putJournal:async entry=>journal.push(copy(entry)),putSync:async()=>{},listSync:async()=>[],deleteSync:async()=>{},rollbackImport:async()=>{}});return {journal,restore:()=>Object.assign(u.ImportStore,original)};}
function coverage(s){const rows=e.selectTransactionProjections(s),w=rows.find(p=>p.transactionType==='van-spaarrekening'),x=rows.find(p=>p.effects.realExpense);c.setSavingsCoverageAllocation(s,{id:'allocation',withdrawalTransactionId:w.id,withdrawalSourceKey:w.sourceKey,expenseTransactionId:x.id,expenseSourceKey:x.sourceKey,amountCents:20000});}
test('P4 source reopen of deposit cannot make spent goal negative before journal',async()=>{const mem=memory();try{const s=state();s.savingsGoalLedger[0].effectiveAmount=0;s.spaardoelen.gezamenlijk[0].algespaard=0;const dep=row('deposit','sparen',-100,{savingsGoalId:'vacation'}),out=row('withdraw','van-spaarrekening',100,{savingsGoalId:'vacation'}),{draft}=apply(s,[dep,out]),before=copy(s);await assert.rejects(u.reopenStoredSource({state:s,commitChange:fn=>{fn();return true;}},draft,dep),/negatief/);assert.deepEqual(s,before);assert.equal(mem.journal.length,0);}finally{mem.restore();}});
test('P4 reapproval withdrawal beyond goal balance blocks before journal',async()=>{const mem=memory();try{const s=state(),out=row('withdraw','van-spaarrekening',500,{savingsGoalId:'vacation'}),{draft}=apply(s,[out]),root={state:s,commitChange:fn=>{fn();return true;}};await u.reopenStoredSource(root,draft,out);out.processing.processedAmount=1500;u.markExplicitlyApproved(out);const before=copy(s),count=mem.journal.length;await assert.rejects(u.approveStoredSource(root,draft,out),/negatief/);assert.deepEqual(s,before);assert.equal(mem.journal.length,count);}finally{mem.restore();}});
test('P4 shrinking expense under retained coverage blocks source approval atomically',async()=>{const mem=memory();try{const s=state(),out=row('withdraw','van-spaarrekening',500,{savingsGoalId:'vacation'}),x=row('expense','uitgave',-300),{draft}=apply(s,[out,x]),root={state:s,commitChange:fn=>{fn();return true;}};coverage(s);await u.reopenStoredSource(root,draft,x);x.processing.processedAmount=100;u.markExplicitlyApproved(x);const before=copy(s),count=mem.journal.length;await assert.rejects(u.approveStoredSource(root,draft,x),/uitgave/);assert.deepEqual(s,before);assert.equal(mem.journal.length,count);}finally{mem.restore();}});
test('P4 incoming refund above remaining category after coverage preserves negative usage',()=>{const s=state();apply(s,[row('withdraw','van-spaarrekening',500,{savingsGoalId:'vacation'}),row('expense','uitgave',-300)]);coverage(s);const refund=row('refund','terugbetaling',150,{refundCategory:'Kleding',refundMonth:'2026-10'}),draft={id:'refund-batch',accountProfileId:'joint',rows:[refund],summary:{}};u.updateDraftSummary(draft);const plan=u.planImportEffects(draft,s);assert.equal(plan.ok,true);u.applyImportPlan(s,plan);assert.equal(e.categoryFinancialActuals(s,'2026-10','gezamenlijk')[0].budgetImpact,-50);assert.equal(e.sumTransactionEffects(s,'incomeImpact'),0);});
test('P4 existing undo retains ledger and allocation audit without repeated history',()=>{const s=state(),{draft}=apply(s,[row('withdraw','van-spaarrekening',500,{savingsGoalId:'vacation'}),row('expense','uitgave',-300)]);coverage(s);u.undoImportEffects(s,draft);assert.equal(d.calculateGoalSavedAmount(s,'vacation'),1000);assert.equal(s.savingsGoalLedger.length,2);assert.equal(s.savingsCoverageAllocations.length,1);assert.equal(e.coverageAllocationStatus(s)[0].active,false);const once=copy(s);u.undoImportEffects(s,draft);assert.deepEqual(s,once);});
