const assert=require('node:assert/strict');
const {setBudgetForMonth,resolveVariableBudgetsForMonth}=require('../src/core/planning-timeline.mjs');
const state={planning:{},budgetDefaultsHistory:{dion:[{id:'initial',effectiveFrom:'0000-01',rows:[{id:'base',post:'Overig',bedrag:100}]}]},monthlyBudgets:{'2026-08':{dionVariabel:[{id:'future',bedrag:175}]}}};
setBudgetForMonth(state,'dion','2026-07',[{id:'new',post:'Overig',bedrag:150}]);
assert.equal(resolveVariableBudgetsForMonth(state,'2026-06','dion')[0].bedrag,100);
assert.equal(resolveVariableBudgetsForMonth(state,'2026-07','dion')[0].bedrag,150);
assert.equal(resolveVariableBudgetsForMonth(state,'2026-08','dion')[0].bedrag,175,'Latere expliciete uitzondering blijft behouden');
assert.equal(resolveVariableBudgetsForMonth(state,'2027-01','dion')[0].bedrag,150);
setBudgetForMonth(state,'dion','2026-07',[{id:'once',post:'Overig',bedrag:160}],{scope:'once'});
assert.equal(resolveVariableBudgetsForMonth(state,'2026-07','dion')[0].bedrag,160);
assert.equal(resolveVariableBudgetsForMonth(state,'2026-09','dion')[0].bedrag,150);
console.log('UPDATE5_BUDGET_HISTORY_SAVING_OVERRIDES_OK');
