const {test}=require('node:test'),assert=require('node:assert/strict');
const u=require('../src/import/update4-runtime.cjs'),e=require('../src/core/transaction-engine.mjs'),c=require('../src/core/transaction-processing.mjs');
const b=require('../src/core/bank-sources.mjs'),d=require('../src/core/processing-lines.mjs'),repair=require('../src/import/source-repair.mjs'),sync=require('../src/import/import-sync-protocol.mjs');
const {state,row,materialize,memory,copy}=require('./helpers/package5-fixture.cjs');
const total=s=>b.selectBankTransactions(s).reduce((sum,t)=>sum+t.bankAmount,0);
const effects=s=>e.selectTransactionProjections(s).map(p=>({id:p.id,effects:p.effects}));
const coreRows=s=>s.transactions.filter(t=>!b.isBankSource(t));
function processing(total=100){return row('source','uitgave',-total).processing;}
function two(p){return d.addProcessingSplit(p,'a','b');}
function command(s,batch,type){return u.planImportCommand(s,batch,{type,operationId:batch.id+'-'+type,timestamp:'2026-10-06T10:00:00Z'},{validateRow:u.rowProcessingValidation});}
function overlap(s,A,id='B'){
 const B={...copy(A),id,version:1,operationId:id+'-initial',rows:A.rows.map((r,i)=>({...copy(r),id:id+i,duplicate:true,duplicateSource:{batchId:A.id,rowId:r.id}}))};
 s.importSummaries.push(u.compactSummary(B));b.ensureImportBankSources(s,B);return B;
}
async function editor(id='edit',sources=[row('r')]){
 const mem=memory(),s=state(),batch=materialize(s,sources,id);mem.imports.set(id,copy(batch));const root={state:s,commitChange:fn=>{fn();return true;}};
 return {mem,s,batch,root,draft:await u.beginImportEditor(root,batch)};
}
test('V113 01 eerste splitsactie bewaart categorie en maakt twee automatische regels',()=>{const p=two(processing());assert.deepEqual(p.splits.map(l=>[l.id,l.category,l.amount,l.amountMode]),[['a','Kleding',50,'auto'],['b','Kleding',50,'auto']]);});
test('V113 02 handmatig bedrag bepaalt resterende automatische ruimte',()=>{const p=two(processing());Object.assign(p.splits[0],{amount:25,amountMode:'manual'});d.redistributeProcessing(p);assert.deepEqual(p.splits.map(l=>l.amount),[25,75]);});
test('V113 03 derde regel behoudt handmatig bedrag',()=>{const p=two(processing());Object.assign(p.splits[0],{amount:25,amountMode:'manual'});d.addProcessingSplit(p,'c');assert.deepEqual(p.splits.map(l=>l.amount),[25,37.5,37.5]);});
test('V113 04 afrondingscenten zijn deterministisch en exact',()=>{assert.deepEqual(d.distributeProcessingCents(10001,[{id:'a',amountMode:'auto'},{id:'b',amountMode:'auto'},{id:'c',amountMode:'auto'}]).map(l=>l.amount),[33.34,33.34,33.33]);});
test('V113 05 oude splits zonder metadata worden nooit herverdeeld',()=>{assert.deepEqual(d.distributeProcessingCents(10000,[{id:'a',amount:25},{id:'b',amount:75}]).map(l=>l.amount),[25,75]);});
test('V113 06 alle bestaande regels handmatig: nieuwe regel start op nul',()=>{const p=processing();p.splits=[{id:'a',amount:20},{id:'b',amount:30}];d.addProcessingSplit(p,'c');assert.deepEqual(p.splits.map(l=>l.amount),[20,30,0]);});
for(const [amount,difference]of [[90,10],[110,-10]])test(`V113 07 totaal ${amount} blokkeert met concreet verschil`,()=>{const r=row('bad');r.processing.processedAmount=100;r.processing.splits=[{...processing(),id:'a',amount}];const result=u.rowProcessingValidation(r,state());assert.equal(result.ok,false);assert.equal(result.errors.find(x=>x.code==='splits').differenceCents,difference*100);});
test('V113 08 verwijderen handmatige regel verhoogt andere handmatige regels niet',()=>{const p=processing();p.splits=[{id:'a',amount:25},{id:'b',amount:35},{id:'c',amount:40}];d.removeProcessingSplit(p,0);assert.deepEqual(p.splits.map(l=>l.amount),[35,40]);});
test('V113 09 één resterende regel behoudt bedrag categorie ID en totaalreferentie',()=>{const p=processing();p.splits=[{id:'a',amount:25,category:'Kleding'},{id:'b',amount:75}];d.removeProcessingSplit(p,1);assert.equal(p.splits.length,0);assert.equal(p.singleLineAmount,25);assert.equal(p.singleLineId,'a');assert.equal(p.processedAmount,100);assert.equal(p.category,'Kleding');assert.equal(d.splitDifference(p).differenceCents,7500);});
test('V113 10 één resterende ongeldige regel kan niet goedgekeurd worden',()=>{const r=row('one','uitgave',-100);r.processing.singleLineAmount=25;assert.equal(u.rowProcessingValidation(r,state()).ok,false);});
test('V113 11 eerste splitsactie behoudt vaste last uitsluitend op eerste regel',()=>{const p=processing();Object.assign(p,{transactionType:'vaste-last',fixedExpenseId:'fixed',fixedOccurrenceId:'occ',category:'Vaste lasten'});two(p);assert.equal(p.splits[0].fixedExpenseId,'fixed');assert.equal(p.splits[0].fixedOccurrenceId,'occ');assert.equal(p.splits[1].fixedExpenseId,'');});
test('V113 12 hoofdtypewissel behoudt bedragen vastzettingen en IDs',()=>{const r=row('family');two(r.processing);r.processing.splits[0].amountMode='manual';const before=r.processing.splits.map(l=>[l.id,l.amount,l.amountMode]);u.applyTransactionFamily(r,'terugbetaling');assert.deepEqual(r.processing.splits.map(l=>[l.id,l.amount,l.amountMode]),before);assert.ok(r.processing.splits.every(l=>l.transactionType==='terugbetaling'));});
test('V113 13 verschillende hoofdtypen per split worden afgewezen',()=>{const r=row('mixed');r.processing.editorVersion=113;r.processing.splits=[{...processing(),id:'x',amount:300,transactionType:'salaris'}];assert.equal(u.rowProcessingValidation(r,state()).errors.some(x=>x.code==='split-family'),true);});
function fixedState(){const s=state();s.recurringFixedExpenses=['fixed-a','fixed-b'].map(id=>({id,naam:id,categorie:'Wonen',bedrag:100,financialFor:'gezamenlijk',rekening:'gezamenlijk',begindatum:'2026-01-01',actief:true,frequentieAantal:1,frequentieEenheid:'maanden',amountHistory:[{effectiveFrom:'2026-01-01',amount:100}]}));return s;}
test('V113 14 budget vaste last en gedeeltelijk niet meetellen: één bankafschrijving',()=>{const s=fixedState(),r=row('mixed','uitgave',-300);r.processing.editorVersion=113;r.processing.splits=[{id:'budget',transactionType:'uitgave',amount:150,budgetOwner:'gezamenlijk',category:'Kleding'},{id:'fixed',transactionType:'vaste-last',amount:100,budgetOwner:'gezamenlijk',category:'Vaste lasten',fixedExpenseId:'fixed-a'},{id:'excluded',transactionType:'niet-meetellen',amount:50,budgetOwner:'gezamenlijk',include:false}];u.selectFixedOccurrence({state:s},r,r.processing.splits[1]);materialize(s,[r]);assert.equal(total(s),-300);assert.equal(b.selectBankTransactions(s).length,1);assert.equal(e.sumTransactionEffects(s,'budgetImpact'),150);assert.equal(e.sumTransactionEffects(s,'fixedRealization'),100);});
test('V113 15 één transactie betaalt meerdere vaste lasten met eigen afwijking',()=>{const s=fixedState(),r=row('fixed','uitgave',-180);r.processing.splits=s.recurringFixedExpenses.map((f,i)=>({id:'f'+i,amount:i?80:100,transactionType:'vaste-last',category:'Vaste lasten',budgetOwner:'gezamenlijk',fixedExpenseId:f.id}));r.processing.splits.forEach(l=>u.selectFixedOccurrence({state:s},r,l));materialize(s,[r]);for(const [i,l]of r.processing.splits.entries()){const actual=e.fixedOccurrenceActuals(s,{id:l.fixedOccurrenceId,month:'2026-10',amount:100});assert.equal(actual.paid,true);assert.equal(actual.actual,i?80:100);}assert.equal(total(s),-180);});
function withdrawal(s,amount=500,direct=300){const r=row('withdraw','van-spaarrekening',amount,{savingsGoalId:'goal',editorVersion:113});r.processing.splits=[{id:'direct',amount:direct,transactionType:'van-spaarrekening',withdrawalBudgetCategory:'Kleding',budgetOwner:'gezamenlijk'},{id:'free',amount:amount-direct,transactionType:'van-spaarrekening',budgetOwner:'gezamenlijk'}];return materialize(s,[r],'withdraw-batch');}
test('V113 16 spaaropname heeft één doelmutatie en gedeeltelijke budgetcorrectie',()=>{const s=state();withdrawal(s);assert.equal(u.calculateGoalSavedAmount(s,'goal'),1500);assert.equal(coreRows(s).length,1);assert.equal(e.categoryActuals(s,'2026-10','gezamenlijk').Kleding,-300);assert.equal(e.sumTransactionEffects(s,'unusedSavings'),200);assert.equal(total(s),500);});
test('V113 17 meerdere directe budgetcategorieën behouden één spaardoelmutatie',()=>{const s=state(),r=row('w','van-spaarrekening',500,{savingsGoalId:'goal',editorVersion:113});r.processing.splits=[{id:'a',amount:300,transactionType:'van-spaarrekening',withdrawalBudgetCategory:'Kleding',budgetOwner:'gezamenlijk'},{id:'b',amount:200,transactionType:'van-spaarrekening',withdrawalBudgetCategory:'Kleding',budgetOwner:'gezamenlijk'}];materialize(s,[r]);assert.equal(coreRows(s).length,1);assert.equal(e.categoryActuals(s,'2026-10','gezamenlijk').Kleding,-500);assert.equal(u.calculateGoalSavedAmount(s,'goal'),1500);});
test('V113 18 budgetcategorie bij opname is optioneel',()=>{const s=state();withdrawal(s,500,0);assert.equal(e.sumTransactionEffects(s,'unusedSavings'),500);assert.equal(e.sumTransactionEffects(s,'budgetImpact'),0);});
test('V113 19 directe toerekening en bestaande dekking delen capaciteit',()=>{const s=state();withdrawal(s);materialize(s,[row('purchase','uitgave',-200)],'expense-batch');c.setSavingsCoverageAllocation(s,{id:'cover',withdrawalTransactionId:'tx-withdraw',expenseTransactionId:'tx-purchase',amountCents:20000});assert.equal(e.sumTransactionEffects(s,'unusedSavings'),0);assert.equal(e.categoryActuals(s,'2026-10','gezamenlijk').Kleding,-300);assert.equal(u.calculateGoalSavedAmount(s,'goal'),1500);});
test('V113 20 te veel dekking plus directe toerekening blijft atomair ongeldig',()=>{const s=state();withdrawal(s);materialize(s,[row('purchase','uitgave',-300)],'expense-batch');const before=copy(s);assert.throws(()=>c.setSavingsCoverageAllocation(s,{id:'cover',withdrawalTransactionId:'tx-withdraw',expenseTransactionId:'tx-purchase',amountCents:20100}),/dekking|spaaropname/i);assert.deepEqual(s,before);});
test('V113 21 naar sparen behoudt doelstand',()=>{const s=state();materialize(s,[row('deposit','sparen',-250,{savingsGoalId:'goal'})]);assert.equal(u.calculateGoalSavedAmount(s,'goal'),2250);assert.equal(total(s),-250);});
test('V113 22 te grote opname bewaart oude toestand',()=>{const s=state(),before=copy(s);assert.throws(()=>withdrawal(s,2500,0),/Onvoldoende saldo/);assert.deepEqual(s.transactions,before.transactions);});
test('V113 23 terugbetalingsregels corrigeren eigen maanden zonder bankdatum te verplaatsen',()=>{const s=state(),r=row('refund','terugbetaling',100,{editorVersion:113});r.processing.splits=[{id:'a',amount:60,transactionType:'terugbetaling',category:'Terugbetaling',refundCategory:'Kleding',refundMonth:'2026-09',budgetOwner:'gezamenlijk'},{id:'b',amount:40,transactionType:'terugbetaling',category:'Terugbetaling',refundCategory:'Kleding',budgetOwner:'gezamenlijk'}];materialize(s,[r]);assert.equal(e.categoryActuals(s,'2026-09','gezamenlijk').Kleding,-60);assert.equal(e.categoryActuals(s,'2026-10','gezamenlijk').Kleding,-40);assert.equal(b.selectBankTransactions(s)[0].date,'2026-10-03');assert.equal(total(s),100);assert.equal(e.actualIncomeForMonth(s,'2026-10').amount,0);});
test('V113 24 terugbetaling boven belasting maakt gebruik negatief',()=>{const s=state();materialize(s,[row('expense','uitgave',-50)]);materialize(s,[row('refund','terugbetaling',100,{refundCategory:'Kleding',refundMonth:'2026-10'})],'refund-batch');assert.equal(e.categoryActuals(s,'2026-10','gezamenlijk').Kleding,-50);assert.equal(100-e.categoryActuals(s,'2026-10','gezamenlijk').Kleding,150);});
test('V113 25 terugbetaling en sparen veranderen gepland zakgeld niet',()=>{const s=state(),allowance=copy(e.financialForecastForMonth(s,'2026-10').allowanceBasis);withdrawal(s);materialize(s,[row('refund','terugbetaling',100,{refundCategory:'Kleding',refundMonth:'2026-10'})],'refund');assert.deepEqual(e.financialForecastForMonth(s,'2026-10').allowanceBasis,allowance);});
test('V113 26 historisch afgesloten snapshot en planning blijven behouden',()=>{const s=state(),before=copy({planning:s.planning,records:s.monthRecords});withdrawal(s);assert.deepEqual({planning:s.planning,records:s.monthRecords},before);});
for(const status of ['onbekend','nakijken','niet-meetellen','goedgekeurd'])test(`V113 27 bankbeweging onafhankelijk van ${status}`,()=>{const s=state(),r=row('original');const batch={id:'pending',rows:[r],accountProfileId:'joint',accountOwner:'gezamenlijk',summary:{},status:'concept'};r.processingStatus=status;s.importSummaries.push(u.compactSummary(batch));b.ensureImportBankSources(s,batch);assert.equal(total(s),-300);assert.equal(e.sumTransactionEffects(s,'realExpense'),0);assert.deepEqual(b.selectBankTransactions(s)[0].bankOriginal,r.bankOriginal);});
test('V113 28 opnieuw categoriseren behoudt origineel bedrag rekening en identiteit',async()=>{const x=await editor();try{const before=copy(b.selectBankTransactions(x.s)[0]);x.draft.rows[0].processing.processedAmount=200;await u.commitImportEditor(x.root,x.draft,{approveIds:['r']});const after=b.selectBankTransactions(x.s)[0];assert.equal(after.bankAmount,before.bankAmount);assert.deepEqual(after.bankOriginal,before.bankOriginal);assert.equal(after.accountProfileId,before.accountProfileId);assert.equal(after.bankSourceId,before.bankSourceId);}finally{x.mem.restore();}});
test('V113 29 ongeldig concept behoudt goedgekeurde financiële toestand',async()=>{const x=await editor();try{const before=copy(x.s);x.draft.rows[0].processing.singleLineAmount=50;await assert.rejects(u.commitImportEditor(x.root,x.draft,{approveIds:['r']}),/resterende bedrag/);assert.deepEqual(x.s,before);}finally{x.mem.restore();}});
test('V113 30 lokaal bewaren en annuleren veranderen geen effecten',async()=>{const x=await editor();try{const before=copy(x.s);x.draft.rows[0].processing.processedAmount=150;await u.commitImportEditor(x.root,x.draft);assert.deepEqual(x.s,before);await u.ImportStore.deleteJournal('editor-draft-edit');const reopened=await u.beginImportEditor(x.root,x.mem.imports.get('edit'));assert.equal(reopened.rows[0].processing.processedAmount,300);assert.deepEqual(x.s,before);}finally{x.mem.restore();}});
test('V113 31 herhaald opslaan heeft geen dubbele effecten',async()=>{const x=await editor();try{two(x.draft.rows[0].processing);await u.commitImportEditor(x.root,x.draft,{approveIds:['r']});const before=effects(x.s);await u.commitImportEditor(x.root,x.draft,{approveIds:['r']});assert.deepEqual(effects(x.s),before);assert.equal(total(x.s),-300);assert.equal(b.selectBankTransactions(x.s).length,1);}finally{x.mem.restore();}});
test('V113 32 uitsluitend geselecteerde bron wordt toegepast',async()=>{const x=await editor('selected',[row('r'),row('other')]);try{x.draft.rows[0].processing.processedAmount=100;x.draft.rows[1].processing.processedAmount=50;await u.commitImportEditor(x.root,x.draft,{approveIds:['r']});assert.equal(e.sumTransactionEffects(x.s,'realExpense'),400);assert.equal(x.draft.rows[1].processing.processedAmount,50);assert.equal(x.mem.imports.get('selected').rows[1].processing.processedAmount,300);}finally{x.mem.restore();}});
test('V113 33 opslagfout laat oude goedgekeurde toestand intact',async()=>{const x=await editor();try{const before=copy(x.s);u.ImportStore.putImport=async()=>{throw new Error('storage failure');};x.draft.rows[0].processing.processedAmount=100;await assert.rejects(u.commitImportEditor(x.root,x.draft,{approveIds:['r']}),/storage failure/);assert.deepEqual(x.s,before);}finally{x.mem.restore();}});
test('V113 34 conflict via gedeelde bankbron overschrijft geen nieuwere verwerking',async()=>{const x=await editor();try{const source=x.s.transactions.find(b.isBankSource);source.processingRevision++;const before=copy(x.s);await assert.rejects(u.commitImportEditor(x.root,x.draft,{approveIds:['r']}),/andere import|intussen/);assert.deepEqual(x.s,before);}finally{x.mem.restore();}});
test('V113 35 splits blijven uitsluitend financiële resultaten van één bron',()=>{const s=state(),r=row('split');two(r.processing);materialize(s,[r]);assert.equal(coreRows(s).length,2);assert.equal(b.selectBankTransactions(s).length,1);assert.equal(total(s),-300);});
test('V113 36 interne overboeking creëert geen huishoudinkomen of uitgaven',()=>{const s=state(),r=row('transfer','interne-overboeking',-100,{sourceAccountProfileId:'joint',destinationAccountProfileId:'other'});s.accountProfiles.push({id:'other',accountOwner:'dion',identifier:'NL02OTHER'});materialize(s,[r]);assert.equal(total(s),-100);assert.equal(e.sumTransactionEffects(s,'incomeImpact'),0);assert.equal(e.sumTransactionEffects(s,'realExpense'),0);});
test('V113 37 afzonderlijke gelijke betalingen blijven afzonderlijk',()=>{const s=state(),a=row('a'),second=copy(a);second.id='b';materialize(s,[a,second]);assert.equal(b.selectBankTransactions(s).length,2);assert.equal(total(s),-600);});
test('V113 38 fysieke rekeningen van dezelfde eigenaar blijven onderscheiden',()=>{const s=state();s.accountProfiles.push({id:'second',identifier:'NL02JOINT',accountOwner:'gezamenlijk'});const A=materialize(s,[row('a')],'A'),r=row('b');r.bankOriginal.accountIdentifier='NL02JOINT';const B={...copy(A),id:'B',accountProfileId:'second',rows:[r]};s.importSummaries.push(u.compactSummary(B));const plan=u.planImportEffects(B,s);assert.equal(plan.ok,true);u.applyImportPlan(s,plan);assert.equal(b.selectBankTransactions(s).length,2);assert.equal(b.selectBankTransactions(s,{accountId:'second'}).length,1);});
test('V113 39 oude transacties zonder aanvullende velden blijven projecteervaar',()=>{const s=state();materialize(s,[row('legacy')]);s.transactions=coreRows(s);s.transactions.forEach(tx=>delete tx.bankSourceId);assert.equal(total(s),-300);assert.equal(e.sumTransactionEffects(s,'realExpense'),300);});
test('V113 40 overlappende imports ondersteunen één bankbron',()=>{const s=state(),A=materialize(s,[row('r')],'A');overlap(s,A);assert.equal(b.selectBankTransactions(s).length,1);assert.equal(total(s),-300);assert.equal(e.sumTransactionEffects(s,'realExpense'),300);});
test('V113 41 A terugtrekken met B actief behoudt bron en effecten',()=>{const s=state(),A=materialize(s,[row('r')],'A');overlap(s,A);const before=effects(s),out=command(s,A,'withdraw');assert.equal(total(out.state),-300);assert.deepEqual(effects(out.state),before);});
test('V113 42 A herstellen met B actief maakt geen duplicaat',()=>{const s=state(),A=materialize(s,[row('r')],'A');overlap(s,A);const out=command(s,A,'withdraw'),restored=command(out.state,out.batch,'restore');assert.equal(total(restored.state),-300);assert.equal(e.sumTransactionEffects(restored.state,'realExpense'),300);});
test('V113 43 alle imports terugtrekken maakt bron en effecten inactief',()=>{const s=state(),A=materialize(s,[row('r')],'A'),B=overlap(s,A);const a=command(s,A,'withdraw'),out=command(a.state,B,'withdraw');assert.equal(total(out.state),0);assert.equal(e.sumTransactionEffects(out.state,'realExpense'),0);assert.equal(b.selectBankTransactions(out.state,{includeInactive:true}).length,1);});
test('V113 44 één import herstellen activeert bron eenmaal',()=>{const s=state(),A=materialize(s,[row('r')],'A'),B=overlap(s,A);const a=command(s,A,'withdraw'),out=command(a.state,B,'withdraw'),restored=command(out.state,out.batch,'restore');assert.equal(total(restored.state),-300);assert.equal(e.sumTransactionEffects(restored.state,'realExpense'),300);});
test('V113 45 A verwijderen terwijl B actief blijft behoudt bankbron',()=>{const s=state(),A=materialize(s,[row('r')],'A');overlap(s,A);const out=command(s,A,'delete');assert.equal(total(out.state),-300);assert.equal(e.sumTransactionEffects(out.state,'realExpense'),300);assert.equal(out.state.transactions.find(b.isBankSource).importReferences.length,1);});
test('V113 46 laatste import verwijderen volgt verwijderprotocol',()=>{const s=state(),A=materialize(s,[row('r')],'A'),B=overlap(s,A);const a=command(s,A,'delete'),out=command(a.state,B,'delete');assert.equal(total(out.state),0);assert.equal(coreRows(out.state).length,0);assert.equal(out.state.importDeletionProofs.length,2);});
test('V113 47 herhaald terugtrekken en herstellen is idempotent',()=>{const s=state(),A=materialize(s,[row('r')],'A');let x={state:s,batch:A};for(let i=0;i<3;i++){x=command(x.state,x.batch,'withdraw');x=command(x.state,x.batch,'withdraw');x=command(x.state,x.batch,'restore');x=command(x.state,x.batch,'restore');}assert.equal(total(x.state),-300);assert.equal(e.sumTransactionEffects(x.state,'realExpense'),300);});
test('V113 48 gedeelde spaarverwerking behoudt stand en effect-ID',()=>{const s=state(),A=withdrawal(s);overlap(s,A);const before=effects(s),out=command(s,A,'withdraw');assert.equal(u.calculateGoalSavedAmount(out.state,'goal'),1500);assert.deepEqual(effects(out.state),before);});
test('V113 49 meerdere imports vergelijken dezelfde bankbron bij cloudconflict',()=>{const s=state(),A=materialize(s,[row('r')],'A');overlap(s,A);const local=copy(s),remote=copy(s);local.transactions.find(b.isBankSource).processingRevision=2;remote.transactions.find(b.isBankSource).processingRevision=3;assert.ok(sync.findImportConflicts(s,local,remote).some(x=>x.kind==='source'));});
test('V113 50 correcte oudere bron vereist geen herstel',()=>{const s=state(),A=materialize(s,[row('r')]);assert.equal(repair.inspectSourceAvailability(s,coreRows(s)[0],A).ok,true);});
function broken(){const s=state(),A=materialize(s,[row('r')]);s.transactions=coreRows(s);s.transactions.forEach(tx=>delete tx.bankSourceId);return {s,A,tx:s.transactions[0]};}
test('V113 51 ontbrekende importregel kan bevestigd aan bestaande transactie worden hersteld',()=>{const x=broken(),old=effects(x.s);const out=repair.planSourceRepair(x.s,x.tx.id,null,x.A.rows[0].bankOriginal,{confirmed:true,operationId:'repair',timestamp:'2026-10-06'});assert.equal(coreRows(out.state).length,1);assert.equal(total(out.state),-300);assert.deepEqual(effects(out.state),old);assert.equal(out.batch.rows[0].processing.category,'Kleding');});
test('V113 52 herstel behoudt splits en goedgekeurde categorieën',()=>{const s=state(),r=row('r');two(r.processing);const A=materialize(s,[r]);s.transactions=coreRows(s);s.transactions.forEach(tx=>delete tx.bankSourceId);const out=repair.planSourceRepair(s,s.transactions[0].id,null,r.bankOriginal,{confirmed:true,operationId:'repair',timestamp:'2026-10-06'});assert.deepEqual(out.batch.rows[0].processing.splits,r.processing.splits);assert.equal(total(out.state),-300);});
test('V113 53 onvoldoende bewijs zonder bevestiging maakt geen koppeling',()=>{const x=broken(),before=copy(x.s);assert.throws(()=>repair.planSourceRepair(x.s,x.tx.id,null,x.A.rows[0].bankOriginal,{confirmed:false}),/Bevestig/);assert.deepEqual(x.s,before);});
test('V113 54 verkeerde rekening en bedrag leveren geen herstelvoorstel',()=>{const x=broken(),bank=x.A.rows[0].bankOriginal;assert.deepEqual(repair.sourceRepairCandidates(x.s,x.tx,[{...bank,accountIdentifier:'NL99WRONG'},{...bank,amount:-299}]),[]);});
test('V113 55 ontbrekend rekeningkenmerk forceert geen onzekere koppeling',()=>{const x=broken();delete x.tx.bankOriginal.accountIdentifier;x.s.accountProfiles=[];assert.throws(()=>repair.sourceRepairCandidates(x.s,x.tx,x.A.rows.map(r=>r.bankOriginal)),/rekeningkenmerk/);});
test('V113 56 herstelback-up wordt teruggelezen vóór opslag',async()=>{const x=broken(),mem=memory(),root={state:x.s,commitChange:fn=>{fn();return true;}};try{let saved;const out=await u.commitSourceRepair(root,x.tx.id,null,x.A.rows[0].bankOriginal,{confirmed:true,backupStore:{persist:async(_scope,envelope)=>{saved=copy(envelope);return {id:'backup',payload:JSON.stringify(saved)};}}});assert.deepEqual(saved.state.transactions.length,1);assert.equal(total(out.state),-300);assert.equal(mem.imports.size,1);}finally{mem.restore();}});
test('V113 57 beschadigde back-up blokkeert herstel zonder wijzigingen',async()=>{const x=broken(),mem=memory(),before=copy(x.s);try{await assert.rejects(u.commitSourceRepair({state:x.s},x.tx.id,null,x.A.rows[0].bankOriginal,{confirmed:true,backupStore:{persist:async()=>({payload:'{}'})}}));assert.deepEqual(x.s,before);assert.equal(mem.imports.size,0);}finally{mem.restore();}});
test('V113 58 opslagfout tijdens herstel bewaart oorspronkelijke toestand',async()=>{const x=broken(),mem=memory(),before=copy(x.s);try{u.ImportStore.putImport=async()=>{throw new Error('disk full');};await assert.rejects(u.commitSourceRepair({state:x.s},x.tx.id,null,x.A.rows[0].bankOriginal,{confirmed:true,backupStore:{persist:async(_scope,envelope)=>({id:'backup',payload:JSON.stringify(envelope)})}}),/disk full/);assert.deepEqual(x.s,before);}finally{mem.restore();}});
test('V113 59 synchronisatie tijdens herstel overschrijft geen nieuwere wijziging',async()=>{const x=broken(),mem=memory();try{await assert.rejects(u.commitSourceRepair({state:x.s},x.tx.id,null,x.A.rows[0].bankOriginal,{confirmed:true,backupStore:{persist:async(_scope,envelope)=>{const payload=JSON.stringify(envelope);x.s.meta.revision++;return {id:'backup',payload};}}}),/intussen gewijzigd/);assert.equal(x.s.meta.revision,2);assert.equal(mem.imports.size,0);}finally{mem.restore();}});
test('V113 60 normale bronreparatie kan nooit een bestaande geldige bron vervangen',()=>{const s=state(),A=materialize(s,[row('r')]);assert.throws(()=>repair.planSourceRepair(s,coreRows(s)[0].id,A,A.rows[0].bankOriginal,{confirmed:true}),/niet nodig/);});
test('V113 61 verwijderen laatste actieve import behoudt verwerking voor inactieve andere import',()=>{const s=state(),A=materialize(s,[row('r')],'A'),B=overlap(s,A);const inactiveB=command(s,B,'withdraw'),deletedA=command(inactiveB.state,A,'delete');assert.equal(total(deletedA.state),0);assert.equal(coreRows(deletedA.state).length,1);const restored=command(deletedA.state,inactiveB.batch,'restore');assert.equal(total(restored.state),-300);assert.equal(e.sumTransactionEffects(restored.state,'realExpense'),300);});
test('V113 62 gedeelde handmatige vervanging blijft onderdrukt bij terugtrekken en verwijderen A',()=>{const s=state(),A=materialize(s,[row('r')],'A');s.transactions.push({id:'manual',source:'manual',processingStatus:'goedgekeurd',transactionType:'uitgave',accountContext:'gezamenlijk',financialFor:'gezamenlijk',date:'2026-10-03',amount:300,category:'Kleding'});s.manualTransactionReplacements=[{id:'replacement-A-manual',manualTransactionId:'manual',importBatchId:'A',importTransactionId:'r',active:true}];const B=overlap(s,A);const out=command(s,A,'withdraw');assert.equal(total(out.state),-300);assert.equal(out.state.manualTransactionReplacements[0].active,true);const deleted=command(out.state,out.batch,'delete');assert.equal(total(deleted.state),-300);const inactive=command(deleted.state,B,'withdraw');assert.equal(inactive.state.manualTransactionReplacements[0].active,false);assert.equal(total(inactive.state),-300);});
test('V113 63 oude spaardekking via bronkey blijft geldig bij minimale bronuitbreiding',()=>{const s=state(),A=materialize(s,[row('withdraw','van-spaarrekening',500,{savingsGoalId:'goal'}),row('purchase','uitgave',-300)],'A');s.transactions=coreRows(s);s.transactions.forEach(tx=>delete tx.bankSourceId);c.setSavingsCoverageAllocation(s,{id:'old-cover',withdrawalTransactionId:'tx-withdraw',withdrawalSourceKey:'A:withdraw',withdrawalSplitId:'',expenseTransactionId:'tx-purchase',expenseSourceKey:'A:purchase',expenseSplitId:'',amountCents:20000});const before=e.categoryActuals(s,'2026-10','gezamenlijk');overlap(s,A);assert.deepEqual(e.categoryActuals(s,'2026-10','gezamenlijk'),before);assert.equal(e.coverageAllocationStatus(s)[0].active,true);});
test('V113 64 gedeeltelijk verloren bronbedrag kan alleen bevestigd worden aangevuld',()=>{const x=broken(),original=copy(x.A.rows[0].bankOriginal);delete x.tx.bankOriginal.amount;const evidence=copy(x.tx.bankOriginal),before=effects(x.s);assert.equal(repair.inspectSourceAvailability(x.s,x.tx,x.A).ok,false);const out=repair.planSourceRepair(x.s,x.tx.id,x.A,original,{confirmed:true,operationId:'repair-partial',timestamp:'2026-10-06'});assert.equal(total(out.state),-300);assert.deepEqual(coreRows(out.state)[0].bankOriginal,evidence);assert.deepEqual(effects(out.state),before);assert.equal(out.state.transactions.find(b.isBankSource).bankOriginal.amount,-300);});
test('V113 65 gedeelde vaste-lastkoppelingen en afwijkingen blijven behouden',()=>{const s=fixedState(),r=row('r','vaste-last',-90,{fixedExpenseId:'fixed-a'});u.selectFixedOccurrence({state:s},r,r.processing);const A=materialize(s,[r],'A');overlap(s,A);const occurrence={id:r.processing.fixedOccurrenceId,month:'2026-10',amount:100},before=e.fixedOccurrenceActuals(s,occurrence);const out=command(s,A,'delete');assert.equal(e.fixedOccurrenceActuals(out.state,occurrence).actual,before.actual);assert.equal(e.fixedOccurrenceActuals(out.state,occurrence).deviation,-10);assert.equal(e.fixedOccurrenceActuals(out.state,occurrence).paid,true);});
test('V113 66 gewijzigde vaste-lastkoppeling wordt Onbetaald zonder achtergebleven betaling',async()=>{const x=await editor('fixed-edit',[row('r')]);try{x.s.recurringFixedExpenses=fixedState().recurringFixedExpenses;Object.assign(x.draft.rows[0].processing,{transactionType:'vaste-last',fixedExpenseId:'fixed-a'});u.selectFixedOccurrence(x.root,x.draft.rows[0],x.draft.rows[0].processing);const occurrence={id:x.draft.rows[0].processing.fixedOccurrenceId,month:'2026-10',amount:100};await u.commitImportEditor(x.root,x.draft,{approveIds:['r']});assert.equal(e.fixedOccurrenceActuals(x.s,occurrence).paid,true);u.applyTransactionFamily(x.draft.rows[0],'uitgave');x.draft.rows[0].processing.category='Kleding';await u.commitImportEditor(x.root,x.draft,{approveIds:['r']});assert.equal(e.fixedOccurrenceActuals(x.s,occurrence).paid,false);assert.equal(total(x.s),-300);}finally{x.mem.restore();}});
test('V113 67 directe spaarcorrecties volgen hun eigen budgeteigenaar',()=>{const s=state();s.budgetDefaultsHistory.dion=copy(s.budgetDefaultsHistory.gezamenlijk);const r=row('r','van-spaarrekening',500,{savingsGoalId:'goal',editorVersion:113});r.processing.splits=[{id:'dion',amount:300,transactionType:'van-spaarrekening',withdrawalBudgetCategory:'Kleding',budgetOwner:'dion'},{id:'joint',amount:200,transactionType:'van-spaarrekening',budgetOwner:'gezamenlijk'}];materialize(s,[r]);assert.equal(e.categoryActuals(s,'2026-10','dion').Kleding,-300);assert.equal(e.categoryActuals(s,'2026-10','gezamenlijk').Kleding,undefined);assert.equal(total(s),500);});

test('V113 68 beschadigd bronheader wordt bevestigd hersteld met behoud van effecten en bron-ID',()=>{const s=state(),A=materialize(s,[row('r')]);const header=s.transactions.find(b.isBankSource),id=header.bankSourceId,before=effects(s);delete header.bankOriginal.amount;const out=repair.planSourceRepair(s,header.id,A,A.rows[0].bankOriginal,{confirmed:true,operationId:'header-repair',timestamp:'2026-10-06'});assert.equal(total(out.state),-300);assert.deepEqual(effects(out.state),before);assert.equal(out.state.transactions.find(b.isBankSource).bankSourceId,id);assert.equal(out.batch.sourceRepairHistory.length,1);});
test('V113 69 legacy undo route respecteert gedeelde importondersteuning',()=>{const s=state(),A=materialize(s,[row('r')],'A');overlap(s,A);u.undoImportEffects(s,A);assert.equal(total(s),-300);assert.equal(e.sumTransactionEffects(s,'realExpense'),300);});
test('V113 70 herbewerken verplaatst een bankbron nooit naar een ander rekeningprofiel',()=>{const s=state(),A=materialize(s,[row('r')],'A');s.accountProfiles.push({id:'dion-other',accountOwner:'dion',identifier:'NL02OTHER'});const changed={...copy(A),accountProfileId:'dion-other',accountOwner:'dion'};changed.rows[0].accountOwner='dion';changed.rows[0].processing.budgetOwner='dion';const plan=u.planImportEffects(changed,s);assert.equal(plan.ok,true);assert.equal(plan.transactions[0].accountProfileId,'joint');assert.equal(plan.transactions[0].accountContext,'gezamenlijk');assert.equal(plan.transactions[0].financialFor,'dion');});

test('V113 71 directe spaarcorrectie staat in centrale categoriedetails en maandtotalen',()=>{const s=state(),r=row('r','van-spaarrekening',500,{savingsGoalId:'goal',editorVersion:113});r.processing.splits=[{id:'budget',amount:300,transactionType:'van-spaarrekening',withdrawalBudgetCategory:'Kleding',budgetOwner:'gezamenlijk'},{id:'none',amount:200,transactionType:'van-spaarrekening',budgetOwner:'gezamenlijk'}];materialize(s,[r]);const details=e.categoryProcessingDetails(s,'2026-10','gezamenlijk');assert.equal(details.length,1);assert.equal(details[0].category,'Kleding');assert.equal(details[0].displayImpact,-300);assert.equal(e.sumTransactionEffects(s,'savingsFunded',{month:'2026-10'}),300);assert.equal(total(s),500);});

test('V113 72 huishoudwissel tijdens herstelback-up kan geen bron wijzigen',async()=>{const x=broken(),mem=memory(),scope=u.ImportStore.scope,before=copy(x.s);try{await assert.rejects(u.commitSourceRepair({state:x.s},x.tx.id,null,x.A.rows[0].bankOriginal,{confirmed:true,backupStore:{persist:async(_scope,envelope)=>{u.ImportStore.scope='other-household';return {id:'backup',payload:JSON.stringify(envelope)};}}}),/intussen gewijzigd/);assert.deepEqual(x.s,before);assert.equal(mem.imports.size,0);}finally{u.ImportStore.scope=scope;mem.restore();}});

test('V113 73 oudere nog niet verwerkte import is leesbaar als bankbron zonder migratie',()=>{const s=state(),r=row('old');r.processingStatus='onbekend';r.certainty='onbekend';r.approvalSource='';const A={id:'old-batch',accountProfileId:'joint',accountOwner:'gezamenlijk',lifecycle:'active',rows:[r],summary:{}};s.importSummaries=[{id:A.id,lifecycle:'active',status:'concept'}];const before=copy(s),original=copy(A);assert.equal(b.selectBankTransactions(s,{imports:[A]}).length,1);assert.equal(b.selectBankTransactions(s,{imports:[A]})[0].bankAmount,-300);assert.deepEqual(s,before);assert.deepEqual(A,original);assert.equal(e.sumTransactionEffects(s,'realExpense'),0);s.importSummaries[0].lifecycle='withdrawn';assert.equal(b.selectBankTransactions(s,{imports:[A]}).length,0);});
test('V113 74 oude overlappende onverwerkte imports delen uitsluitend een gelezen bankbron',()=>{const s=state(),r=row('old'),A={id:'A',accountProfileId:'joint',accountOwner:'gezamenlijk',rows:[r]},B={...copy(A),id:'B',rows:[{...copy(r),id:'alias',duplicate:true,duplicateSource:{batchId:'A',rowId:'old'}}]};s.importSummaries=[{id:'A',lifecycle:'withdrawn'},{id:'B',lifecycle:'active'}];const before=copy(s);assert.equal(b.selectBankTransactions(s,{imports:[A,B]}).length,1);assert.equal(b.selectBankTransactions(s,{imports:[A,B]})[0].bankAmount,-300);assert.deepEqual(s,before);assert.equal(e.sumTransactionEffects(s,'realExpense'),0);});

test('V113 75 opgeslagen financiële referentie behoudt effecten forecast planning en snapshots',()=>{const reference=require('./fixtures/v113-financial-reference.json'),s=copy(reference.state),before=copy(s);const dimensions=rows=>rows.map(p=>({id:p.id,source:p.source,accountContext:p.accountContext,financialFor:p.financialFor,status:p.status,active:p.active,transactionType:p.transactionType,amount:p.amount,calendarMonth:p.calendarMonth,financialMonth:p.financialMonth,effects:{directSavingsCorrection:0,...p.effects}}));assert.deepEqual(dimensions(e.selectTransactionProjections(s)),dimensions(reference.effects));assert.deepEqual(e.financialForecastForMonth(s,reference.forecast.month),reference.forecast);assert.deepEqual(s,before);});

test('V113 76 fout in synchronisatiewachtrij draait importdetails terug en wordt niet hervat',async()=>{const x=await editor(),before=copy(x.s),original=copy(x.mem.imports.get('edit')),putSync=u.ImportStore.putSync;try{u.ImportStore.putSync=async()=>{throw new Error('outbox full');};x.draft.rows[0].processing.processedAmount=100;await assert.rejects(u.commitImportEditor(x.root,x.draft,{approveIds:['r']}),/outbox full/);assert.deepEqual(x.s,before);assert.deepEqual(x.mem.imports.get('edit'),original);assert.ok([...x.mem.journals.values()].some(j=>j.operation==='import-command'&&j.status==='rolled-back'));u.ImportStore.putSync=putSync;await u.recoverJournal(x.root);assert.deepEqual(x.s,before);assert.deepEqual(x.mem.imports.get('edit'),original);}finally{x.mem.restore();}});
test('V113 77 afgebroken financiële commit draait opgeslagen importdetails terug',async()=>{const x=await editor(),before=copy(x.s),original=copy(x.mem.imports.get('edit'));try{x.root.commitChange=()=>false;x.draft.rows[0].processing.processedAmount=100;await assert.rejects(u.commitImportEditor(x.root,x.draft,{approveIds:['r']}),/afgebroken/);assert.deepEqual(x.s,before);assert.deepEqual(x.mem.imports.get('edit'),original);assert.equal(x.mem.queue.size,0);await u.recoverJournal(x.root);assert.deepEqual(x.s,before);}finally{x.mem.restore();}});
test('V113 78 mislukte importopslag blijft na journalherstel ongewijzigd',async()=>{const x=await editor(),before=copy(x.s),putImport=u.ImportStore.putImport;try{u.ImportStore.putImport=async()=>{throw new Error('disk full');};x.draft.rows[0].processing.processedAmount=100;await assert.rejects(u.commitImportEditor(x.root,x.draft,{approveIds:['r']}),/disk full/);u.ImportStore.putImport=putImport;await u.recoverJournal(x.root);assert.deepEqual(x.s,before);}finally{x.mem.restore();}});
test('V113 79 open editor kan na huishoudwissel geen concept of verwerking schrijven',async()=>{const x=await editor(),before=copy(x.s),scope=u.ImportStore.scope,original=copy([...x.mem.imports]);try{u.ImportStore.scope='different-household';x.draft.rows[0].processing.processedAmount=100;await assert.rejects(u.commitImportEditor(x.root,x.draft,{approveIds:['r']}),/huishouden/);await assert.rejects(u.commitImportEditor(x.root,x.draft),/huishouden/);assert.deepEqual(x.s,before);assert.deepEqual([...x.mem.imports],original);assert.equal(x.mem.journals.size,0);assert.equal(x.mem.queue.size,0);}finally{u.ImportStore.scope=scope;x.mem.restore();}});
test('V113 80 storing na duurzame financiële ontvangstbevestiging rondt bij herstart eenmaal af',async()=>{const x=await editor(),putJournal=u.ImportStore.putJournal;try{u.ImportStore.putJournal=async j=>{if(j.operation==='import-command'&&j.status==='completed')throw new Error('receipt cleanup failed');return putJournal(j);};x.draft.rows[0].processing.processedAmount=100;await u.commitImportEditor(x.root,x.draft,{approveIds:['r']});assert.equal(e.sumTransactionEffects(x.s,'realExpense'),100);assert.equal(total(x.s),-300);assert.ok([...x.mem.journals.values()].some(j=>j.operation==='import-command'&&j.status==='pending'));u.ImportStore.putJournal=putJournal;await u.recoverJournal(x.root);await u.recoverJournal(x.root);assert.equal(e.sumTransactionEffects(x.s,'realExpense'),100);assert.equal(total(x.s),-300);assert.ok([...x.mem.journals.values()].some(j=>j.operation==='import-command'&&j.status==='completed'));}finally{x.mem.restore();}});
test('V113 81 opruimfout na opgeslagen verwerking meldt geen mislukte financiële commit',async()=>{const x=await editor();try{u.ImportStore.deleteJournal=async()=>{throw new Error('concept cleanup failed');};x.draft.rows[0].processing.processedAmount=100;await u.commitImportEditor(x.root,x.draft,{approveIds:['r']});assert.equal(e.sumTransactionEffects(x.s,'realExpense'),100);assert.equal(total(x.s),-300);assert.equal(x.mem.imports.get('edit').rows[0].processing.processedAmount,100);}finally{x.mem.restore();}});
