const assert=require('node:assert/strict'),l=require('../../src/import/import-lifecycle.mjs');
const u=require('../../src/import/update4-runtime.cjs'),sync=require('../../src/import/import-sync-protocol.mjs'),copy=x=>JSON.parse(JSON.stringify(x));
function state(){return {meta:{schemaVersion:11,revision:1},planning:{verdeling:{minimumDion:.4},spaarpotDezeMaand:250},budgetDefaultsHistory:{gezamenlijk:[{effectiveFrom:'0000-01',rows:[{id:'food',post:'Kleding',bedrag:500}]}],dion:[],dara:[]},incomeDefaultsHistory:{dion:[{effectiveFrom:'0000-01',salary:3000}],dara:[{effectiveFrom:'0000-01',salary:2000}]},transactions:[],recurringFixedExpenses:[],spaardoelen:{gezamenlijk:[{id:'goal',naam:'Vakantie',algespaard:2000}],dion:[],dara:[]},savingsGoalLedger:[{id:'opening',goalId:'goal',source:'legacy-opening',effectiveAmount:2000,active:true}],savingsCoverageAllocations:[],monthlySavingOverrides:{},accountProfiles:[{id:'joint',accountOwner:'gezamenlijk',identifier:'NL01JOINT'}],importSummaries:[],advanceLedger:[],advanceRepayments:[],internalTransferPairs:[],manualTransactionReplacements:[],monthRecords:{'2026-08':{status:'afgesloten',snapshot:{income:123,expenses:55},closureHistory:[{source:'original'}]}}};}
function row(id,type='uitgave',amount=-300,extra={}){const row={id,source:'csv',accountOwner:'gezamenlijk',certainty:'nakijken',recognitionState:'known',bankOriginal:{valid:true,bankDate:'2026-10-03',amount,description:id,rawDescription:id,accountIdentifier:'NL01JOINT',rawCells:[id,String(amount)]},processing:{processingDate:'2026-10-03',processedAmount:Math.abs(amount),description:id,category:'Kleding',budgetOwner:'gezamenlijk',advanceMode:'none',fixedAmountMode:'none',include:true,splits:[],transactionType:type,...extra}};u.markExplicitlyApproved(row);return row;}
function materialize(s,rows,id='batch'){const batch={id,status:'concept',lifecycle:'active',version:1,operationId:id+'-initial',accountProfileId:'joint',accountOwner:'gezamenlijk',rows,summary:{}};u.updateDraftSummary(batch);s.importSummaries.push(u.compactSummary(batch));const plan=u.planImportEffects(batch,s);assert.equal(plan.ok,true,JSON.stringify(plan.errors));u.applyImportPlan(s,plan);batch.effectManifest=u.effectManifest(plan);batch.status='verwerkt';return batch;}
function command(s,b,type){return l.planImportCommand(s,b,{type,operationId:b.id+'-'+type,timestamp:'2026-10-06T12:00:00Z'},{validateRow:u.rowProcessingValidation});}
function cycle(s,b){const withdrawn=command(s,b,'withdraw'),restored=command(withdrawn.state,withdrawn.batch,'restore');return {withdrawn,restored};}
function fixed(s){s.recurringFixedExpenses=[{id:'fixed',naam:'Hypotheek',categorie:'Wonen',bedrag:100,financialFor:'gezamenlijk',rekening:'gezamenlijk',begindatum:'2026-01-01',actief:true,frequentieAantal:1,frequentieEenheid:'maanden',amountHistory:[{effectiveFrom:'2026-01-01',amount:100}]}];}
function memory(){const original={};for(const key of ['putImport','getImport','listImports','putJournal','getJournal','listJournal','deleteJournal','putSync','listSync','deleteSync','deleteImport','rollbackImport','confirmCloudReceipt'])original[key]=u.ImportStore[key];const imports=new Map(),journals=new Map(),queue=new Map();Object.assign(u.ImportStore,{putImport:async r=>imports.set(r.id,copy(r)),getImport:async id=>imports.has(id)?copy(imports.get(id)):undefined,listImports:async()=>[...imports.values()].map(copy),deleteImport:async id=>imports.delete(id),rollbackImport:async(expected,previous,previousQueue)=>{assert.equal(imports.get(expected.id)?.operationId,expected.operationId);if(previous)imports.set(expected.id,copy(previous));else imports.delete(expected.id);if(previousQueue)queue.set(expected.id,copy(previousQueue));else queue.delete(expected.id);},putJournal:async r=>journals.set(r.id,copy(r)),getJournal:async id=>journals.has(id)?copy(journals.get(id)):undefined,listJournal:async()=>[...journals.values()].map(copy),deleteJournal:async id=>journals.delete(id),putSync:async r=>queue.set(r.id,copy(r)),listSync:async()=>[...queue.values()].map(copy),deleteSync:async id=>queue.delete(id),confirmCloudReceipt:async(receipt,record)=>{const current=imports.get(receipt.id);if(current&&current.version>=receipt.version){current.baseVersion=receipt.version;current.confirmedBatch=copy(record);}if(sync.acknowledgeMatches(queue.get(receipt.id),receipt))queue.delete(receipt.id);}});return {imports,journals,queue,restore:()=>Object.assign(u.ImportStore,original)};}

module.exports={state,row,materialize,memory,copy};
